// Code generated by wit-bindgen-go. DO NOT EDIT.

package walletgo

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "mududb:wallet-go".

//go:wasmexport mp2-create-user
//export mp2-create-user
func wasmexport_Mp2CreateUser(param0 *uint8, param1 uint32) (result *cm.List[uint8]) {
	param := cm.LiftList[cm.List[uint8]]((*uint8)(param0), (uint32)(param1))
	result_ := Exports.Mp2CreateUser(param)
	result = &result_
	return
}

//go:wasmexport mp2-deposit
//export mp2-deposit
func wasmexport_Mp2Deposit(param0 *uint8, param1 uint32) (result *cm.List[uint8]) {
	param := cm.LiftList[cm.List[uint8]]((*uint8)(param0), (uint32)(param1))
	result_ := Exports.Mp2Deposit(param)
	result = &result_
	return
}

//go:wasmexport mp2-withdraw
//export mp2-withdraw
func wasmexport_Mp2Withdraw(param0 *uint8, param1 uint32) (result *cm.List[uint8]) {
	param := cm.LiftList[cm.List[uint8]]((*uint8)(param0), (uint32)(param1))
	result_ := Exports.Mp2Withdraw(param)
	result = &result_
	return
}

//go:wasmexport mp2-transfer-funds
//export mp2-transfer-funds
func wasmexport_Mp2TransferFunds(param0 *uint8, param1 uint32) (result *cm.List[uint8]) {
	param := cm.LiftList[cm.List[uint8]]((*uint8)(param0), (uint32)(param1))
	result_ := Exports.Mp2TransferFunds(param)
	result = &result_
	return
}

//go:wasmexport mp2-balance
//export mp2-balance
func wasmexport_Mp2Balance(param0 *uint8, param1 uint32) (result *cm.List[uint8]) {
	param := cm.LiftList[cm.List[uint8]]((*uint8)(param0), (uint32)(param1))
	result_ := Exports.Mp2Balance(param)
	result = &result_
	return
}

//go:wasmexport mp2-update-profile
//export mp2-update-profile
func wasmexport_Mp2UpdateProfile(param0 *uint8, param1 uint32) (result *cm.List[uint8]) {
	param := cm.LiftList[cm.List[uint8]]((*uint8)(param0), (uint32)(param1))
	result_ := Exports.Mp2UpdateProfile(param)
	result = &result_
	return
}
