#nullable enable

using mududb;
using mududb.codec;
using mududb.mock;
using mududb.sys;
using Xunit;

namespace mududb.tests;

/// <summary>
/// Byte-level snapshots of the MSSP request frames emitted by the new
/// <c>Sys*</c> methods (captured at the mock boundary) and of the
/// corresponding result frames built by <see cref="SyscallPayload"/>. All
/// expected hex is hand-derived from
/// `mudu_binding::codec::syscall_payload::router` and is meant to be
/// cross-checked against golden frames generated by the Rust host codec.
///
/// Fixture inputs (shared with the golden-frame phase):
/// - oid:      UniOid { H = 0x0123456789ABCDEF, L = 0xFEDCBA9876543210 }
/// - key:      "alpha" (ASCII); value: [0x01, 0x02, 0x03]
/// - range:    start "a", end "z"
/// - batch:    sql "INSERT INTO t VALUES (1)", no params
/// - relation: table "users", key [(1, [01 02 03])], values [(2, [04 05])],
///             deltas [Add(3, [06 07])], select [2, 300]
/// - error:    UniError { 50012, "duplicate", "test", "", [1, 2] }
/// </summary>
[Collection("MockBackend")]
public class SyscallPayloadSnapshotTests
{
    private static readonly UniOid Oid = new() { H = 0x0123456789ABCDEF, L = 0xFEDCBA9876543210 };

    // UniOid {1: H, 2: L} with both limbs above u32::MAX, exercising the 0xCF
    // (uint64) MessagePack marker and big-endian limb order.
    private const string OidHex = "8201CF0123456789ABCDEF02CFFEDCBA9876543210";

    // 4D535350 "MSSP", version 1, flags 0; the kind fills the last 4 bytes.
    private const string HeaderPrefix = "4D5353500000000100000000";

    private const string KeyAlphaHex = "C405616C706861"; // bin "alpha"
    private const string ValueHex = "C403010203"; // bin [01 02 03]

    [Fact]
    public void OpenRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysOpen(Oid));
        Assert.Equal(HeaderPrefix + "00000004" + "81" + "01" + OidHex, hex);
    }

    [Fact]
    public void CloseRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysClose(Oid));
        Assert.Equal(HeaderPrefix + "00000005" + "81" + "01" + OidHex, hex);
    }

    [Fact]
    public void GetRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysGet(Oid, "alpha"u8.ToArray()));
        Assert.Equal(HeaderPrefix + "00000006" + "82" + "01" + OidHex + "02" + KeyAlphaHex, hex);
    }

    [Fact]
    public void PutRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysPut(Oid, "alpha"u8.ToArray(), [0x01, 0x02, 0x03]));
        Assert.Equal(HeaderPrefix + "00000007" + "83" + "01" + OidHex + "02" + KeyAlphaHex + "03" + ValueHex, hex);
    }

    [Fact]
    public void DeleteRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysDelete(Oid, "alpha"u8.ToArray()));
        Assert.Equal(HeaderPrefix + "00000008" + "82" + "01" + OidHex + "02" + KeyAlphaHex, hex);
    }

    [Fact]
    public void RangeRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysRange(Oid, "a"u8.ToArray(), "z"u8.ToArray()));
        Assert.Equal(HeaderPrefix + "00000009" + "83" + "01" + OidHex + "02" + "C40161" + "03" + "C4017A", hex);
    }

    [Fact]
    public void BatchRequestFrameMatchesSnapshot()
    {
        var argv = new UniCommandArgv
        {
            Oid = Oid,
            Command = new UniSqlStmt { SqlString = "INSERT INTO t VALUES (1)" },
            ParamList = new UniSqlParam { Params = [] },
        };
        var hex = CaptureFrame(() => MuduSysCallApi.SysBatch(argv));
        // "INSERT INTO t VALUES (1)" is 24 chars: fixstr 0xB8.
        const string sqlHex = "B8494E5345525420494E544F20742056414C55455320283129";
        // argv {1: oid, 2: {1: sql}, 3: {1: []}} as the single request-map value.
        Assert.Equal(
            HeaderPrefix + "00000003" + "81" + "01"
            + "83" + "01" + OidHex + "02" + "81" + "01" + sqlHex + "03" + "81" + "01" + "90",
            hex);
    }

    [Fact]
    public void RelationGetRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysRelationGet(
            Oid,
            "users",
            [(1UL, new byte[] { 0x01, 0x02, 0x03 })],
            [2UL, 300UL]));
        // key [[1, bin 010203]], select [2, 300]: 300 encodes as uint16 0xCD 0x012C;
        // the func-level tuples stay arrays inside the integer-keyed request map.
        Assert.Equal(
            HeaderPrefix + "00000015" + "84" + "01" + OidHex + "02" + "A57573657273"
            + "03" + "91" + "92" + "01" + ValueHex
            + "04" + "92" + "02" + "CD012C",
            hex);
    }

    [Fact]
    public void RelationUpdateRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysRelationUpdate(
            Oid,
            "users",
            [(1UL, new byte[] { 0x01, 0x02, 0x03 })],
            [(2UL, new byte[] { 0x04, 0x05 })],
            [UniRelationDelta.Add(3, [0x06, 0x07])]));
        // delta [3, 0, bin 0607]: op 0 is UniRelationDeltaOp.Add.
        Assert.Equal(
            HeaderPrefix + "00000016" + "85" + "01" + OidHex + "02" + "A57573657273"
            + "03" + "91" + "92" + "01" + ValueHex
            + "04" + "91" + "92" + "02" + "C4020405"
            + "05" + "91" + "93" + "03" + "00" + "C4020607",
            hex);
    }

    [Fact]
    public void RelationInsertRequestFrameMatchesSnapshot()
    {
        var hex = CaptureFrame(() => MuduSysCallApi.SysRelationInsert(
            Oid,
            "users",
            [(1UL, new byte[] { 0x01, 0x02, 0x03 })],
            [(2UL, new byte[] { 0x04, 0x05 })]));
        Assert.Equal(
            HeaderPrefix + "00000017" + "84" + "01" + OidHex + "02" + "A57573657273"
            + "03" + "91" + "92" + "01" + ValueHex
            + "04" + "91" + "92" + "02" + "C4020405",
            hex);
    }

    [Fact]
    public void OpenOkResultFrameMatchesSnapshot()
    {
        var frame = SyscallPayload.EncodeResultFrame(MessageKind.OpenSession, Oid);
        Assert.Equal(HeaderPrefix + "00000004" + "92" + "00" + OidHex, Convert.ToHexString(frame));
    }

    [Fact]
    public void GetOkNilResultFrameMatchesSnapshot()
    {
        var frame = SyscallPayload.EncodeResultFrame<byte[]?>(MessageKind.Get, null);
        Assert.Equal(HeaderPrefix + "00000006" + "9200C0", Convert.ToHexString(frame));
    }

    [Fact]
    public void UnitOkResultFrameMatchesSnapshot()
    {
        var frame = SyscallPayload.EncodeUnitResultFrame(MessageKind.Put);
        Assert.Equal(HeaderPrefix + "00000007" + "920000", Convert.ToHexString(frame));
    }

    [Fact]
    public void ErrorResultFrameMatchesSnapshot()
    {
        var frame = SyscallPayload.EncodeResultErrorFrame(MessageKind.RelationInsert, ErrorFixture());
        // UniError {1: 50012, 2: "duplicate", 3: "test", 4: "", 5: [1, 2]}:
        // 50012 = 0xC35C encodes as uint16 0xCD 0xC35C; err_details is a u8
        // ARRAY, not bin (both quirks pinned by the corpus).
        Assert.Equal(
            HeaderPrefix + "00000017" + "92" + "01"
            + "85" + "01" + "CDC35C" + "02" + "A96475706C6963617465" + "03" + "A474657374" + "04" + "A0" + "05" + "92" + "0102",
            Convert.ToHexString(frame));
    }

    // ---- decode round-trips: ok and UniError arms for every new kind ----

    [Fact]
    public void BatchResultRoundTrips()
    {
        var okFrame = SyscallPayload.EncodeResultFrame(MessageKind.Batch, new UniCommandResult { AffectedRows = 7 });
        var ok = MuduSysCallApi.DeserializeBatchResult(okFrame);
        Assert.Equal(UniCommandReturnKind.Ok, ok.Kind());
        Assert.Equal(7UL, UniCommandReturnOk.AsOk(ok).Inner.AffectedRows);

        var err = MuduSysCallApi.DeserializeBatchResult(
            SyscallPayload.EncodeResultErrorFrame(MessageKind.Batch, ErrorFixture()));
        Assert.Equal(UniCommandReturnKind.Err, err.Kind());
        Assert.Equal(50012u, UniCommandReturnErr.AsErr(err).Inner.ErrCode);
    }

    [Fact]
    public void OpenResultRoundTrips()
    {
        var ok = SyscallPayload.DecodeResultFrame<UniOid>(
            MessageKind.OpenSession,
            SyscallPayload.EncodeResultFrame(MessageKind.OpenSession, Oid));
        Assert.True(ok.IsOk);
        Assert.Equal(Oid, ok.Value);

        var err = SyscallPayload.DecodeResultFrame<UniOid>(
            MessageKind.OpenSession,
            SyscallPayload.EncodeResultErrorFrame(MessageKind.OpenSession, ErrorFixture()));
        Assert.True(err.IsErr);
        Assert.Equal(50012u, err.Error.GetValueOrDefault().ErrCode);
    }

    [Fact]
    public void CloseResultRoundTrips()
    {
        Assert.Null(SyscallPayload.DecodeUnitResultFrame(
            MessageKind.CloseSession,
            SyscallPayload.EncodeUnitResultFrame(MessageKind.CloseSession)));

        var err = SyscallPayload.DecodeUnitResultFrame(
            MessageKind.CloseSession,
            SyscallPayload.EncodeResultErrorFrame(MessageKind.CloseSession, ErrorFixture()));
        Assert.NotNull(err);
        Assert.Equal("duplicate", err.GetValueOrDefault().ErrMsg);
    }

    [Fact]
    public void GetResultRoundTripsValueAndNil()
    {
        var okValue = SyscallPayload.DecodeResultFrame<byte[]>(
            MessageKind.Get,
            SyscallPayload.EncodeResultFrame<byte[]?>(MessageKind.Get, [0x2A]));
        Assert.True(okValue.IsOk);
        Assert.Equal([0x2A], okValue.Value);

        var okNil = SyscallPayload.DecodeResultFrame<byte[]>(
            MessageKind.Get,
            SyscallPayload.EncodeResultFrame<byte[]?>(MessageKind.Get, null));
        Assert.True(okNil.IsOk);
        Assert.Null(okNil.Value);

        var err = SyscallPayload.DecodeResultFrame<byte[]>(
            MessageKind.Get,
            SyscallPayload.EncodeResultErrorFrame(MessageKind.Get, ErrorFixture()));
        Assert.True(err.IsErr);
    }

    [Fact]
    public void PutAndDeleteUnitResultsRoundTrip()
    {
        foreach (var kind in new[] { MessageKind.Put, MessageKind.Delete })
        {
            Assert.Null(SyscallPayload.DecodeUnitResultFrame(kind, SyscallPayload.EncodeUnitResultFrame(kind)));
            var err = SyscallPayload.DecodeUnitResultFrame(
                kind,
                SyscallPayload.EncodeResultErrorFrame(kind, ErrorFixture()));
            Assert.NotNull(err);
            Assert.Equal(50012u, err.GetValueOrDefault().ErrCode);
        }
    }

    [Fact]
    public void RangeResultRoundTrips()
    {
        (byte[] Key, byte[] Value)[] items = [([0x61], [0x01]), ([0x62], [0x02])];
        var ok = SyscallPayload.DecodeResultFrame<(byte[] Key, byte[] Value)[]>(
            MessageKind.Range,
            SyscallPayload.EncodeResultFrame(MessageKind.Range, items));
        Assert.True(ok.IsOk);
        Assert.Equal(2, ok.Value!.Length);
        Assert.Equal([0x61], ok.Value[0].Key);
        Assert.Equal([0x02], ok.Value[1].Value);

        var err = SyscallPayload.DecodeResultFrame<(byte[] Key, byte[] Value)[]>(
            MessageKind.Range,
            SyscallPayload.EncodeResultErrorFrame(MessageKind.Range, ErrorFixture()));
        Assert.True(err.IsErr);
    }

    [Fact]
    public void RelationGetResultRoundTripsRowNilAndNullFields()
    {
        byte[]?[]? row = [new byte[] { 0x01 }, null, new byte[] { 0x02, 0x03 }];
        var ok = SyscallPayload.DecodeResultFrame<byte[]?[]>(
            MessageKind.RelationGet,
            SyscallPayload.EncodeResultFrame<byte[]?[]?>(MessageKind.RelationGet, row));
        Assert.True(ok.IsOk);
        Assert.Equal(3, ok.Value!.Length);
        Assert.Equal([0x01], ok.Value[0]);
        Assert.Null(ok.Value[1]);
        Assert.Equal([0x02, 0x03], ok.Value[2]);

        var okNil = SyscallPayload.DecodeResultFrame<byte[]?[]>(
            MessageKind.RelationGet,
            SyscallPayload.EncodeResultFrame<byte[]?[]?>(MessageKind.RelationGet, null));
        Assert.True(okNil.IsOk);
        Assert.Null(okNil.Value);

        var err = SyscallPayload.DecodeResultFrame<byte[]?[]>(
            MessageKind.RelationGet,
            SyscallPayload.EncodeResultErrorFrame(MessageKind.RelationGet, ErrorFixture()));
        Assert.True(err.IsErr);
    }

    [Fact]
    public void RelationUpdateResultRoundTrips()
    {
        var ok = SyscallPayload.DecodeResultFrame<ulong>(
            MessageKind.RelationUpdate,
            SyscallPayload.EncodeResultFrame(MessageKind.RelationUpdate, 1UL));
        Assert.True(ok.IsOk);
        Assert.Equal(1UL, ok.Value);

        var err = SyscallPayload.DecodeResultFrame<ulong>(
            MessageKind.RelationUpdate,
            SyscallPayload.EncodeResultErrorFrame(MessageKind.RelationUpdate, ErrorFixture()));
        Assert.True(err.IsErr);
    }

    [Fact]
    public void RelationInsertResultRoundTrips()
    {
        Assert.Null(SyscallPayload.DecodeUnitResultFrame(
            MessageKind.RelationInsert,
            SyscallPayload.EncodeUnitResultFrame(MessageKind.RelationInsert)));
        var err = SyscallPayload.DecodeUnitResultFrame(
            MessageKind.RelationInsert,
            SyscallPayload.EncodeResultErrorFrame(MessageKind.RelationInsert, ErrorFixture()));
        Assert.NotNull(err);
    }

    // ---- integrity rules ----

    [Fact]
    public void DecodeRejectsTrailingBytes()
    {
        var frame = SyscallPayload.EncodeResultFrame<byte[]?>(MessageKind.Get, [0x2A]);
        var bloated = new byte[frame.Length + 1];
        frame.CopyTo(bloated, 0);
        Assert.Throws<global::System.IO.InvalidDataException>(
            () => SyscallPayload.DecodeResultFrame<byte[]>(MessageKind.Get, bloated));
    }

    [Fact]
    public void DecodeRejectsMismatchedKind()
    {
        var frame = SyscallPayload.EncodeResultFrame<byte[]?>(MessageKind.Get, [0x2A]);
        Assert.Throws<global::System.IO.InvalidDataException>(
            () => SyscallPayload.DecodeResultFrame<byte[]>(MessageKind.Put, frame));
    }

    [Fact]
    public void DecodeRejectsUnknownResultTag()
    {
        // body [2, 0]: tag 2 is neither ok (0) nor err (1)
        var frame = SyscallPayload.EncodeFrame(MessageKind.Get, [0x92, 0x02, 0x00]);
        Assert.Throws<global::System.IO.InvalidDataException>(
            () => SyscallPayload.DecodeResultFrame<byte[]>(MessageKind.Get, frame));
    }

    private static UniError ErrorFixture()
    {
        return new UniError
        {
            ErrCode = 50012,
            ErrMsg = "duplicate",
            ErrSrc = "test",
            ErrLoc = string.Empty,
            ErrDetails = [1, 2],
        };
    }

    /// <summary>
    /// Runs one <c>Sys*</c> call against the mock backend and returns the hex
    /// of the exact request frame it emitted.
    /// </summary>
    private static string CaptureFrame(Action call)
    {
        MuduSysCallApi.UseMockBackend = true;
        var captured = new global::System.Collections.Generic.List<byte[]>();
        MockSqliteMuduSysCall.CaptureRequests = captured;
        try
        {
            call();
        }
        finally
        {
            MockSqliteMuduSysCall.CaptureRequests = null;
        }

        return Convert.ToHexString(Assert.Single(captured));
    }
}

[CollectionDefinition("MockBackend")]
public class MockBackendCollection;
