use std::collections::BTreeMap;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let repo_root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .parent()
        .unwrap()
        .to_path_buf();

    let root_manifest_path = repo_root.join("Cargo.toml");
    let root_manifest = fs::read_to_string(&root_manifest_path).expect("read workspace Cargo.toml");
    println!("cargo:rerun-if-changed={}", root_manifest_path.display());

    let workspace_versions = load_workspace_versions(&root_manifest);
    let sdk_root = repo_root.join("mudu_api").join("rust");
    let sdk_src_universal = sdk_root.join("src").join("universal");
    let sdk_wit_dir = sdk_root.join("wit");
    let demo_dir = sdk_root.join("demo");

    fs::create_dir_all(&sdk_src_universal).expect("create sdk universal dir");
    fs::create_dir_all(&sdk_wit_dir).expect("create sdk wit dir");
    fs::create_dir_all(demo_dir.join("src")).expect("create sdk demo src dir");

    let universal_src_root = repo_root.join("mudu_binding").join("src").join("universal");
    println!("cargo:rerun-if-changed={}", universal_src_root.display());
    let universal_files = collect_universal_files(&universal_src_root);
    for file in &universal_files {
        let source = universal_src_root.join(file);
        println!("cargo:rerun-if-changed={}", source.display());
        let target = sdk_src_universal.join(file);
        copy_file_if_changed(&source, &target);
    }
    remove_stale_files(&sdk_src_universal, &universal_files, Some("mod.rs"));

    let generated_mod = generate_universal_mod(&universal_files);
    write_if_changed(&sdk_src_universal.join("mod.rs"), &generated_mod);

    let wit_source = repo_root
        .join("sys_interface")
        .join("wit")
        .join("async")
        .join("async-api.wit");
    println!("cargo:rerun-if-changed={}", wit_source.display());
    copy_file_if_changed(&wit_source, &sdk_wit_dir.join("async-api.wit"));

    let sdk_manifest = generate_sdk_manifest(&workspace_versions);
    write_if_changed(&sdk_root.join("Cargo.toml"), &sdk_manifest);

    let demo_manifest = generate_demo_manifest(&workspace_versions);
    write_if_changed(&demo_dir.join("Cargo.toml"), &demo_manifest);
}

fn load_workspace_versions(root_manifest: &str) -> BTreeMap<String, String> {
    let manifest: toml::Value = toml::from_str(root_manifest).expect("parse workspace Cargo.toml");
    let deps = manifest["workspace"]["dependencies"]
        .as_table()
        .expect("workspace.dependencies table");

    let keys = [
        "rmp-serde",
        "serde",
        "serde_repr",
        "tokio",
        "wit-bindgen",
        "rusqlite",
    ];

    keys.into_iter()
        .map(|key| {
            let value = deps
                .get(key)
                .unwrap_or_else(|| panic!("missing workspace dep: {key}"));
            (
                key.to_string(),
                extract_version(value).unwrap_or_else(|| panic!("missing version for {key}")),
            )
        })
        .collect()
}

fn collect_universal_files(source_dir: &Path) -> Vec<String> {
    let mut files = fs::read_dir(source_dir)
        .unwrap_or_else(|err| panic!("read dir {}: {err}", source_dir.display()))
        .filter_map(|entry| {
            let entry = entry
                .unwrap_or_else(|err| panic!("read dir entry {}: {err}", source_dir.display()));
            let path = entry.path();
            let file_name = entry.file_name();
            let file_name = file_name.to_string_lossy().to_string();

            if !path.is_file()
                || path.extension() != Some(OsStr::new("rs"))
                || file_name == "mod.rs"
            {
                return None;
            }

            Some(file_name)
        })
        .collect::<Vec<_>>();
    files.sort();
    files
}

fn extract_version(value: &toml::Value) -> Option<String> {
    match value {
        toml::Value::String(version) => Some(version.clone()),
        toml::Value::Table(table) => table
            .get("version")
            .and_then(|value| value.as_str())
            .map(ToOwned::to_owned),
        _ => None,
    }
}

fn generate_universal_mod(universal_files: &[String]) -> String {
    let mut content = String::from("// Generated by mudu_api_sync. Do not edit manually.\n\n");
    for file in universal_files {
        let module = file.trim_end_matches(".rs");
        content.push_str(&format!("pub mod {module};\n"));
    }
    content
}

fn generate_sdk_manifest(versions: &BTreeMap<String, String>) -> String {
    format!(
        concat!(
            "# Generated by mudu_api_sync. Do not edit manually.\n",
            "[package]\n",
            "name = \"mudu_api_rust\"\n",
            "version = \"0.1.0\"\n",
            "edition = \"2024\"\n\n",
            "[workspace]\n",
            "members = [\"demo\"]\n\n",
            "[features]\n",
            "default = []\n",
            "mock-sqlite = [\"dep:rusqlite\"]\n",
            "wasm-async = []\n\n",
            "[dependencies]\n",
            "rmp-serde = \"{rmp_serde}\"\n",
            "serde = {{ version = \"{serde}\", features = [\"default\", \"derive\", \"serde_derive\"] }}\n",
            "serde_repr = \"{serde_repr}\"\n",
            "tokio = {{ version = \"{tokio}\", features = [\"full\"] }}\n",
            "wit-bindgen = \"{wit_bindgen}\"\n",
            "rusqlite = {{ version = \"{rusqlite}\", features = [\"bundled\"], optional = true }}\n",
        ),
        rmp_serde = versions["rmp-serde"],
        serde = versions["serde"],
        serde_repr = versions["serde_repr"],
        tokio = versions["tokio"],
        wit_bindgen = versions["wit-bindgen"],
        rusqlite = versions["rusqlite"],
    )
}

fn generate_demo_manifest(versions: &BTreeMap<String, String>) -> String {
    format!(
        concat!(
            "# Generated by mudu_api_sync. Do not edit manually.\n",
            "[package]\n",
            "name = \"mudu_api_rust_demo\"\n",
            "version = \"0.1.0\"\n",
            "edition = \"2024\"\n\n",
            "[dependencies]\n",
            "mudu_api_rust = {{ path = \"..\", features = [\"mock-sqlite\"] }}\n",
            "tokio = {{ version = \"{tokio}\", features = [\"full\"] }}\n",
        ),
        tokio = versions["tokio"],
    )
}

fn copy_file_if_changed(source: &Path, target: &Path) {
    let content =
        fs::read_to_string(source).unwrap_or_else(|err| panic!("read {}: {err}", source.display()));
    write_if_changed(target, &content);
}

fn remove_stale_files(target_dir: &Path, keep_files: &[String], generated_file: Option<&str>) {
    let mut keep = keep_files
        .iter()
        .cloned()
        .collect::<std::collections::BTreeSet<_>>();
    if let Some(generated_file) = generated_file {
        keep.insert(generated_file.to_string());
    }

    for entry in fs::read_dir(target_dir)
        .unwrap_or_else(|err| panic!("read dir {}: {err}", target_dir.display()))
    {
        let entry =
            entry.unwrap_or_else(|err| panic!("read dir entry {}: {err}", target_dir.display()));
        let path = entry.path();
        if !path.is_file() {
            continue;
        }

        let file_name = entry.file_name().to_string_lossy().to_string();
        if keep.contains(&file_name) {
            continue;
        }

        fs::remove_file(&path).unwrap_or_else(|err| panic!("remove {}: {err}", path.display()));
    }
}

fn write_if_changed(path: &Path, content: &str) {
    let needs_write = match fs::read_to_string(path) {
        Ok(existing) => existing != content,
        Err(_) => true,
    };

    if needs_write {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .unwrap_or_else(|err| panic!("create {}: {err}", parent.display()));
        }
        fs::write(path, content).unwrap_or_else(|err| panic!("write {}: {err}", path.display()));
    }
}
