#!/usr/bin/env python3
"""Patch the AssemblyScript core wasm exports to be component-model compatible.

`asc` emits, for each procedure `<p>` (snake_case), two canonical-ABI exports
generated by the mtp adapter template:

  - `mp2_<p>`           (byte-pipe procedure entry point)
  - `cabi_post_mp2_<p>` (canonical-ABI post-return)

`wasm-tools component new` looks these up under the kebab-case root-level
function names declared by the generated world WIT:

  - `mp2-<p-kebab>`
  - `cabi_post_mp2-<p-kebab>`

This script rewrites the export section of the core module, renaming the
`mp2_*` exports to those kebab-case names. Names change length, so the export
section is rebuilt and its size re-encoded (wasm sections are self-delimiting,
so splicing is safe). The name section is left untouched; it is purely
informational.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE_WASM = ROOT / "build" / "as" / "procedures.core.wasm"
PATCHED_WASM = ROOT / "build" / "as" / "procedures.core.patched.wasm"

MP2_PREFIX = b"mp2_"
POST_MP2_PREFIX = b"cabi_post_mp2_"
EXPORT_SECTION_ID = 7


def read_leb128(data: bytes, pos: int) -> tuple[int, int]:
    result = 0
    shift = 0
    while True:
        byte = data[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        shift += 7
        if not byte & 0x80:
            return result, pos


def write_leb128(value: int) -> bytes:
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            out.append(byte | 0x80)
        else:
            out.append(byte)
            return bytes(out)


def component_export_name(name: bytes) -> bytes:
    if name.startswith(POST_MP2_PREFIX):
        proc = name[len(POST_MP2_PREFIX):].replace(b"_", b"-")
        return b"cabi_post_mp2-" + proc
    if name.startswith(MP2_PREFIX):
        proc = name[len(MP2_PREFIX):].replace(b"_", b"-")
        return b"mp2-" + proc
    return name


def patch_wasm() -> None:
    data = CORE_WASM.read_bytes()
    if data[:4] != b"\0asm":
        raise RuntimeError(f"{CORE_WASM} is not a wasm binary")

    # Split the module into (section id, payload) pairs, keeping order.
    pos = 8
    sections: list[tuple[int, bytes]] = []
    while pos < len(data):
        section_id = data[pos]
        pos += 1
        size, pos = read_leb128(data, pos)
        sections.append((section_id, data[pos:pos + size]))
        pos += size

    renamed: list[tuple[bytes, bytes]] = []
    out = bytearray(data[:8])
    for section_id, payload in sections:
        if section_id == EXPORT_SECTION_ID:
            count, cursor = read_leb128(payload, 0)
            entries = []
            for _ in range(count):
                name_len, cursor = read_leb128(payload, cursor)
                name = payload[cursor:cursor + name_len]
                cursor += name_len
                kind = payload[cursor]
                index, cursor = read_leb128(payload, cursor + 1)
                entries.append((name, kind, index))

            rebuilt = bytearray(write_leb128(count))
            for name, kind, index in entries:
                new_name = component_export_name(name)
                if new_name != name:
                    renamed.append((name, new_name))
                rebuilt += write_leb128(len(new_name)) + new_name
                rebuilt += bytes([kind]) + write_leb128(index)
            payload = bytes(rebuilt)

        out += bytes([section_id]) + write_leb128(len(payload)) + payload

    if not renamed:
        raise RuntimeError(
            f"no {MP2_PREFIX.decode()}* exports found in {CORE_WASM}"
        )

    PATCHED_WASM.write_bytes(bytes(out))


if __name__ == "__main__":
    patch_wasm()
