use crate:universal:uni-scalar-value/uni-scalar-value;

interface universal {
variant uni-dat-value {
    scalar(uni-scalar-value),
    array(list<uni-dat-value>),
    record(list<uni-dat-value>),
    binary(list<u8>)
}
}