/*
 * Syscall layer for the wallet-c guest — see mudu_sys.h for the API
 * contract. Unlike the mpm-crate C template (which hand-rolls the MSSP
 * frame and the `uni` MessagePack shapes), every wire encode/decode here
 * goes through the formal C binding: `mududb/codec/mpack.{h,c}` for the
 * MessagePack runtime and the generated `mududb/types/Uni*.h` codecs for
 * the MSSP v1 frames, the SyscallPayload request/result bodies and the
 * procedure byte-pipe shapes. The binding sources are compiled straight
 * from `crates/sdk/bindings/c` (see Makefile.toml) — nothing is vendored.
 *
 * The procedure byte pipe (the `mp2-*` exports wired in the mtp-generated
 * procedures_gen.c) is NOT MSSP-framed: the host passes a bare MessagePack
 * `UniProcedureParam` (record-as-map) and expects the hand-written
 * `UniResult<UniProcedureResult, UniError>` shape back — a single-entry
 * map, key 0 for the ok value and key 1 for the error (see
 * `mudu_binding::universal::uni_result::UniResult` on the host).
 *
 * Ownership: the binding's decode arena and writer buffers allocate through
 * `mp_realloc` (mpack_alloc.c) -> `realloc`, which the freestanding runtime
 * below backs with the guest bump arena. Decoded values therefore live
 * until the guest call ends; nothing is individually freed (`free` is a
 * no-op), which matches the short-lived procedure-call model.
 */
#include "mudu_sys.h"

#include <stdbool.h>

#include "mududb/codec/mpack.h"
#include "mududb/types/UniDataValue.h"
#include "mududb/types/UniError.h"
#include "mududb/types/UniProcedureParam.h"
#include "mududb/types/UniProcedureResult.h"
#include "mududb/types/UniScalarValue.h"
#include "mududb/types/UniSyscall.h"

/* ---- minimal freestanding runtime ---- */

void *memcpy(void *dst, const void *src, size_t n) {
    uint8_t *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;
    size_t i;
    for (i = 0; i < n; i++) {
        d[i] = s[i];
    }
    return dst;
}

void *memmove(void *dst, const void *src, size_t n) {
    uint8_t *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;
    size_t i;
    if ((uintptr_t)d < (uintptr_t)s) {
        for (i = 0; i < n; i++) {
            d[i] = s[i];
        }
    } else {
        for (i = n; i > 0; i--) {
            d[i - 1] = s[i - 1];
        }
    }
    return dst;
}

void *memset(void *dst, int c, size_t n) {
    uint8_t *d = (uint8_t *)dst;
    size_t i;
    for (i = 0; i < n; i++) {
        d[i] = (uint8_t)c;
    }
    return dst;
}

int memcmp(const void *a, const void *b, size_t n) {
    const uint8_t *x = (const uint8_t *)a;
    const uint8_t *y = (const uint8_t *)b;
    size_t i;
    for (i = 0; i < n; i++) {
        if (x[i] != y[i]) {
            return (int)x[i] - (int)y[i];
        }
    }
    return 0;
}

size_t strlen(const char *s) {
    size_t n = 0;
    while (s[n]) {
        n++;
    }
    return n;
}

/* Bump allocator over linear memory, starting at the linker-provided
 * `__heap_base`; grows the memory on demand. */
extern uint8_t __heap_base;

static uint8_t *arena_cur;

void *mudu_arena_alloc(size_t size, size_t align) {
    uintptr_t p;
    size_t avail;
    if (!arena_cur) {
        arena_cur = &__heap_base;
    }
    if (align < 1) {
        align = 1;
    }
    p = ((uintptr_t)arena_cur + (align - 1)) & ~(uintptr_t)(align - 1);
    avail = __builtin_wasm_memory_size(0) * (size_t)65536 - (size_t)p;
    if (size > avail) {
        size_t pages = (size - avail + 65535) / 65536;
        if (__builtin_wasm_memory_grow(0, pages) == (size_t)-1) {
            return 0;
        }
    }
    arena_cur = (uint8_t *)(p + size);
    return (void *)p;
}

/*
 * Canonical-ABI realloc: the lift glue generated by `wasm-tools component
 * new` calls this to place incoming lists (procedure params, syscall
 * replies) in guest memory. `cabi_realloc` is the current export name;
 * `canonical_abi_realloc` is the pre-rename alias older toolchains look up.
 */
__attribute__((export_name("cabi_realloc"))) void *
cabi_realloc(void *old_ptr, size_t old_size, size_t align, size_t new_size) {
    void *p = mudu_arena_alloc(new_size, align);
    if (old_ptr && p) {
        memcpy(p, old_ptr, old_size < new_size ? old_size : new_size);
    }
    return p;
}

__attribute__((export_name("canonical_abi_realloc"))) void *
canonical_abi_realloc(void *old_ptr, size_t old_size, size_t align, size_t new_size) {
    return cabi_realloc(old_ptr, old_size, align, new_size);
}

/* `realloc`/`free` behind the binding's default `mp_realloc`
 * (mpack_alloc.c): every allocation carries a 16-byte header with its size
 * so `realloc` can copy the old payload; `free` is a no-op because the bump
 * arena is never partially released. The 16-byte header keeps payloads
 * 16-byte aligned, satisfying the strictest C alignment requirement. */
typedef struct {
    uint64_t size;
    uint64_t reserved;
} mudu_alloc_header;

void *realloc(void *old_ptr, size_t new_size) {
    mudu_alloc_header *header;
    if (new_size == 0) {
        return 0;
    }
    header = (mudu_alloc_header *)mudu_arena_alloc(sizeof(mudu_alloc_header) + new_size, 16);
    if (!header) {
        return 0;
    }
    header->size = new_size;
    header->reserved = 0;
    if (old_ptr) {
        const mudu_alloc_header *old_header = ((const mudu_alloc_header *)old_ptr) - 1;
        size_t n = old_header->size < new_size ? old_header->size : new_size;
        memcpy(header + 1, old_ptr, n);
    }
    return (void *)(header + 1);
}

void free(void *ptr) {
    (void)ptr;
}

/* ---- syscall imports ----
 *
 * Canonical-ABI lowering of `mududb:api/system` functions
 * (`func(list<u8>) -> list<u8>`): the request list travels as (ptr, len)
 * and the reply list is written by the lift glue into guest memory, with
 * its (ptr, len) pair stored at `retptr`. Only the functions this guest
 * uses are imported; the host provides the full interface. */
__attribute__((import_module("mududb:api/system"), import_name("query"))) void
mudu_host_query(const uint8_t *ptr, uint32_t len, uint8_t *retptr);

__attribute__((import_module("mududb:api/system"), import_name("command"))) void
mudu_host_command(const uint8_t *ptr, uint32_t len, uint8_t *retptr);

/* ---- small helpers ---- */

static uint32_t mudu_strlen(const char *s) {
    uint32_t n = 0;
    while (s[n]) {
        n++;
    }
    return n;
}

mudu_datum mudu_null(void) {
    mudu_datum d;
    d.kind = MUDU_DATUM_NULL;
    d.i64 = 0;
    d.f64 = 0;
    d.str = 0;
    d.str_len = 0;
    d.record = 0;
    return d;
}

mudu_datum mudu_i64(int64_t value) {
    mudu_datum d = mudu_null();
    d.kind = MUDU_DATUM_I64;
    d.i64 = value;
    return d;
}

mudu_datum mudu_f64(double value) {
    mudu_datum d = mudu_null();
    d.kind = MUDU_DATUM_F64;
    d.f64 = value;
    return d;
}

mudu_datum mudu_str(const char *data, uint32_t len) {
    mudu_datum d = mudu_null();
    d.kind = MUDU_DATUM_STR;
    d.str = data;
    d.str_len = len;
    return d;
}

mudu_datum mudu_record(const uni_data_value *value) {
    mudu_datum d = mudu_null();
    d.kind = MUDU_DATUM_RECORD;
    d.record = value;
    return d;
}

void mudu_error_set(mudu_error *err, uint32_t code, const char *msg) {
    err->code = code;
    err->msg = msg;
    err->msg_len = mudu_strlen(msg);
}

int mudu_error_is_set(const mudu_error *err) {
    return err->code != 0;
}

/* ---- datum <-> UniDataValue conversion ---- */

/* Wrap one datum as a `UniDataValue` for encoding. The scalar and value
 * structs are caller-provided; encoders only borrow them. A record datum
 * shallow-copies the envelope (its payload pointers are arena-owned). */
static void datum_to_uni(const mudu_datum *d, uni_scalar_value *scalar, uni_data_value *value) {
    switch (d->kind) {
    case MUDU_DATUM_I64:
        scalar->kind = UNI_SCALAR_VALUE_I64;
        scalar->as.i64 = d->i64;
        break;
    case MUDU_DATUM_F64:
        scalar->kind = UNI_SCALAR_VALUE_F64;
        scalar->as.f64 = d->f64;
        break;
    case MUDU_DATUM_STR:
        scalar->kind = UNI_SCALAR_VALUE_STRING;
        scalar->as.string = mp_str_from(d->str, d->str_len);
        break;
    case MUDU_DATUM_RECORD:
        if (d->record) {
            *value = *d->record;
            return;
        }
        scalar->kind = UNI_SCALAR_VALUE_NULL;
        scalar->as.i64 = 0;
        break;
    default:
        scalar->kind = UNI_SCALAR_VALUE_NULL;
        scalar->as.i64 = 0;
        break;
    }
    value->kind = UNI_DATA_VALUE_SCALAR;
    value->as.scalar = scalar;
}

/* Unwrap one decoded `UniDataValue` to a datum. Integer and boolean
 * scalars surface as `MUDU_DATUM_I64`, floats as `MUDU_DATUM_F64`, every
 * string-family scalar (Char/String/Numeric/Date/Time/Timestamp/
 * TimestampTz) as `MUDU_DATUM_STR`; the string slices borrow from the
 * binding's decode arena, which lives in the guest arena. -1 on a
 * non-scalar or unsupported arm. */
static int uni_to_datum(const uni_data_value *value, mudu_datum *out) {
    const uni_scalar_value *s;
    *out = mudu_null();
    if (value->kind != UNI_DATA_VALUE_SCALAR || value->as.scalar == 0) {
        return -1;
    }
    s = value->as.scalar;
    switch (s->kind) {
    case UNI_SCALAR_VALUE_BOOL:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.bool_;
        break;
    case UNI_SCALAR_VALUE_U8:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.u8;
        break;
    case UNI_SCALAR_VALUE_I8:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.i8;
        break;
    case UNI_SCALAR_VALUE_U16:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.u16;
        break;
    case UNI_SCALAR_VALUE_I16:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.i16;
        break;
    case UNI_SCALAR_VALUE_U32:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.u32;
        break;
    case UNI_SCALAR_VALUE_I32:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.i32;
        break;
    case UNI_SCALAR_VALUE_U64:
        out->kind = MUDU_DATUM_I64;
        out->i64 = (int64_t)s->as.u64;
        break;
    case UNI_SCALAR_VALUE_I64:
        out->kind = MUDU_DATUM_I64;
        out->i64 = s->as.i64;
        break;
    case UNI_SCALAR_VALUE_F32:
        out->kind = MUDU_DATUM_F64;
        out->f64 = s->as.f32;
        break;
    case UNI_SCALAR_VALUE_F64:
        out->kind = MUDU_DATUM_F64;
        out->f64 = s->as.f64;
        break;
    case UNI_SCALAR_VALUE_CHAR:
        out->kind = MUDU_DATUM_STR;
        out->str = &s->as.char_;
        out->str_len = 1;
        break;
    case UNI_SCALAR_VALUE_STRING:
        out->kind = MUDU_DATUM_STR;
        out->str = s->as.string.data;
        out->str_len = s->as.string.len;
        break;
    case UNI_SCALAR_VALUE_NUMERIC:
        out->kind = MUDU_DATUM_STR;
        out->str = s->as.numeric.data;
        out->str_len = s->as.numeric.len;
        break;
    case UNI_SCALAR_VALUE_DATE:
        out->kind = MUDU_DATUM_STR;
        out->str = s->as.date.data;
        out->str_len = s->as.date.len;
        break;
    case UNI_SCALAR_VALUE_TIME:
        out->kind = MUDU_DATUM_STR;
        out->str = s->as.time.data;
        out->str_len = s->as.time.len;
        break;
    case UNI_SCALAR_VALUE_TIMESTAMP:
        out->kind = MUDU_DATUM_STR;
        out->str = s->as.timestamp.data;
        out->str_len = s->as.timestamp.len;
        break;
    case UNI_SCALAR_VALUE_TIMESTAMP_TZ:
        out->kind = MUDU_DATUM_STR;
        out->str = s->as.timestamp_tz.data;
        out->str_len = s->as.timestamp_tz.len;
        break;
    case UNI_SCALAR_VALUE_NULL:
        out->kind = MUDU_DATUM_NULL;
        break;
    default: /* U128/I128/Blob: unsupported */
        return -1;
    }
    return 0;
}

/* Copy a decoded host `UniError` into `err`; the message slice is copied
 * into the guest arena so it stays valid after the decode arena is gone. */
static void host_error_to_mudu(const uni_error *host, mudu_error *err) {
    char *msg;
    if (host->err_msg.len == 0) {
        err->code = host->err_code;
        err->msg = "";
        err->msg_len = 0;
        return;
    }
    msg = (char *)mudu_arena_alloc(host->err_msg.len, 1);
    if (!msg) {
        mudu_error_set(err, MUDU_EC_INTERNAL, "out of memory");
        return;
    }
    memcpy(msg, host->err_msg.data, host->err_msg.len);
    err->code = host->err_code;
    err->msg = msg;
    err->msg_len = host->err_msg.len;
}

/* Build the `uni_sql_param` argument array of a query/command request:
 * one `UniDataValue::Scalar` per datum, borrowed by the encoder. */
static int build_sql_params(const mudu_datum *args, uint32_t n_args, uni_sql_param *out) {
    uni_data_value *values;
    uni_scalar_value *scalars;
    uint32_t i;
    memset(out, 0, sizeof(*out));
    out->param_names_is_null = true;
    if (n_args == 0) {
        return 0;
    }
    values = (uni_data_value *)mudu_arena_alloc((size_t)n_args * sizeof(uni_data_value), 8);
    scalars = (uni_scalar_value *)mudu_arena_alloc((size_t)n_args * sizeof(uni_scalar_value), 8);
    if (!values || !scalars) {
        return -1;
    }
    for (i = 0; i < n_args; i++) {
        datum_to_uni(&args[i], &scalars[i], &values[i]);
    }
    out->params.items = values;
    out->params.len = n_args;
    return 0;
}

/* ---- SQL entry points ---- */

int mudu_query(mudu_oid session, const char *sql, const mudu_datum *args, uint32_t n_args,
               mudu_rows *out, mudu_error *err) {
    uni_query_argv argv;
    mp_writer w;
    mp_reader r;
    mp_arena a;
    uni_syscall_query_result res;
    uint8_t ret_area[8];
    const uint8_t *frame;
    uint32_t frame_len;
    uint32_t i;

    out->n_rows = 0;
    out->rows = 0;
    memset(&argv, 0, sizeof(argv));
    argv.oid = session;
    argv.query.sql_string = mp_str_from_cstr(sql);
    argv.param_desc_is_null = true;
    if (build_sql_params(args, n_args, &argv.param_list) != 0) {
        mudu_error_set(err, MUDU_EC_INTERNAL, "out of memory");
        return -1;
    }
    mpw_init(&w);
    if (uni_syscall_query_request_encode(&w, &argv) != 0) {
        mudu_error_set(err, MUDU_EC_INTERNAL, "MSSP: encode query request failed");
        return -1;
    }
    mudu_host_query(w.buf, (uint32_t)w.len, ret_area);
    mpw_free(&w);
    memcpy(&frame, ret_area, 4);
    memcpy(&frame_len, ret_area + 4, 4);

    mpr_init(&r, frame, frame_len);
    mpa_init(&a);
    if (uni_syscall_query_result_decode(&r, &a, &res) != 0) {
        mudu_error_set(err, MUDU_EC_INTERNAL, "MSSP: malformed query result");
        return -1;
    }
    if (res.is_err) {
        host_error_to_mudu(&res.err, err);
        return -1;
    }
    out->n_rows = res.value.result_set.row_set.len;
    if (out->n_rows) {
        out->rows = (mudu_row *)mudu_arena_alloc((size_t)out->n_rows * sizeof(mudu_row), 8);
        if (!out->rows) {
            mudu_error_set(err, MUDU_EC_INTERNAL, "out of memory");
            return -1;
        }
        for (i = 0; i < out->n_rows; i++) {
            const uni_tuple_row *row = &res.value.result_set.row_set.items[i];
            uint32_t f;
            out->rows[i].n_fields = row->fields.len;
            out->rows[i].fields = 0;
            if (row->fields.len) {
                out->rows[i].fields =
                    (mudu_datum *)mudu_arena_alloc((size_t)row->fields.len * sizeof(mudu_datum), 8);
                if (!out->rows[i].fields) {
                    mudu_error_set(err, MUDU_EC_INTERNAL, "out of memory");
                    return -1;
                }
            }
            for (f = 0; f < row->fields.len; f++) {
                if (uni_to_datum(&row->fields.items[f], &out->rows[i].fields[f]) != 0) {
                    mudu_error_set(err, MUDU_EC_INTERNAL, "MSSP: unsupported query result cell");
                    return -1;
                }
            }
        }
    }
    return 0;
}

int mudu_command(mudu_oid session, const char *sql, const mudu_datum *args, uint32_t n_args,
                 uint64_t *affected, mudu_error *err) {
    uni_command_argv argv;
    mp_writer w;
    mp_reader r;
    mp_arena a;
    uni_syscall_command_result res;
    uint8_t ret_area[8];
    const uint8_t *frame;
    uint32_t frame_len;

    *affected = 0;
    memset(&argv, 0, sizeof(argv));
    argv.oid = session;
    argv.command.sql_string = mp_str_from_cstr(sql);
    argv.param_desc_is_null = true;
    if (build_sql_params(args, n_args, &argv.param_list) != 0) {
        mudu_error_set(err, MUDU_EC_INTERNAL, "out of memory");
        return -1;
    }
    mpw_init(&w);
    if (uni_syscall_command_request_encode(&w, &argv) != 0) {
        mudu_error_set(err, MUDU_EC_INTERNAL, "MSSP: encode command request failed");
        return -1;
    }
    mudu_host_command(w.buf, (uint32_t)w.len, ret_area);
    mpw_free(&w);
    memcpy(&frame, ret_area, 4);
    memcpy(&frame_len, ret_area + 4, 4);

    mpr_init(&r, frame, frame_len);
    mpa_init(&a);
    if (uni_syscall_command_result_decode(&r, &a, &res) != 0) {
        mudu_error_set(err, MUDU_EC_INTERNAL, "MSSP: malformed command result");
        return -1;
    }
    if (res.is_err) {
        host_error_to_mudu(&res.err, err);
        return -1;
    }
    *affected = res.value.affected_rows;
    return 0;
}

/* ---- procedure byte-pipe codec (`handle_procedure`) ---- */

/* Decode the bare-MessagePack `UniProcedureParam` the host passes to the
 * `mp2-*` exports; scalar parameters are unwrapped to datums, and a
 * record-case parameter passes through as a `MUDU_DATUM_RECORD` datum
 * holding the decoded envelope (it lives in the binding's decode arena,
 * which is backed by the guest arena and stays valid until the call ends). */
static int decode_proc_param(const uint8_t *data, size_t len, mudu_proc_param *out) {
    mp_reader r;
    mp_arena a;
    uni_procedure_param decoded;
    uint32_t i;
    mpr_init(&r, data, len);
    mpa_init(&a);
    if (uni_procedure_param_decode(&r, &a, &decoded) != 0 || !mpr_done(&r)) {
        return -1;
    }
    out->procedure = decoded.procedure;
    out->session = decoded.session;
    out->n_params = decoded.param_list.len;
    out->params = 0;
    if (out->n_params) {
        out->params = (mudu_datum *)mudu_arena_alloc((size_t)out->n_params * sizeof(mudu_datum), 8);
        if (!out->params) {
            return -1;
        }
        for (i = 0; i < out->n_params; i++) {
            const uni_data_value *value = &decoded.param_list.items[i];
            if (value->kind == UNI_DATA_VALUE_RECORD) {
                out->params[i] = mudu_record(value);
            } else if (uni_to_datum(value, &out->params[i]) != 0) {
                return -1;
            }
        }
    }
    return 0;
}

/* Ok arm of `UniResult<UniProcedureResult, UniError>`: the single-entry map
 * `{0: {1: [return_list]}}`, mirroring the hand-written serde impl of
 * `mudu_binding::universal::uni_result::UniResult` with the record-as-map
 * `UniProcedureResult` payload. */
static void encode_proc_ok(mp_writer *w, const mudu_datum *result) {
    uni_scalar_value scalar;
    uni_data_value value;
    uni_procedure_result proc_result;
    datum_to_uni(result, &scalar, &value);
    memset(&proc_result, 0, sizeof(proc_result));
    proc_result.return_list.items = &value;
    proc_result.return_list.len = 1;
    mpw_map_header(w, 1);
    mpw_u64(w, 0);
    uni_procedure_result_encode(w, &proc_result);
}

/* Err arm: `{1: UniError}`. */
static void encode_proc_err(mp_writer *w, uint32_t code, const char *msg, uint32_t msg_len) {
    uni_error error;
    if (!msg) {
        msg = "";
        msg_len = 0;
    }
    memset(&error, 0, sizeof(error));
    error.err_code = code;
    error.err_msg = mp_str_from(msg, msg_len);
    error.err_src = mp_str_from("wallet-c", (uint32_t)(sizeof("wallet-c") - 1));
    error.err_loc = mp_str_from("", 0);
    error.err_details = mp_bin_from(0, 0);
    mpw_map_header(w, 1);
    mpw_u64(w, 1);
    uni_error_encode(w, &error);
}

uint32_t mudu_run_proc(const uint8_t *param_ptr, uint32_t param_len, mudu_proc_fn fn) {
    static uint32_t ret_area[2]; /* the lift glue reads the reply (ptr, len) here */
    mp_writer w;
    mudu_proc_param param;
    mudu_error err;
    mudu_datum result;
    err.code = 0;
    err.msg = 0;
    err.msg_len = 0;
    result = mudu_null();
    mpw_init(&w);
    if (decode_proc_param(param_ptr, param_len, &param) != 0) {
        encode_proc_err(&w, MUDU_EC_INVALID_ARGUMENT, "decode procedure param failed",
                        (uint32_t)(sizeof("decode procedure param failed") - 1));
    } else if (fn(&param, &result, &err) != 0) {
        if (!mudu_error_is_set(&err)) {
            mudu_error_set(&err, MUDU_EC_INTERNAL, "procedure failed");
        }
        encode_proc_err(&w, err.code, err.msg, err.msg_len);
    } else {
        encode_proc_ok(&w, &result);
    }
    if (!mpw_ok(&w)) {
        ret_area[0] = 0;
        ret_area[1] = 0;
    } else {
        ret_area[0] = (uint32_t)(uintptr_t)w.buf;
        ret_area[1] = (uint32_t)w.len;
    }
    return (uint32_t)(uintptr_t)ret_area;
}
