//! Backwards-compatible module path for the query return type.
//!
//! The canonical definition is generated by `mudu_gen` into
//! [`crate::universal::uni_query_result`] (from `uni-query-result.wit`, which
//! declares both `uni-query-result` and `uni-query-return`). This shim keeps
//! the pre-existing `universal::uni_query_return` import path
//! source-compatible.

pub use crate::universal::uni_query_result::UniQueryReturn;

#[cfg(test)]
mod tests {
    use super::UniQueryReturn;
    use crate::universal::mp_wire::{FromValue, ToValue, Value, decode_value, encode_value};
    use crate::universal::uni_error::UniError;
    use crate::universal::uni_query_result::UniQueryResult;

    fn value_roundtrip(value: &UniQueryReturn) -> UniQueryReturn {
        let bytes = encode_value(&value.to_value());
        UniQueryReturn::from_value(&decode_value(&bytes).unwrap()).unwrap()
    }

    #[test]
    fn ok_roundtrip() {
        let value = UniQueryReturn::from_ok(UniQueryResult {
            tuple_desc: Default::default(),
            result_set: Default::default(),
        });
        let decoded = value_roundtrip(&value);
        assert!(decoded.as_ok().is_some());
    }

    #[test]
    fn err_roundtrip() {
        let value = UniQueryReturn::from_err(UniError {
            err_code: 9,
            err_msg: "bad fd".to_string(),
            ..Default::default()
        });
        let decoded = value_roundtrip(&value);
        let err = decoded.expect_err();
        assert_eq!(err.err_code, 9);
        assert_eq!(err.err_msg, "bad fd");
    }

    #[test]
    fn rejects_unknown_tag() {
        // [7, 0] — unknown variant tag.
        let bytes = vec![0x92, 0x07, 0x00];
        assert!(UniQueryReturn::from_value(&decode_value(&bytes).unwrap()).is_err());
        let _ = Value::Nil;
    }

    #[test]
    fn accessors_return_none_for_wrong_variant() {
        let ok = UniQueryReturn::default();
        assert!(ok.as_err().is_none());
        let err = UniQueryReturn::from_err(UniError::default());
        assert!(err.as_ok().is_none());
    }
}
