// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
use crate::universal::uni_oid::UniOid;
#[derive(Debug, Clone)]
pub struct UniFsOpenArgv {
    pub session: UniOid,
    pub oid: UniOid,
    pub path: String,
    pub flags: u32,
}
impl Default for UniFsOpenArgv {
    fn default() -> Self {
        Self {
            session: Default::default(),
            oid: Default::default(),
            path: Default::default(),
            flags: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniFsOpenArgv {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.session).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                (&self.oid).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(3u32),
                (&self.path).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(4u32),
                (&self.flags).to_value(),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniFsOpenArgv {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut session = None;
        let mut oid = None;
        let mut path = None;
        let mut flags = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => session = Some(UniOid::from_value(val)?),
                2 => oid = Some(UniOid::from_value(val)?),
                3 => path = Some(String::from_value(val)?),
                4 => flags = Some(u32::from_value(val)?),
                _ => {}
            }
        }
        Ok(Self {
            session: session.unwrap_or_default(),
            oid: oid.unwrap_or_default(),
            path: path.unwrap_or_default(),
            flags: flags.unwrap_or_default(),
        })
    }
}
