// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
#[derive(Debug, Clone)]
pub struct UniOid {
    pub h: u64,
    pub l: u64,
}
impl Default for UniOid {
    fn default() -> Self {
        Self {
            h: Default::default(),
            l: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniOid {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.h).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                (&self.l).to_value(),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniOid {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut h = None;
        let mut l = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => h = Some(u64::from_value(val)?),
                2 => l = Some(u64::from_value(val)?),
                _ => {}
            }
        }
        Ok(Self {
            h: h.unwrap_or_default(),
            l: l.unwrap_or_default(),
        })
    }
}
