// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
use crate::universal::uni_oid::UniOid;
#[derive(Debug, Clone)]
pub struct UniFsStat {
    pub oid: UniOid,
    pub generation: u64,
    pub entry: String,
    pub length: u64,
    pub state: u32,
}
impl Default for UniFsStat {
    fn default() -> Self {
        Self {
            oid: Default::default(),
            generation: Default::default(),
            entry: Default::default(),
            length: Default::default(),
            state: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniFsStat {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.oid).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                (&self.generation).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(3u32),
                (&self.entry).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(4u32),
                (&self.length).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(5u32),
                (&self.state).to_value(),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniFsStat {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut oid = None;
        let mut generation = None;
        let mut entry = None;
        let mut length = None;
        let mut state = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => oid = Some(UniOid::from_value(val)?),
                2 => generation = Some(u64::from_value(val)?),
                3 => entry = Some(String::from_value(val)?),
                4 => length = Some(u64::from_value(val)?),
                5 => state = Some(u32::from_value(val)?),
                _ => {}
            }
        }
        Ok(Self {
            oid: oid.unwrap_or_default(),
            generation: generation.unwrap_or_default(),
            entry: entry.unwrap_or_default(),
            length: length.unwrap_or_default(),
            state: state.unwrap_or_default(),
        })
    }
}
