// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
use crate::universal::uni_scalar_value::UniScalarValue;
#[derive(Debug, Clone)]
pub enum UniDataValue {
    Scalar(UniScalarValue),
    Array(Vec<UniDataValue>),
    Record(Vec<UniDataValueField>),
    Binary(Vec<u8>),
}
impl Default for UniDataValue {
    fn default() -> Self {
        Self::Scalar(Default::default())
    }
}
impl UniDataValue {
    pub fn from_scalar(inner: UniScalarValue) -> Self {
        Self::Scalar(inner)
    }
    pub fn as_scalar(&self) -> Option<&UniScalarValue> {
        match self {
            Self::Scalar(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_scalar(&self) -> &UniScalarValue {
        match self {
            Self::Scalar(inner) => inner,
            _ => panic!("UniDataValue::expect_scalar called on the wrong variant"),
        }
    }
    pub fn from_array(inner: Vec<UniDataValue>) -> Self {
        Self::Array(inner)
    }
    pub fn as_array(&self) -> Option<&Vec<UniDataValue>> {
        match self {
            Self::Array(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_array(&self) -> &Vec<UniDataValue> {
        match self {
            Self::Array(inner) => inner,
            _ => panic!("UniDataValue::expect_array called on the wrong variant"),
        }
    }
    pub fn from_record(inner: Vec<UniDataValueField>) -> Self {
        Self::Record(inner)
    }
    pub fn as_record(&self) -> Option<&Vec<UniDataValueField>> {
        match self {
            Self::Record(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_record(&self) -> &Vec<UniDataValueField> {
        match self {
            Self::Record(inner) => inner,
            _ => panic!("UniDataValue::expect_record called on the wrong variant"),
        }
    }
    pub fn from_binary(inner: Vec<u8>) -> Self {
        Self::Binary(inner)
    }
    pub fn as_binary(&self) -> Option<&Vec<u8>> {
        match self {
            Self::Binary(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_binary(&self) -> &Vec<u8> {
        match self {
            Self::Binary(inner) => inner,
            _ => panic!("UniDataValue::expect_binary called on the wrong variant"),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniDataValue {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        match self {
            UniDataValue::Scalar(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(0u32),
                (inner).to_value(),
            ]),
            UniDataValue::Array(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(1u32),
                to_array(inner, |item| (item).to_value()),
            ]),
            UniDataValue::Record(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(2u32),
                to_array(inner, |item| (item).to_value()),
            ]),
            UniDataValue::Binary(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(3u32),
                (inner).to_value(),
            ]),
        }
    }
}
impl crate::universal::mp_wire::FromValue for UniDataValue {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let items = value.as_array()?;
        if items.len() != 2 {
            return Err(crate::universal::mp_wire::WireError::new(format!(
                "a {} value must be a 2-element [tag, payload] array, found {} elements",
                "UniDataValue",
                items.len()
            )));
        }
        let tag = u32::from_value(&items[0])?;
        match tag {
            0 => Ok(Self::Scalar(UniScalarValue::from_value(&items[1])?)),
            1 => Ok(Self::Array(from_array(&items[1], |item| {
                UniDataValue::from_value(item)
            })?)),
            2 => Ok(Self::Record(from_array(&items[1], |item| {
                UniDataValueField::from_value(item)
            })?)),
            3 => Ok(Self::Binary((&items[1]).as_bin()?)),
            _ => Err(crate::universal::mp_wire::WireError::new(format!(
                "unknown UniDataValue tag {tag}"
            ))),
        }
    }
}
#[derive(Debug, Clone)]
pub struct UniDataValueField {
    pub field_name: String,
    pub field_value: UniDataValue,
}
impl Default for UniDataValueField {
    fn default() -> Self {
        Self {
            field_name: Default::default(),
            field_value: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniDataValueField {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.field_name).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                (&self.field_value).to_value(),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniDataValueField {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut field_name = None;
        let mut field_value = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => field_name = Some(String::from_value(val)?),
                2 => field_value = Some(UniDataValue::from_value(val)?),
                _ => {}
            }
        }
        Ok(Self {
            field_name: field_name.unwrap_or_default(),
            field_value: field_value.unwrap_or_default(),
        })
    }
}
