// Generated by mudu_gen. Do not edit manually.
package types

import (
	"fmt"
)

// UniDataType is a sealed union: one struct per case, discriminated by
// UniDataTypeKind. Codec functions take/return the interface and
// discriminate with a type switch.
type UniDataType interface {
	uniDataTypeKind() UniDataTypeKind
}

// UniDataTypeKind identifies the case of a UniDataType value.
type UniDataTypeKind uint32

const (
	UniDataTypeKindScalar     UniDataTypeKind = 0
	UniDataTypeKindArray      UniDataTypeKind = 1
	UniDataTypeKindRecord     UniDataTypeKind = 2
	UniDataTypeKindOption     UniDataTypeKind = 3
	UniDataTypeKindTuple      UniDataTypeKind = 4
	UniDataTypeKindResult     UniDataTypeKind = 5
	UniDataTypeKindIdentifier UniDataTypeKind = 6
	UniDataTypeKindBinary     UniDataTypeKind = 7
	UniDataTypeKindBox        UniDataTypeKind = 8
)

// defaultUniDataType returns the proto3-style default of a missing
// UniDataType-typed field: the first declared case with its zero
// payload.
func defaultUniDataType() UniDataType {
	return UniDataTypeScalar{}
}

type UniDataTypeScalar struct {
	Inner UniScalar
}

// UniDataTypeScalar implements UniDataType.
func (UniDataTypeScalar) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindScalar
}

type UniDataTypeArray struct {
	Inner UniDataType
}

// UniDataTypeArray implements UniDataType.
func (UniDataTypeArray) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindArray
}

type UniDataTypeRecord struct {
	Inner UniRecordType
}

// UniDataTypeRecord implements UniDataType.
func (UniDataTypeRecord) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindRecord
}

type UniDataTypeOption struct {
	Inner UniDataType
}

// UniDataTypeOption implements UniDataType.
func (UniDataTypeOption) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindOption
}

type UniDataTypeTuple struct {
	Inner []UniDataType
}

// UniDataTypeTuple implements UniDataType.
func (UniDataTypeTuple) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindTuple
}

type UniDataTypeResult struct {
	Inner UniResultType
}

// UniDataTypeResult implements UniDataType.
func (UniDataTypeResult) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindResult
}

type UniDataTypeIdentifier struct {
	Inner string
}

// UniDataTypeIdentifier implements UniDataType.
func (UniDataTypeIdentifier) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindIdentifier
}

type UniDataTypeBinary struct{}

// UniDataTypeBinary implements UniDataType.
func (UniDataTypeBinary) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindBinary
}

type UniDataTypeBox struct {
	Inner UniDataType
}

// UniDataTypeBox implements UniDataType.
func (UniDataTypeBox) uniDataTypeKind() UniDataTypeKind {
	return UniDataTypeKindBox
}

// UniDataTypeToValue converts x to its MSSP wire value: the fixed
// [tag, payload] 2-element array; payload-less cases carry a 0u8 placeholder
// (NOT nil), matching the Rust host's variant serde.
func UniDataTypeToValue(x UniDataType) (any, error) {
	switch _x := x.(type) {
	case UniDataTypeScalar:
		var _p any
		_c0, err := UniScalarToValue(_x.Inner)
		if err != nil {
			return nil, err
		}
		_p = _c0
		return []any{uint64(0), _p}, nil
	case UniDataTypeArray:
		var _p any
		_c1, err := UniDataTypeToValue(_x.Inner)
		if err != nil {
			return nil, err
		}
		_p = _c1
		return []any{uint64(1), _p}, nil
	case UniDataTypeRecord:
		var _p any
		_c2, err := UniRecordTypeToValue(_x.Inner)
		if err != nil {
			return nil, err
		}
		_p = _c2
		return []any{uint64(2), _p}, nil
	case UniDataTypeOption:
		var _p any
		_c3, err := UniDataTypeToValue(_x.Inner)
		if err != nil {
			return nil, err
		}
		_p = _c3
		return []any{uint64(3), _p}, nil
	case UniDataTypeTuple:
		var _p any
		_v4 := make([]any, len(_x.Inner))
		for _i4, _e4 := range _x.Inner {
			_c5, err := UniDataTypeToValue(_e4)
			if err != nil {
				return nil, err
			}
			_v4[_i4] = _c5
		}
		_p = _v4
		return []any{uint64(4), _p}, nil
	case UniDataTypeResult:
		var _p any
		_c6, err := UniResultTypeToValue(_x.Inner)
		if err != nil {
			return nil, err
		}
		_p = _c6
		return []any{uint64(5), _p}, nil
	case UniDataTypeIdentifier:
		var _p any
		_p = _x.Inner
		return []any{uint64(6), _p}, nil
	case UniDataTypeBinary:
		return []any{uint64(7), uint8(0)}, nil
	case UniDataTypeBox:
		var _p any
		_c7, err := UniDataTypeToValue(_x.Inner)
		if err != nil {
			return nil, err
		}
		_p = _c7
		return []any{uint64(8), _p}, nil
	default:
		return nil, fmt.Errorf("unknown UniDataType kind %T", x)
	}
}

// UniDataTypeFromValue converts a wire value back to UniDataType; unknown tags are rejected.
func UniDataTypeFromValue(v any) (UniDataType, error) {
	_s, err := expectSeq(v, 2)
	if err != nil {
		return nil, err
	}
	_tag, err := u64Checked(_s[0])
	if err != nil {
		return nil, err
	}
	switch _tag {
	case 0:
		var _p UniScalar
		_p, err = UniScalarFromValue(_s[1])
		if err != nil {
			return nil, err
		}
		return UniDataTypeScalar{Inner: _p}, nil
	case 1:
		var _p UniDataType
		_p, err = UniDataTypeFromValue(_s[1])
		if err != nil {
			return nil, err
		}
		return UniDataTypeArray{Inner: _p}, nil
	case 2:
		var _p UniRecordType
		_p, err = UniRecordTypeFromValue(_s[1])
		if err != nil {
			return nil, err
		}
		return UniDataTypeRecord{Inner: _p}, nil
	case 3:
		var _p UniDataType
		_p, err = UniDataTypeFromValue(_s[1])
		if err != nil {
			return nil, err
		}
		return UniDataTypeOption{Inner: _p}, nil
	case 4:
		var _p []UniDataType
		_l0, err := expectList(_s[1])
		if err != nil {
			return nil, err
		}
		_v0 := make([]UniDataType, len(_l0))
		for _i0, _e0 := range _l0 {
			_v0[_i0], err = UniDataTypeFromValue(_e0)
			if err != nil {
				return nil, err
			}
		}
		_p = _v0
		return UniDataTypeTuple{Inner: _p}, nil
	case 5:
		var _p UniResultType
		_p, err = UniResultTypeFromValue(_s[1])
		if err != nil {
			return nil, err
		}
		return UniDataTypeResult{Inner: _p}, nil
	case 6:
		var _p string
		_p, err = strChecked(_s[1])
		if err != nil {
			return nil, err
		}
		return UniDataTypeIdentifier{Inner: _p}, nil
	case 7:
		// the payload placeholder is not inspected
		return UniDataTypeBinary{}, nil
	case 8:
		var _p UniDataType
		_p, err = UniDataTypeFromValue(_s[1])
		if err != nil {
			return nil, err
		}
		return UniDataTypeBox{Inner: _p}, nil
	default:
		return nil, fmt.Errorf("unknown UniDataType tag %d", _tag)
	}
}
