// Generated by mudu_gen. Do not edit manually.
package types

type UniError struct {
	ErrCode    uint32
	ErrMsg     string
	ErrSrc     string
	ErrLoc     string
	ErrDetails []byte
}

// UniErrorToValue converts x to its MSSP wire value: the
// integer-keyed MessagePack map of the 1-based field numbers (WIT
// declaration order). Option fields are omitted when nil (proto3 presence
// semantics); []byte fields encode as arrays of u8 (the record-context form
// of list<u8>), NOT as MessagePack bin.
func UniErrorToValue(x UniError) (any, error) {
	_d := map[uint64]any{}
	_d[1] = x.ErrCode
	_d[2] = x.ErrMsg
	_d[3] = x.ErrSrc
	_d[4] = x.ErrLoc
	_d[5] = blobToArrayValue(x.ErrDetails)
	return _d, nil
}

// UniErrorFromValue converts a wire value back to UniError.
// Decode is lenient: non-integer map keys are skipped, unknown field numbers
// are ignored and missing fields keep their proto3-style default.
func UniErrorFromValue(v any) (UniError, error) {
	var x UniError
	_m, err := expectMap(v)
	if err != nil {
		return x, err
	}
	for _k, _val := range _m {
		_key, _ok := mapKeyUint(_k)
		if !_ok {
			continue
		}
		switch _key {
		case 1:
			x.ErrCode, err = u32Checked(_val)
			if err != nil {
				return x, err
			}
		case 2:
			x.ErrMsg, err = strChecked(_val)
			if err != nil {
				return x, err
			}
		case 3:
			x.ErrSrc, err = strChecked(_val)
			if err != nil {
				return x, err
			}
		case 4:
			x.ErrLoc, err = strChecked(_val)
			if err != nil {
				return x, err
			}
		case 5:
			x.ErrDetails, err = blobFromValue(_val)
			if err != nil {
				return x, err
			}
		}
	}
	return x, nil
}
