// Generated by mudu_gen. Do not edit manually.
package types

type UniFsDirent struct {
	Name   string
	IsDir  bool
	Length uint64
}

// UniFsDirentToValue converts x to its MSSP wire value: the
// integer-keyed MessagePack map of the 1-based field numbers (WIT
// declaration order). Option fields are omitted when nil (proto3 presence
// semantics); []byte fields encode as arrays of u8 (the record-context form
// of list<u8>), NOT as MessagePack bin.
func UniFsDirentToValue(x UniFsDirent) (any, error) {
	_d := map[uint64]any{}
	_d[1] = x.Name
	_d[2] = x.IsDir
	_d[3] = x.Length
	return _d, nil
}

// UniFsDirentFromValue converts a wire value back to UniFsDirent.
// Decode is lenient: non-integer map keys are skipped, unknown field numbers
// are ignored and missing fields keep their proto3-style default.
func UniFsDirentFromValue(v any) (UniFsDirent, error) {
	var x UniFsDirent
	_m, err := expectMap(v)
	if err != nil {
		return x, err
	}
	for _k, _val := range _m {
		_key, _ok := mapKeyUint(_k)
		if !_ok {
			continue
		}
		switch _key {
		case 1:
			x.Name, err = strChecked(_val)
			if err != nil {
				return x, err
			}
		case 2:
			x.IsDir, err = boolChecked(_val)
			if err != nil {
				return x, err
			}
		case 3:
			x.Length, err = u64Checked(_val)
			if err != nil {
				return x, err
			}
		}
	}
	return x, nil
}
