// Generated by mudu_gen. Do not edit manually.
package types

type UniMessage struct {
	MessageId      uint32
	SourceOid      UniOid
	DestinationOid UniOid
	Payload        []byte
}

// UniMessageToValue converts x to its MSSP wire value: the
// integer-keyed MessagePack map of the 1-based field numbers (WIT
// declaration order). Option fields are omitted when nil (proto3 presence
// semantics); []byte fields encode as arrays of u8 (the record-context form
// of list<u8>), NOT as MessagePack bin.
func UniMessageToValue(x UniMessage) (any, error) {
	_d := map[uint64]any{}
	_d[1] = x.MessageId
	_c0, err := UniOidToValue(x.SourceOid)
	if err != nil {
		return nil, err
	}
	_d[2] = _c0
	_c1, err := UniOidToValue(x.DestinationOid)
	if err != nil {
		return nil, err
	}
	_d[3] = _c1
	_d[4] = blobToArrayValue(x.Payload)
	return _d, nil
}

// UniMessageFromValue converts a wire value back to UniMessage.
// Decode is lenient: non-integer map keys are skipped, unknown field numbers
// are ignored and missing fields keep their proto3-style default.
func UniMessageFromValue(v any) (UniMessage, error) {
	var x UniMessage
	_m, err := expectMap(v)
	if err != nil {
		return x, err
	}
	for _k, _val := range _m {
		_key, _ok := mapKeyUint(_k)
		if !_ok {
			continue
		}
		switch _key {
		case 1:
			x.MessageId, err = u32Checked(_val)
			if err != nil {
				return x, err
			}
		case 2:
			x.SourceOid, err = UniOidFromValue(_val)
			if err != nil {
				return x, err
			}
		case 3:
			x.DestinationOid, err = UniOidFromValue(_val)
			if err != nil {
				return x, err
			}
		case 4:
			x.Payload, err = blobFromValue(_val)
			if err != nil {
				return x, err
			}
		}
	}
	return x, nil
}
