// Generated by mudu_gen. Do not edit manually.
package types

type UniResultSet struct {
	Eof    bool
	RowSet []UniTupleRow
	Cursor []byte
}

// UniResultSetToValue converts x to its MSSP wire value: the
// integer-keyed MessagePack map of the 1-based field numbers (WIT
// declaration order). Option fields are omitted when nil (proto3 presence
// semantics); []byte fields encode as arrays of u8 (the record-context form
// of list<u8>), NOT as MessagePack bin.
func UniResultSetToValue(x UniResultSet) (any, error) {
	_d := map[uint64]any{}
	_d[1] = x.Eof
	_v0 := make([]any, len(x.RowSet))
	for _i0, _e0 := range x.RowSet {
		_c1, err := UniTupleRowToValue(_e0)
		if err != nil {
			return nil, err
		}
		_v0[_i0] = _c1
	}
	_d[2] = _v0
	_d[3] = blobToArrayValue(x.Cursor)
	return _d, nil
}

// UniResultSetFromValue converts a wire value back to UniResultSet.
// Decode is lenient: non-integer map keys are skipped, unknown field numbers
// are ignored and missing fields keep their proto3-style default.
func UniResultSetFromValue(v any) (UniResultSet, error) {
	var x UniResultSet
	_m, err := expectMap(v)
	if err != nil {
		return x, err
	}
	for _k, _val := range _m {
		_key, _ok := mapKeyUint(_k)
		if !_ok {
			continue
		}
		switch _key {
		case 1:
			x.Eof, err = boolChecked(_val)
			if err != nil {
				return x, err
			}
		case 2:
			_l0, err := expectList(_val)
			if err != nil {
				return x, err
			}
			_v0 := make([]UniTupleRow, len(_l0))
			for _i0, _e0 := range _l0 {
				_v0[_i0], err = UniTupleRowFromValue(_e0)
				if err != nil {
					return x, err
				}
			}
			x.RowSet = _v0
		case 3:
			x.Cursor, err = blobFromValue(_val)
			if err != nil {
				return x, err
			}
		}
	}
	return x, nil
}
