// Hand-written wire-conversion helpers used by the mgen-generated codecs in
// this package (the files carrying the "Generated by mudu_gen" header).
//
// Decode is lenient — any integer width is accepted (range-checked against
// the target type), a bool also decodes from its procedure byte-pipe form
// (the i32 0/1 of the host's uni-data-value vocabulary), blobs accept both
// the bin and the array-of-int form, maps accept both the read-side
// map[any]any and the value-model map[uint64]any, non-integer record map
// keys are skipped and missing fields keep their proto3-style default.
// Encode takes already-typed Go values and converts them to the wire value
// model of the codec package.
//
// TinyGo-compatible: no unsafe, no generics, no reflection.
package types

import (
	"fmt"
	"unicode/utf8"

	"github.com/ybbh/mududb_p/bindings/go/codec"
)

// typeError reports a wire value of an unexpected shape.
func typeError(what string, v any) error {
	return fmt.Errorf("expected %s, got %T: %v", what, v, v)
}

// rangeError reports an integer outside the target type's range.
func rangeError(what string, lo, hi, v int64) error {
	return fmt.Errorf("%s out of range [%d, %d]: %d", what, lo, hi, v)
}

func u64Checked(v any) (uint64, error) {
	switch t := v.(type) {
	case uint64:
		return t, nil
	case uint8:
		return uint64(t), nil
	case uint16:
		return uint64(t), nil
	case uint32:
		return uint64(t), nil
	case uint:
		return uint64(t), nil
	case int8:
		return signedAsU64(int64(t), v)
	case int16:
		return signedAsU64(int64(t), v)
	case int32:
		return signedAsU64(int64(t), v)
	case int64:
		return signedAsU64(t, v)
	case int:
		return signedAsU64(int64(t), v)
	default:
		return 0, typeError("u64", v)
	}
}

func signedAsU64(s int64, v any) (uint64, error) {
	if s < 0 {
		return 0, typeError("u64 (negative value)", v)
	}
	return uint64(s), nil
}

func i64Checked(v any) (int64, error) {
	switch t := v.(type) {
	case int64:
		return t, nil
	case int8:
		return int64(t), nil
	case int16:
		return int64(t), nil
	case int32:
		return int64(t), nil
	case int:
		return int64(t), nil
	case uint8:
		return int64(t), nil
	case uint16:
		return int64(t), nil
	case uint32:
		return int64(t), nil
	case uint64:
		if t > 9223372036854775807 {
			return 0, typeError("i64 (overflow)", v)
		}
		return int64(t), nil
	case uint:
		return i64Checked(uint64(t))
	default:
		return 0, typeError("i64", v)
	}
}

func u8Checked(v any) (uint8, error) {
	n, err := u64Checked(v)
	if err != nil {
		return 0, err
	}
	if n > 255 {
		return 0, rangeError("u8", 0, 255, int64(n))
	}
	return uint8(n), nil
}

func u16Checked(v any) (uint16, error) {
	n, err := u64Checked(v)
	if err != nil {
		return 0, err
	}
	if n > 65535 {
		return 0, rangeError("u16", 0, 65535, int64(n))
	}
	return uint16(n), nil
}

func u32Checked(v any) (uint32, error) {
	n, err := u64Checked(v)
	if err != nil {
		return 0, err
	}
	if n > 4294967295 {
		return 0, rangeError("u32", 0, 4294967295, int64(n))
	}
	return uint32(n), nil
}

func i8Checked(v any) (int8, error) {
	n, err := i64Checked(v)
	if err != nil {
		return 0, err
	}
	if n < -128 || n > 127 {
		return 0, rangeError("i8", -128, 127, n)
	}
	return int8(n), nil
}

func i16Checked(v any) (int16, error) {
	n, err := i64Checked(v)
	if err != nil {
		return 0, err
	}
	if n < -32768 || n > 32767 {
		return 0, rangeError("i16", -32768, 32767, n)
	}
	return int16(n), nil
}

func i32Checked(v any) (int32, error) {
	n, err := i64Checked(v)
	if err != nil {
		return 0, err
	}
	if n < -2147483648 || n > 2147483647 {
		return 0, rangeError("i32", -2147483648, 2147483647, n)
	}
	return int32(n), nil
}

func boolChecked(v any) (bool, error) {
	if b, ok := v.(bool); ok {
		return b, nil
	}
	// A bool crosses the Mudu procedure byte pipe as an i32 (0/1): the
	// host's uni-data-value vocabulary has no Bool case (its desc declares
	// the I32 family). Accept the integer form so the generated codecs can
	// decode host-supplied records.
	n, err := i64Checked(v)
	if err != nil {
		return false, typeError("bool", v)
	}
	if n == 0 {
		return false, nil
	}
	if n == 1 {
		return true, nil
	}
	return false, rangeError("bool", 0, 1, n)
}

func f64Checked(v any) (float64, error) {
	switch t := v.(type) {
	case float64:
		return t, nil
	case float32:
		return float64(t), nil
	case codec.F32:
		return float64(t), nil
	default:
		// integers convert like the Python binding's _f64_checked
		if n, err := i64Checked(v); err == nil {
			return float64(n), nil
		}
		if n, err := u64Checked(v); err == nil {
			return float64(n), nil
		}
		return 0, typeError("f64", v)
	}
}

func f32FromValue(v any) (float32, error) {
	f, err := f64Checked(v)
	if err != nil {
		return 0, err
	}
	return float32(f), nil
}

func strChecked(v any) (string, error) {
	if s, ok := v.(string); ok {
		return s, nil
	}
	return "", typeError("str", v)
}

func charChecked(v any) (string, error) {
	if s, ok := v.(string); ok && utf8.RuneCountInString(s) == 1 {
		return s, nil
	}
	return "", typeError("char (a single-rune string)", v)
}

// bytesChecked asserts the func-context blob form: a plain []byte (the wire
// bin form), nothing else.
func bytesChecked(v any) ([]byte, error) {
	if b, ok := v.([]byte); ok {
		return b, nil
	}
	return nil, typeError("bytes", v)
}

// blobFromValue accepts both the bin and the array-of-u8 form (lenient) and
// always returns a freshly allocated slice.
func blobFromValue(v any) ([]byte, error) {
	switch t := v.(type) {
	case []byte:
		out := make([]byte, len(t))
		copy(out, t)
		return out, nil
	case []any:
		out := make([]byte, len(t))
		for i, item := range t {
			b, err := u8Checked(item)
			if err != nil {
				return nil, err
			}
			out[i] = b
		}
		return out, nil
	default:
		return nil, typeError("bytes or a list of u8", v)
	}
}

// blobToArrayValue converts a blob to the record-context wire form: a
// MessagePack ARRAY of u8 ([]any of uint8), not a bin.
func blobToArrayValue(b []byte) []any {
	out := make([]any, len(b))
	for i, v := range b {
		out[i] = v
	}
	return out
}

// u128FromValue decodes a u128 from its 16-byte big-endian form (bin or
// array-of-u8, lenient).
func u128FromValue(v any) ([16]byte, error) {
	return int128FromValue(v, "u128")
}

// i128FromValue decodes an i128 from its 16-byte big-endian form (bin or
// array-of-u8, lenient).
func i128FromValue(v any) ([16]byte, error) {
	return int128FromValue(v, "i128")
}

func int128FromValue(v any, what string) ([16]byte, error) {
	data, err := blobFromValue(v)
	if err != nil {
		return [16]byte{}, err
	}
	if len(data) != 16 {
		return [16]byte{}, fmt.Errorf("%s must be 16 bytes, got %d", what, len(data))
	}
	var out [16]byte
	copy(out[:], data)
	return out, nil
}

func expectMap(v any) (map[any]any, error) {
	switch m := v.(type) {
	case map[any]any:
		return m, nil
	case map[uint64]any:
		// the value-model map form: an XxxToValue result or the record
		// bridge output fed back to a decoder — the same integer-keyed map
		// with the keys typed
		out := make(map[any]any, len(m))
		for key, value := range m {
			out[key] = value
		}
		return out, nil
	default:
		return nil, typeError("a map", v)
	}
}

func expectList(v any) ([]any, error) {
	if l, ok := v.([]any); ok {
		return l, nil
	}
	return nil, typeError("an array", v)
}

func expectSeq(v any, n int) ([]any, error) {
	if l, ok := v.([]any); ok && len(l) == n {
		return l, nil
	}
	return nil, typeError(fmt.Sprintf("a %d-element array", n), v)
}

// mapKeyUint converts a wire record/request map key to its field number.
// Integer keys of any width are returned (negative keys report not-ok); any
// non-integer key reports not-ok, so the caller skips the associated value —
// matching the host's lenient key handling. Field numbers are 1-based.
func mapKeyUint(key any) (uint64, bool) {
	switch k := key.(type) {
	case uint8:
		return uint64(k), true
	case uint16:
		return uint64(k), true
	case uint32:
		return uint64(k), true
	case uint64:
		return k, true
	case uint:
		return uint64(k), true
	case int8:
		return signedMapKey(int64(k))
	case int16:
		return signedMapKey(int64(k))
	case int32:
		return signedMapKey(int64(k))
	case int64:
		return signedMapKey(k)
	case int:
		return signedMapKey(int64(k))
	default:
		return 0, false
	}
}

func signedMapKey(v int64) (uint64, bool) {
	if v < 0 {
		return 0, false
	}
	return uint64(v), true
}
