pub mod dat_internal;

pub mod build_tuple;
pub mod comparator;
pub mod dat_binary;
pub mod dat_printable;
pub mod enum_dat;
mod field_desc;
mod read_datum;
mod slot;
pub mod tuple_binary_desc;
pub mod tuple_key;
pub mod tuple_binary;
pub mod tuple_ref;
pub mod update_tuple;
mod write_value;
pub mod datum;
pub mod tuple_field;
pub mod tuple_field_desc;
pub mod datum_vec;
pub mod datum_desc;
pub mod rs_tuple_datum;
pub mod enumerable_datum;
pub mod vec_dyn_datum;
pub mod typed_bin;
