// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::customer_type::Customer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `customer`.
///
/// Obtain a handle from the [`CustomerTableAccess::customer`] method on [`super::RemoteTables`],
/// like `ctx.db.customer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.customer().on_insert(...)`.
pub struct CustomerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Customer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `customer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CustomerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CustomerTableHandle`], which mediates access to the table `customer`.
    fn customer(&self) -> CustomerTableHandle<'_>;
}

impl CustomerTableAccess for super::RemoteTables {
    fn customer(&self) -> CustomerTableHandle<'_> {
        CustomerTableHandle {
            imp: self.imp.get_table::<Customer>("customer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CustomerInsertCallbackId(__sdk::CallbackId);
pub struct CustomerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CustomerTableHandle<'ctx> {
    type Row = Customer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Customer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CustomerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CustomerInsertCallbackId {
        CustomerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CustomerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CustomerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CustomerDeleteCallbackId {
        CustomerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CustomerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Customer>("customer");
    _table.add_unique_constraint::<u64>("pk", |row| &row.pk);
}
pub struct CustomerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CustomerTableHandle<'ctx> {
    type UpdateCallbackId = CustomerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CustomerUpdateCallbackId {
        CustomerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CustomerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Customer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Customer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `pk` unique index on the table `customer`,
/// which allows point queries on the field of the same name
/// via the [`CustomerPkUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.customer().pk().find(...)`.
pub struct CustomerPkUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Customer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CustomerTableHandle<'ctx> {
    /// Get a handle on the `pk` unique index on the table `customer`.
    pub fn pk(&self) -> CustomerPkUnique<'ctx> {
        CustomerPkUnique {
            imp: self.imp.get_unique_constraint::<u64>("pk"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CustomerPkUnique<'ctx> {
    /// Find the subscribed row whose `pk` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Customer> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Customer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait customerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Customer`.
    fn customer(&self) -> __sdk::__query_builder::Table<Customer>;
}

impl customerQueryTableAccess for __sdk::QueryTableAccessor {
    fn customer(&self) -> __sdk::__query_builder::Table<Customer> {
        __sdk::__query_builder::Table::new("customer")
    }
}
