// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.12.0 (commit 4fdb8d923f39ed592931ad4c7e6391ed99b9fe3a).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod customer_table;
pub mod customer_type;
pub mod district_table;
pub mod district_type;
pub mod history_table;
pub mod history_type;
pub mod hotspot_seed_reducer;
pub mod hotspot_table;
pub mod hotspot_type;
pub mod item_table;
pub mod item_type;
pub mod new_order_table;
pub mod new_order_type;
pub mod order_line_table;
pub mod order_line_type;
pub mod orders_table;
pub mod orders_type;
pub mod seckill_buy_reducer;
pub mod seckill_item_table;
pub mod seckill_item_type;
pub mod seckill_order_table;
pub mod seckill_order_type;
pub mod seckill_seed_reducer;
pub mod stock_table;
pub mod stock_type;
pub mod tpcc_delivery_reducer;
pub mod tpcc_hotspot_hit_reducer;
pub mod tpcc_new_order_reducer;
pub mod tpcc_order_status_reducer;
pub mod tpcc_payment_reducer;
pub mod tpcc_seed_reducer;
pub mod tpcc_stock_level_reducer;
pub mod warehouse_table;
pub mod warehouse_type;

pub use customer_table::*;
pub use customer_type::Customer;
pub use district_table::*;
pub use district_type::District;
pub use history_table::*;
pub use history_type::History;
pub use hotspot_seed_reducer::{HotspotSeedCallbackId, hotspot_seed, set_flags_for_hotspot_seed};
pub use hotspot_table::*;
pub use hotspot_type::Hotspot;
pub use item_table::*;
pub use item_type::Item;
pub use new_order_table::*;
pub use new_order_type::NewOrder;
pub use order_line_table::*;
pub use order_line_type::OrderLine;
pub use orders_table::*;
pub use orders_type::Orders;
pub use seckill_buy_reducer::{SeckillBuyCallbackId, seckill_buy, set_flags_for_seckill_buy};
pub use seckill_item_table::*;
pub use seckill_item_type::SeckillItem;
pub use seckill_order_table::*;
pub use seckill_order_type::SeckillOrder;
pub use seckill_seed_reducer::{SeckillSeedCallbackId, seckill_seed, set_flags_for_seckill_seed};
pub use stock_table::*;
pub use stock_type::Stock;
pub use tpcc_delivery_reducer::{
    TpccDeliveryCallbackId, set_flags_for_tpcc_delivery, tpcc_delivery,
};
pub use tpcc_hotspot_hit_reducer::{
    TpccHotspotHitCallbackId, set_flags_for_tpcc_hotspot_hit, tpcc_hotspot_hit,
};
pub use tpcc_new_order_reducer::{
    TpccNewOrderCallbackId, set_flags_for_tpcc_new_order, tpcc_new_order,
};
pub use tpcc_order_status_reducer::{
    TpccOrderStatusCallbackId, set_flags_for_tpcc_order_status, tpcc_order_status,
};
pub use tpcc_payment_reducer::{TpccPaymentCallbackId, set_flags_for_tpcc_payment, tpcc_payment};
pub use tpcc_seed_reducer::{TpccSeedCallbackId, set_flags_for_tpcc_seed, tpcc_seed};
pub use tpcc_stock_level_reducer::{
    TpccStockLevelCallbackId, set_flags_for_tpcc_stock_level, tpcc_stock_level,
};
pub use warehouse_table::*;
pub use warehouse_type::Warehouse;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    HotspotSeed {
        warehouse_id: i32,
        hot_rows: i32,
        op_index: u64,
    },
    SeckillBuy {
        item_id: i32,
        order_id: i32,
        user_id: i32,
        amount: i32,
        payload: String,
        op_index: u64,
    },
    SeckillSeed {
        item_count: i32,
        initial_stock: i32,
        op_index: u64,
    },
    TpccDelivery {
        warehouse_id: i32,
        district_id: i32,
        carrier_id: i32,
        op_index: u64,
    },
    TpccHotspotHit {
        warehouse_id: i32,
        hot_id: i32,
        op_index: u64,
    },
    TpccNewOrder {
        warehouse_id: i32,
        district_id: i32,
        customer_id: i32,
        item_ids: Vec<i32>,
        supplier_warehouse_ids: Vec<i32>,
        quantities: Vec<i32>,
        op_index: u64,
    },
    TpccOrderStatus {
        warehouse_id: i32,
        district_id: i32,
        customer_id: i32,
        op_index: u64,
    },
    TpccPayment {
        warehouse_id: i32,
        district_id: i32,
        customer_id: i32,
        amount: i32,
        op_index: u64,
    },
    TpccSeed {
        warehouse_id: i32,
        district_count: i32,
        customer_count: i32,
        item_count: i32,
        op_index: u64,
    },
    TpccStockLevel {
        warehouse_id: i32,
        district_id: i32,
        threshold: i32,
        op_index: u64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::HotspotSeed { .. } => "hotspot_seed",
            Reducer::SeckillBuy { .. } => "seckill_buy",
            Reducer::SeckillSeed { .. } => "seckill_seed",
            Reducer::TpccDelivery { .. } => "tpcc_delivery",
            Reducer::TpccHotspotHit { .. } => "tpcc_hotspot_hit",
            Reducer::TpccNewOrder { .. } => "tpcc_new_order",
            Reducer::TpccOrderStatus { .. } => "tpcc_order_status",
            Reducer::TpccPayment { .. } => "tpcc_payment",
            Reducer::TpccSeed { .. } => "tpcc_seed",
            Reducer::TpccStockLevel { .. } => "tpcc_stock_level",
            _ => unreachable!(),
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "hotspot_seed" => Ok(
                __sdk::parse_reducer_args::<hotspot_seed_reducer::HotspotSeedArgs>(
                    "hotspot_seed",
                    &value.args,
                )?
                .into(),
            ),
            "seckill_buy" => Ok(
                __sdk::parse_reducer_args::<seckill_buy_reducer::SeckillBuyArgs>(
                    "seckill_buy",
                    &value.args,
                )?
                .into(),
            ),
            "seckill_seed" => Ok(
                __sdk::parse_reducer_args::<seckill_seed_reducer::SeckillSeedArgs>(
                    "seckill_seed",
                    &value.args,
                )?
                .into(),
            ),
            "tpcc_delivery" => Ok(__sdk::parse_reducer_args::<
                tpcc_delivery_reducer::TpccDeliveryArgs,
            >("tpcc_delivery", &value.args)?
            .into()),
            "tpcc_hotspot_hit" => Ok(__sdk::parse_reducer_args::<
                tpcc_hotspot_hit_reducer::TpccHotspotHitArgs,
            >("tpcc_hotspot_hit", &value.args)?
            .into()),
            "tpcc_new_order" => Ok(__sdk::parse_reducer_args::<
                tpcc_new_order_reducer::TpccNewOrderArgs,
            >("tpcc_new_order", &value.args)?
            .into()),
            "tpcc_order_status" => Ok(__sdk::parse_reducer_args::<
                tpcc_order_status_reducer::TpccOrderStatusArgs,
            >("tpcc_order_status", &value.args)?
            .into()),
            "tpcc_payment" => Ok(
                __sdk::parse_reducer_args::<tpcc_payment_reducer::TpccPaymentArgs>(
                    "tpcc_payment",
                    &value.args,
                )?
                .into(),
            ),
            "tpcc_seed" => Ok(
                __sdk::parse_reducer_args::<tpcc_seed_reducer::TpccSeedArgs>(
                    "tpcc_seed",
                    &value.args,
                )?
                .into(),
            ),
            "tpcc_stock_level" => Ok(__sdk::parse_reducer_args::<
                tpcc_stock_level_reducer::TpccStockLevelArgs,
            >("tpcc_stock_level", &value.args)?
            .into()),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    customer: __sdk::TableUpdate<Customer>,
    district: __sdk::TableUpdate<District>,
    history: __sdk::TableUpdate<History>,
    hotspot: __sdk::TableUpdate<Hotspot>,
    item: __sdk::TableUpdate<Item>,
    new_order: __sdk::TableUpdate<NewOrder>,
    order_line: __sdk::TableUpdate<OrderLine>,
    orders: __sdk::TableUpdate<Orders>,
    seckill_item: __sdk::TableUpdate<SeckillItem>,
    seckill_order: __sdk::TableUpdate<SeckillOrder>,
    stock: __sdk::TableUpdate<Stock>,
    warehouse: __sdk::TableUpdate<Warehouse>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "customer" => db_update
                    .customer
                    .append(customer_table::parse_table_update(table_update)?),
                "district" => db_update
                    .district
                    .append(district_table::parse_table_update(table_update)?),
                "history" => db_update
                    .history
                    .append(history_table::parse_table_update(table_update)?),
                "hotspot" => db_update
                    .hotspot
                    .append(hotspot_table::parse_table_update(table_update)?),
                "item" => db_update
                    .item
                    .append(item_table::parse_table_update(table_update)?),
                "new_order" => db_update
                    .new_order
                    .append(new_order_table::parse_table_update(table_update)?),
                "order_line" => db_update
                    .order_line
                    .append(order_line_table::parse_table_update(table_update)?),
                "orders" => db_update
                    .orders
                    .append(orders_table::parse_table_update(table_update)?),
                "seckill_item" => db_update
                    .seckill_item
                    .append(seckill_item_table::parse_table_update(table_update)?),
                "seckill_order" => db_update
                    .seckill_order
                    .append(seckill_order_table::parse_table_update(table_update)?),
                "stock" => db_update
                    .stock
                    .append(stock_table::parse_table_update(table_update)?),
                "warehouse" => db_update
                    .warehouse
                    .append(warehouse_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.customer = cache
            .apply_diff_to_table::<Customer>("customer", &self.customer)
            .with_updates_by_pk(|row| &row.pk);
        diff.district = cache
            .apply_diff_to_table::<District>("district", &self.district)
            .with_updates_by_pk(|row| &row.pk);
        diff.history = cache
            .apply_diff_to_table::<History>("history", &self.history)
            .with_updates_by_pk(|row| &row.h_seq);
        diff.hotspot = cache
            .apply_diff_to_table::<Hotspot>("hotspot", &self.hotspot)
            .with_updates_by_pk(|row| &row.pk);
        diff.item = cache
            .apply_diff_to_table::<Item>("item", &self.item)
            .with_updates_by_pk(|row| &row.i_id);
        diff.new_order = cache
            .apply_diff_to_table::<NewOrder>("new_order", &self.new_order)
            .with_updates_by_pk(|row| &row.pk);
        diff.order_line = cache
            .apply_diff_to_table::<OrderLine>("order_line", &self.order_line)
            .with_updates_by_pk(|row| &row.pk);
        diff.orders = cache
            .apply_diff_to_table::<Orders>("orders", &self.orders)
            .with_updates_by_pk(|row| &row.pk);
        diff.seckill_item = cache
            .apply_diff_to_table::<SeckillItem>("seckill_item", &self.seckill_item)
            .with_updates_by_pk(|row| &row.si_id);
        diff.seckill_order = cache
            .apply_diff_to_table::<SeckillOrder>("seckill_order", &self.seckill_order)
            .with_updates_by_pk(|row| &row.pk);
        diff.stock = cache
            .apply_diff_to_table::<Stock>("stock", &self.stock)
            .with_updates_by_pk(|row| &row.pk);
        diff.warehouse = cache
            .apply_diff_to_table::<Warehouse>("warehouse", &self.warehouse)
            .with_updates_by_pk(|row| &row.w_id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    customer: __sdk::TableAppliedDiff<'r, Customer>,
    district: __sdk::TableAppliedDiff<'r, District>,
    history: __sdk::TableAppliedDiff<'r, History>,
    hotspot: __sdk::TableAppliedDiff<'r, Hotspot>,
    item: __sdk::TableAppliedDiff<'r, Item>,
    new_order: __sdk::TableAppliedDiff<'r, NewOrder>,
    order_line: __sdk::TableAppliedDiff<'r, OrderLine>,
    orders: __sdk::TableAppliedDiff<'r, Orders>,
    seckill_item: __sdk::TableAppliedDiff<'r, SeckillItem>,
    seckill_order: __sdk::TableAppliedDiff<'r, SeckillOrder>,
    stock: __sdk::TableAppliedDiff<'r, Stock>,
    warehouse: __sdk::TableAppliedDiff<'r, Warehouse>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Customer>("customer", &self.customer, event);
        callbacks.invoke_table_row_callbacks::<District>("district", &self.district, event);
        callbacks.invoke_table_row_callbacks::<History>("history", &self.history, event);
        callbacks.invoke_table_row_callbacks::<Hotspot>("hotspot", &self.hotspot, event);
        callbacks.invoke_table_row_callbacks::<Item>("item", &self.item, event);
        callbacks.invoke_table_row_callbacks::<NewOrder>("new_order", &self.new_order, event);
        callbacks.invoke_table_row_callbacks::<OrderLine>("order_line", &self.order_line, event);
        callbacks.invoke_table_row_callbacks::<Orders>("orders", &self.orders, event);
        callbacks.invoke_table_row_callbacks::<SeckillItem>(
            "seckill_item",
            &self.seckill_item,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SeckillOrder>(
            "seckill_order",
            &self.seckill_order,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Stock>("stock", &self.stock, event);
        callbacks.invoke_table_row_callbacks::<Warehouse>("warehouse", &self.warehouse, event);
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SetReducerFlags = SetReducerFlags,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        customer_table::register_table(client_cache);
        district_table::register_table(client_cache);
        history_table::register_table(client_cache);
        hotspot_table::register_table(client_cache);
        item_table::register_table(client_cache);
        new_order_table::register_table(client_cache);
        order_line_table::register_table(client_cache);
        orders_table::register_table(client_cache);
        seckill_item_table::register_table(client_cache);
        seckill_order_table::register_table(client_cache);
        stock_table::register_table(client_cache);
        warehouse_table::register_table(client_cache);
    }
}
