// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SeckillOrder {
    pub pk: u64,
    pub so_item_id: i32,
    pub so_id: i32,
    pub so_user_id: i32,
    pub so_amount: i32,
    pub so_payload: String,
}

impl __sdk::InModule for SeckillOrder {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SeckillOrder`.
///
/// Provides typed access to columns for query building.
pub struct SeckillOrderCols {
    pub pk: __sdk::__query_builder::Col<SeckillOrder, u64>,
    pub so_item_id: __sdk::__query_builder::Col<SeckillOrder, i32>,
    pub so_id: __sdk::__query_builder::Col<SeckillOrder, i32>,
    pub so_user_id: __sdk::__query_builder::Col<SeckillOrder, i32>,
    pub so_amount: __sdk::__query_builder::Col<SeckillOrder, i32>,
    pub so_payload: __sdk::__query_builder::Col<SeckillOrder, String>,
}

impl __sdk::__query_builder::HasCols for SeckillOrder {
    type Cols = SeckillOrderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SeckillOrderCols {
            pk: __sdk::__query_builder::Col::new(table_name, "pk"),
            so_item_id: __sdk::__query_builder::Col::new(table_name, "so_item_id"),
            so_id: __sdk::__query_builder::Col::new(table_name, "so_id"),
            so_user_id: __sdk::__query_builder::Col::new(table_name, "so_user_id"),
            so_amount: __sdk::__query_builder::Col::new(table_name, "so_amount"),
            so_payload: __sdk::__query_builder::Col::new(table_name, "so_payload"),
        }
    }
}

/// Indexed column accessor struct for the table `SeckillOrder`.
///
/// Provides typed access to indexed columns for query building.
pub struct SeckillOrderIxCols {
    pub pk: __sdk::__query_builder::IxCol<SeckillOrder, u64>,
}

impl __sdk::__query_builder::HasIxCols for SeckillOrder {
    type IxCols = SeckillOrderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SeckillOrderIxCols {
            pk: __sdk::__query_builder::IxCol::new(table_name, "pk"),
        }
    }
}
