// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SeckillItem {
    pub si_id: i32,
    pub si_name: String,
    pub si_stock: i32,
    pub si_sold: i32,
    pub si_price: i32,
}

impl __sdk::InModule for SeckillItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SeckillItem`.
///
/// Provides typed access to columns for query building.
pub struct SeckillItemCols {
    pub si_id: __sdk::__query_builder::Col<SeckillItem, i32>,
    pub si_name: __sdk::__query_builder::Col<SeckillItem, String>,
    pub si_stock: __sdk::__query_builder::Col<SeckillItem, i32>,
    pub si_sold: __sdk::__query_builder::Col<SeckillItem, i32>,
    pub si_price: __sdk::__query_builder::Col<SeckillItem, i32>,
}

impl __sdk::__query_builder::HasCols for SeckillItem {
    type Cols = SeckillItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SeckillItemCols {
            si_id: __sdk::__query_builder::Col::new(table_name, "si_id"),
            si_name: __sdk::__query_builder::Col::new(table_name, "si_name"),
            si_stock: __sdk::__query_builder::Col::new(table_name, "si_stock"),
            si_sold: __sdk::__query_builder::Col::new(table_name, "si_sold"),
            si_price: __sdk::__query_builder::Col::new(table_name, "si_price"),
        }
    }
}

/// Indexed column accessor struct for the table `SeckillItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct SeckillItemIxCols {
    pub si_id: __sdk::__query_builder::IxCol<SeckillItem, i32>,
}

impl __sdk::__query_builder::HasIxCols for SeckillItem {
    type IxCols = SeckillItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SeckillItemIxCols {
            si_id: __sdk::__query_builder::IxCol::new(table_name, "si_id"),
        }
    }
}
