// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TpccPaymentArgs {
    pub warehouse_id: i32,
    pub district_id: i32,
    pub customer_id: i32,
    pub amount: i32,
    pub op_index: u64,
}

impl From<TpccPaymentArgs> for super::Reducer {
    fn from(args: TpccPaymentArgs) -> Self {
        Self::TpccPayment {
            warehouse_id: args.warehouse_id,
            district_id: args.district_id,
            customer_id: args.customer_id,
            amount: args.amount,
            op_index: args.op_index,
        }
    }
}

impl __sdk::InModule for TpccPaymentArgs {
    type Module = super::RemoteModule;
}

pub struct TpccPaymentCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `tpcc_payment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait tpcc_payment {
    /// Request that the remote module invoke the reducer `tpcc_payment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_tpcc_payment`] callbacks.
    fn tpcc_payment(
        &self,
        warehouse_id: i32,
        district_id: i32,
        customer_id: i32,
        amount: i32,
        op_index: u64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `tpcc_payment`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TpccPaymentCallbackId`] can be passed to [`Self::remove_on_tpcc_payment`]
    /// to cancel the callback.
    fn on_tpcc_payment(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32, &i32, &u64) + Send + 'static,
    ) -> TpccPaymentCallbackId;
    /// Cancel a callback previously registered by [`Self::on_tpcc_payment`],
    /// causing it not to run in the future.
    fn remove_on_tpcc_payment(&self, callback: TpccPaymentCallbackId);
}

impl tpcc_payment for super::RemoteReducers {
    fn tpcc_payment(
        &self,
        warehouse_id: i32,
        district_id: i32,
        customer_id: i32,
        amount: i32,
        op_index: u64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "tpcc_payment",
            TpccPaymentArgs {
                warehouse_id,
                district_id,
                customer_id,
                amount,
                op_index,
            },
        )
    }
    fn on_tpcc_payment(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32, &i32, &u64)
        + Send
        + 'static,
    ) -> TpccPaymentCallbackId {
        TpccPaymentCallbackId(self.imp.on_reducer(
            "tpcc_payment",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::TpccPayment {
                                    warehouse_id,
                                    district_id,
                                    customer_id,
                                    amount,
                                    op_index,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    warehouse_id,
                    district_id,
                    customer_id,
                    amount,
                    op_index,
                )
            }),
        ))
    }
    fn remove_on_tpcc_payment(&self, callback: TpccPaymentCallbackId) {
        self.imp.remove_on_reducer("tpcc_payment", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `tpcc_payment`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_tpcc_payment {
    /// Set the call-reducer flags for the reducer `tpcc_payment` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn tpcc_payment(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_tpcc_payment for super::SetReducerFlags {
    fn tpcc_payment(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("tpcc_payment", flags);
    }
}
