// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::warehouse_type::Warehouse;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `warehouse`.
///
/// Obtain a handle from the [`WarehouseTableAccess::warehouse`] method on [`super::RemoteTables`],
/// like `ctx.db.warehouse()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.warehouse().on_insert(...)`.
pub struct WarehouseTableHandle<'ctx> {
    imp: __sdk::TableHandle<Warehouse>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `warehouse`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WarehouseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WarehouseTableHandle`], which mediates access to the table `warehouse`.
    fn warehouse(&self) -> WarehouseTableHandle<'_>;
}

impl WarehouseTableAccess for super::RemoteTables {
    fn warehouse(&self) -> WarehouseTableHandle<'_> {
        WarehouseTableHandle {
            imp: self.imp.get_table::<Warehouse>("warehouse"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WarehouseInsertCallbackId(__sdk::CallbackId);
pub struct WarehouseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WarehouseTableHandle<'ctx> {
    type Row = Warehouse;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Warehouse> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WarehouseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WarehouseInsertCallbackId {
        WarehouseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WarehouseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WarehouseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WarehouseDeleteCallbackId {
        WarehouseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WarehouseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Warehouse>("warehouse");
    _table.add_unique_constraint::<i32>("w_id", |row| &row.w_id);
}
pub struct WarehouseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WarehouseTableHandle<'ctx> {
    type UpdateCallbackId = WarehouseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WarehouseUpdateCallbackId {
        WarehouseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WarehouseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Warehouse>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Warehouse>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `w_id` unique index on the table `warehouse`,
/// which allows point queries on the field of the same name
/// via the [`WarehouseWIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.warehouse().w_id().find(...)`.
pub struct WarehouseWIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Warehouse, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WarehouseTableHandle<'ctx> {
    /// Get a handle on the `w_id` unique index on the table `warehouse`.
    pub fn w_id(&self) -> WarehouseWIdUnique<'ctx> {
        WarehouseWIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("w_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WarehouseWIdUnique<'ctx> {
    /// Find the subscribed row whose `w_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<Warehouse> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Warehouse`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait warehouseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Warehouse`.
    fn warehouse(&self) -> __sdk::__query_builder::Table<Warehouse>;
}

impl warehouseQueryTableAccess for __sdk::QueryTableAccessor {
    fn warehouse(&self) -> __sdk::__query_builder::Table<Warehouse> {
        __sdk::__query_builder::Table::new("warehouse")
    }
}
