"""Record-envelope bridge (`mududb.codec.bridge`).

Hand-written bridge between the `uni-data-value` envelope a Mudu host passes
across the procedure byte pipe and the positional wire-value model of the
mgen-generated Python codecs (the project modules carrying the "Generated by
mudu_gen" header, e.g. a `profile_from_value` / `profile_to_value` pair).

A user-defined record argument travels as a `UniDataValue` record case: field
entries in WIT declaration order, field names possibly empty (the host drops
them — positional semantics). `record_field_values` unwraps that envelope
into the integer-keyed dict (1-based field numbers) the generated
`xxx_from_value` decoders consume; `record_from_field_values` is the
symmetric wrap for record return values, emitting empty field names like the
host does.

The host's transactable scalar vocabulary (`uni_to`/`uni_from` in
`mudu_binding`) has no Bool/U8..U32/U64 cases: booleans cross as i32 (0/1 —
the desc declares them I32, the same family the procedure scalar table
uses), unsigned 8-32-bit integers as i32, and u64 as i64. The bridge
performs exactly those mappings, so the generated codecs see the plain
Python values they expect and the host always receives scalar cases it
accepts.
"""

from mududb.codec.mpack import F32
from mududb.generated.uni_data_value import (
    UniDataValue,
    UniDataValueArray,
    UniDataValueBinary,
    UniDataValueField,
    UniDataValueRecord,
    UniDataValueScalar,
)
from mududb.generated.uni_scalar_value import (
    UniScalarValueBlob,
    UniScalarValueBool,
    UniScalarValueChar,
    UniScalarValueDate,
    UniScalarValueF32,
    UniScalarValueF64,
    UniScalarValueI8,
    UniScalarValueI16,
    UniScalarValueI32,
    UniScalarValueI64,
    UniScalarValueI128,
    UniScalarValueNull,
    UniScalarValueNumeric,
    UniScalarValueString,
    UniScalarValueTime,
    UniScalarValueTimestamp,
    UniScalarValueTimestampTz,
    UniScalarValueU8,
    UniScalarValueU16,
    UniScalarValueU32,
    UniScalarValueU64,
    UniScalarValueU128,
)

__all__ = ["record_field_values", "record_from_field_values"]


def record_field_values(uv) -> dict:
    """Unwrap a `UniDataValue` record-case envelope into the integer-keyed
    field dict (position i becomes key i+1, the WIT declaration order) the
    mgen-generated record decoders (`xxx_from_value`) consume.

    Field values convert to the plain wire-value model recursively (nested
    records become nested dicts, arrays become lists, the Null scalar becomes
    `None`). A non-record input is an error. Decode stays lenient end to
    end: the generated decoder skips field numbers it does not declare and
    defaults the missing ones.
    """
    if not isinstance(uv, UniDataValueRecord):
        raise TypeError(f"expected a UniDataValue record, got {type(uv).__name__}: {uv!r}")
    out = {}
    for i, field in enumerate(uv.inner):
        out[i + 1] = _wire_value_from_datum(field.field_value)
    return out


def record_from_field_values(vals) -> UniDataValue:
    """Wrap the positional field values of a record into the `UniDataValue`
    record-case envelope (field names empty — the wire is positional).

    The input is either the integer-keyed dict produced by the
    mgen-generated `xxx_to_value` encoders (1-based field numbers; a missing
    slot, e.g. an omitted option field, encodes as the Null scalar so
    declaration positions are preserved — note that trailing omitted slots
    cannot be recovered and shrink the record) or a plain positional list.
    Field values convert to the host's transactable scalar vocabulary (see
    the module docstring).
    """
    if isinstance(vals, dict):
        positional = _flatten_field_map(vals)
    elif isinstance(vals, (list, tuple)):
        positional = list(vals)
    else:
        raise TypeError(
            "expected a dict or list of record field values, "
            f"got {type(vals).__name__}: {vals!r}"
        )
    fields = [
        UniDataValueField(field_name="", field_value=_datum_from_wire_value(value))
        for value in positional
    ]
    return UniDataValueRecord(inner=fields)


def _flatten_field_map(m: dict) -> list:
    """Render a 1-based field dict as the positional list of slots 1..maxKey;
    absent slots (omitted option fields) stay `None`."""
    max_key = 0
    for key in m:
        if isinstance(key, bool) or not isinstance(key, int) or key < 0:
            raise ValueError(f"record field number must be a positive int, got {key!r}")
        max_key = max(max_key, key)
    out = [None] * max_key
    for key, value in m.items():
        if key == 0:
            # 0 is not a valid field number; skip it
            continue
        out[key - 1] = value
    return out


def _wire_value_from_datum(uv) -> object:
    """Convert a `UniDataValue` to its plain wire value in the mgen codec
    value model (the shape an `xxx_from_value` decoder expects for the
    corresponding field type)."""
    if isinstance(uv, UniDataValueScalar):
        return _wire_value_from_scalar(uv.inner)
    if isinstance(uv, UniDataValueArray):
        return [_wire_value_from_datum(item) for item in uv.inner]
    if isinstance(uv, UniDataValueRecord):
        return record_field_values(uv)
    if isinstance(uv, UniDataValueBinary):
        return bytes(uv.inner)
    raise TypeError(f"unknown UniDataValue kind {type(uv).__name__}: {uv!r}")


def _wire_value_from_scalar(sv) -> object:
    """Convert a `UniScalarValue` to its plain wire value. Integers of every
    width surface as `int` — the checked conversions of the generated
    decoders accept every width (range-checked against the declared field
    type)."""
    if isinstance(sv, UniScalarValueBool):
        return bool(sv.inner)
    if isinstance(
        sv,
        (
            UniScalarValueU8,
            UniScalarValueI8,
            UniScalarValueU16,
            UniScalarValueI16,
            UniScalarValueU32,
            UniScalarValueI32,
            UniScalarValueU64,
            UniScalarValueI64,
        ),
    ):
        return int(sv.inner)
    if isinstance(sv, UniScalarValueU128):
        return int.from_bytes(sv.inner, "big")
    if isinstance(sv, UniScalarValueI128):
        return int.from_bytes(sv.inner, "big", signed=True)
    if isinstance(sv, (UniScalarValueF32, UniScalarValueF64)):
        return float(sv.inner)
    if isinstance(
        sv,
        (
            UniScalarValueChar,
            UniScalarValueString,
            UniScalarValueNumeric,
            UniScalarValueDate,
            UniScalarValueTime,
            UniScalarValueTimestamp,
            UniScalarValueTimestampTz,
        ),
    ):
        return str(sv.inner)
    if isinstance(sv, UniScalarValueBlob):
        return bytes(sv.inner)
    if isinstance(sv, UniScalarValueNull):
        return None
    raise TypeError(f"unknown UniScalarValue kind {type(sv).__name__}: {sv!r}")


def _datum_from_wire_value(value) -> UniDataValue:
    """Convert a plain wire value (as produced by the mgen-generated
    `xxx_to_value` encoders) to a `UniDataValue` in the host's transactable
    vocabulary: booleans become I32 (0/1 — the host vocabulary has no Bool),
    integers become I64, and every composite shape recurses."""
    if value is None:
        return UniDataValueScalar(inner=UniScalarValueNull())
    # bool must be checked before int (Python bool is an int subclass).
    if isinstance(value, bool):
        return UniDataValueScalar(inner=UniScalarValueI32(inner=1 if value else 0))
    if isinstance(value, int):
        return UniDataValueScalar(inner=UniScalarValueI64(inner=value))
    # the F32 marker keeps the single-precision wire semantics through the
    # plain value model (it is a float subclass, so check it before float)
    if isinstance(value, F32):
        return UniDataValueScalar(inner=UniScalarValueF32(inner=float(value)))
    if isinstance(value, float):
        return UniDataValueScalar(inner=UniScalarValueF64(inner=value))
    if isinstance(value, str):
        return UniDataValueScalar(inner=UniScalarValueString(inner=value))
    if isinstance(value, (bytes, bytearray)):
        return UniDataValueScalar(inner=UniScalarValueBlob(inner=bytes(value)))
    if isinstance(value, (list, tuple)):
        return UniDataValueArray(inner=[_datum_from_wire_value(item) for item in value])
    if isinstance(value, dict):
        return record_from_field_values(value)
    raise TypeError(f"unsupported record field value type {type(value).__name__}: {value!r}")
