// Generated by mudu_gen. Do not edit manually.
/*
 * mududb C binding message types/codecs (mgen message -l c
 * --with-func-codec). Self-contained header: `MP_INLINE` functions only
 * (`static inline` in C, `inline` in C++), no mutable state. Ownership
 * contract: encode borrows its inputs; decode copies every variable-length
 * value into the caller's `mp_arena`; the writer owns its buffer
 * (`mpw_free`). See the package readme.md.
 */
#ifndef MUDUD_TYPES_UNI_DATA_VALUE_H
#define MUDUD_TYPES_UNI_DATA_VALUE_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "mududb/codec/mpack.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef MUDUD_FWD_UNI_DATA_VALUE
#define MUDUD_FWD_UNI_DATA_VALUE
typedef struct uni_data_value uni_data_value;
MP_INLINE void uni_data_value_encode(mp_writer *w, const uni_data_value *value);
MP_INLINE int uni_data_value_decode(mp_reader *r, mp_arena *a, uni_data_value *out);
MP_INLINE uni_data_value *uni_data_value_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_DATA_VALUE */
#ifndef MUDUD_FWD_UNI_DATA_VALUE_FIELD
#define MUDUD_FWD_UNI_DATA_VALUE_FIELD
typedef struct uni_data_value_field uni_data_value_field;
MP_INLINE void uni_data_value_field_encode(mp_writer *w, const uni_data_value_field *value);
MP_INLINE int uni_data_value_field_decode(mp_reader *r, mp_arena *a, uni_data_value_field *out);
MP_INLINE uni_data_value_field *uni_data_value_field_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_DATA_VALUE_FIELD */
#ifndef MUDUD_FWD_UNI_SCALAR_VALUE
#define MUDUD_FWD_UNI_SCALAR_VALUE
typedef struct uni_scalar_value uni_scalar_value;
MP_INLINE void uni_scalar_value_encode(mp_writer *w, const uni_scalar_value *value);
MP_INLINE int uni_scalar_value_decode(mp_reader *r, mp_arena *a, uni_scalar_value *out);
MP_INLINE uni_scalar_value *uni_scalar_value_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_SCALAR_VALUE */

typedef enum {
    UNI_DATA_VALUE_SCALAR = 0u,
    UNI_DATA_VALUE_ARRAY = 1u,
    UNI_DATA_VALUE_RECORD = 2u,
    UNI_DATA_VALUE_BINARY = 3u,
} uni_data_value_kind;

typedef struct { uni_data_value *items; uint32_t len; } uni_data_value_array_list;
typedef struct { uni_data_value_field *items; uint32_t len; } uni_data_value_record_list;
struct uni_data_value {
    uni_data_value_kind kind;
    union {
        uni_scalar_value * scalar;
        uni_data_value_array_list array;
        uni_data_value_record_list record;
        mp_bin binary;
    } as;
};

struct uni_data_value_field {
    mp_str field_name;
    uni_data_value field_value;
};

/* Encode `value` as a `[tag, payload]` 2-array; payload-less cases carry a
 * `0u8` placeholder (NOT nil), matching the Rust host's variant serde. An
 * unknown kind flags `w` (check `mpw_ok`) instead of emitting a corrupt
 * value. */
MP_INLINE void uni_data_value_encode(mp_writer *w, const uni_data_value *value) {
    mpw_array_header(w, 2u);
    mpw_u64(w, (uint64_t)value->kind);
    switch (value->kind) {
    case UNI_DATA_VALUE_SCALAR:
        if ((value->as.scalar) == 0) {
            mpw_fail(w);
        } else {
            uni_scalar_value_encode(w, &((*value->as.scalar)));
        }
        break;
    case UNI_DATA_VALUE_ARRAY:
        mpw_array_header(w, (value->as.array).len);
        for (uint32_t i0 = 0; i0 < (value->as.array).len; i0++) {
            uni_data_value_encode(w, &((value->as.array).items[i0]));
        }
        break;
    case UNI_DATA_VALUE_RECORD:
        mpw_array_header(w, (value->as.record).len);
        for (uint32_t i0 = 0; i0 < (value->as.record).len; i0++) {
            uni_data_value_field_encode(w, &((value->as.record).items[i0]));
        }
        break;
    case UNI_DATA_VALUE_BINARY:
        mpw_array_header(w, (value->as.binary).len);
        for (uint32_t i0 = 0; i0 < (value->as.binary).len; i0++) {
            mpw_u64(w, (value->as.binary).data[i0]);
        }
        break;
    default:
        /* unknown kind: flag the writer instead of emitting a corrupt value */
        mpw_fail(w);
        break;
    }
}

/* Decode one variant into `value` (arena contract of the generated
 * decoders). 0 on success, -1 (sticky error set) on a malformed shape or an
 * unknown tag. */
MP_INLINE int uni_data_value_decode(mp_reader *r, mp_arena *a, uni_data_value *value) {
    (void)a;
    memset(value, 0, sizeof(*value));
    if (mpr_array_header(r) != 2u) {
        mpr_fail(r);
        return -1;
    }
    {
        uint64_t tag = mpr_u64(r);
        switch (tag) {
        case 0u:
            value->kind = UNI_DATA_VALUE_SCALAR;
            {
                uni_scalar_value *p0 = uni_scalar_value_decode_new(r, a);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    value->as.scalar = p0;
                }
            }
            break;
        case 1u:
            value->kind = UNI_DATA_VALUE_ARRAY;
            {
                uint32_t n0 = mpr_array_header(r);
                uni_data_value *p0 = (uni_data_value *)mpa_alloc(a, sizeof(uni_data_value) * (size_t)n0);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    for (uint32_t i0 = 0; i0 < n0; i0++) {
                        uni_data_value_decode(r, a, &(p0[i0]));
                    }
                    (value->as.array).items = p0;
                    (value->as.array).len = n0;
                }
            }
            break;
        case 2u:
            value->kind = UNI_DATA_VALUE_RECORD;
            {
                uint32_t n0 = mpr_array_header(r);
                uni_data_value_field *p0 = (uni_data_value_field *)mpa_alloc(a, sizeof(uni_data_value_field) * (size_t)n0);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    for (uint32_t i0 = 0; i0 < n0; i0++) {
                        uni_data_value_field_decode(r, a, &(p0[i0]));
                    }
                    (value->as.record).items = p0;
                    (value->as.record).len = n0;
                }
            }
            break;
        case 3u:
            value->kind = UNI_DATA_VALUE_BINARY;
            {
                uint32_t n0 = mpr_array_header(r);
                uint8_t *p0 = (uint8_t *)mpa_alloc(a, n0);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    for (uint32_t i0 = 0; i0 < n0; i0++) {
                        p0[i0] = (uint8_t)mpr_u64(r);
                    }
                    (value->as.binary).data = p0;
                    (value->as.binary).len = n0;
                }
            }
            break;
        default:
            mpr_fail(r);
            return -1;
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one variant into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_data_value *uni_data_value_decode_new(mp_reader *r, mp_arena *a) {
    uni_data_value *p = (uni_data_value *)mpa_alloc(a, sizeof(uni_data_value));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_data_value_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

/* Encode `value` as a MessagePack map keyed by the 1-based field numbers
 * (WIT declaration order); `option` fields are omitted when null (proto3
 * presence semantics). Encode only borrows `value`; failures are sticky in
 * `w` (check `mpw_ok`). */
MP_INLINE void uni_data_value_field_encode(mp_writer *w, const uni_data_value_field *value) {
    mpw_map_header(w, 2u);
    mpw_u64(w, 1u);
    mpw_str(w, (value->field_name).data, (value->field_name).len);
    mpw_u64(w, 2u);
    uni_data_value_encode(w, &(value->field_value));
}

/* Decode one record into `out`, borrowing nothing from the input: every
 * string, blob, array and boxed value is copied into `a`. Lenient: unknown
 * keys are skipped and missing fields keep their zero default (absent
 * `option` fields decode as null). 0 on success, -1 (with the reader's
 * sticky error set) on malformed input or arena exhaustion. */
MP_INLINE int uni_data_value_field_decode(mp_reader *r, mp_arena *a, uni_data_value_field *out) {
    (void)a;
    memset(out, 0, sizeof(*out));
    {
        uint32_t count = mpr_map_header(r);
        for (uint32_t i = 0; i < count && mpr_ok(r); i++) {
            if (mpr_next_is_integer(r)) {
                uint64_t key = mpr_u64(r);
                if (key == 1u) {
                    {
                        uint32_t n0 = 0;
                        const char *s0 = mpr_str(r, &n0);
                        char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            memcpy(p0, s0, n0);
                            p0[n0] = '\0';
                            (out->field_name).data = p0;
                            (out->field_name).len = n0;
                        }
                    }
                } else if (key == 2u) {
                    uni_data_value_decode(r, a, &(out->field_value));
                } else {
                    mpr_skip(r);
                }
            } else {
                mpr_skip(r);
                mpr_skip(r);
            }
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one record into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_data_value_field *uni_data_value_field_decode_new(mp_reader *r, mp_arena *a) {
    uni_data_value_field *p = (uni_data_value_field *)mpa_alloc(a, sizeof(uni_data_value_field));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_data_value_field_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

#ifdef __cplusplus
}
#endif
#include "mududb/types/UniScalarValue.h"

#endif /* MUDUD_TYPES_UNI_DATA_VALUE_H */