// Generated by mudu_gen. Do not edit manually.
/*
 * mududb C binding message types/codecs (mgen message -l c
 * --with-func-codec). Self-contained header: `MP_INLINE` functions only
 * (`static inline` in C, `inline` in C++), no mutable state. Ownership
 * contract: encode borrows its inputs; decode copies every variable-length
 * value into the caller's `mp_arena`; the writer owns its buffer
 * (`mpw_free`). See the package readme.md.
 */
#ifndef MUDUD_TYPES_UNI_RECORD_TYPE_H
#define MUDUD_TYPES_UNI_RECORD_TYPE_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "mududb/codec/mpack.h"
#include "mududb/types/UniDataType.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef MUDUD_FWD_UNI_FIELD_ATTR
#define MUDUD_FWD_UNI_FIELD_ATTR
typedef struct uni_field_attr uni_field_attr;
MP_INLINE void uni_field_attr_encode(mp_writer *w, const uni_field_attr *value);
MP_INLINE int uni_field_attr_decode(mp_reader *r, mp_arena *a, uni_field_attr *out);
MP_INLINE uni_field_attr *uni_field_attr_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_FIELD_ATTR */
#ifndef MUDUD_FWD_UNI_RECORD_FIELD
#define MUDUD_FWD_UNI_RECORD_FIELD
typedef struct uni_record_field uni_record_field;
MP_INLINE void uni_record_field_encode(mp_writer *w, const uni_record_field *value);
MP_INLINE int uni_record_field_decode(mp_reader *r, mp_arena *a, uni_record_field *out);
MP_INLINE uni_record_field *uni_record_field_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_RECORD_FIELD */
#ifndef MUDUD_FWD_UNI_RECORD_TYPE
#define MUDUD_FWD_UNI_RECORD_TYPE
typedef struct uni_record_type uni_record_type;
MP_INLINE void uni_record_type_encode(mp_writer *w, const uni_record_type *value);
MP_INLINE int uni_record_type_decode(mp_reader *r, mp_arena *a, uni_record_type *out);
MP_INLINE uni_record_type *uni_record_type_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_RECORD_TYPE */

struct uni_field_attr {
    mp_str attr_name;
    mp_str attr_value;
};

typedef struct { uni_field_attr *items; uint32_t len; } uni_record_field_field_attrs_list;
struct uni_record_field {
    mp_str field_name;
    uni_data_type field_type;
    uni_record_field_field_attrs_list field_attrs;
};

typedef struct { uni_record_field *items; uint32_t len; } uni_record_type_record_fields_list;
struct uni_record_type {
    mp_str record_name;
    uni_record_type_record_fields_list record_fields;
};

/* Encode `value` as a MessagePack map keyed by the 1-based field numbers
 * (WIT declaration order); `option` fields are omitted when null (proto3
 * presence semantics). Encode only borrows `value`; failures are sticky in
 * `w` (check `mpw_ok`). */
MP_INLINE void uni_field_attr_encode(mp_writer *w, const uni_field_attr *value) {
    mpw_map_header(w, 2u);
    mpw_u64(w, 1u);
    mpw_str(w, (value->attr_name).data, (value->attr_name).len);
    mpw_u64(w, 2u);
    mpw_str(w, (value->attr_value).data, (value->attr_value).len);
}

/* Decode one record into `out`, borrowing nothing from the input: every
 * string, blob, array and boxed value is copied into `a`. Lenient: unknown
 * keys are skipped and missing fields keep their zero default (absent
 * `option` fields decode as null). 0 on success, -1 (with the reader's
 * sticky error set) on malformed input or arena exhaustion. */
MP_INLINE int uni_field_attr_decode(mp_reader *r, mp_arena *a, uni_field_attr *out) {
    (void)a;
    memset(out, 0, sizeof(*out));
    {
        uint32_t count = mpr_map_header(r);
        for (uint32_t i = 0; i < count && mpr_ok(r); i++) {
            if (mpr_next_is_integer(r)) {
                uint64_t key = mpr_u64(r);
                if (key == 1u) {
                    {
                        uint32_t n0 = 0;
                        const char *s0 = mpr_str(r, &n0);
                        char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            memcpy(p0, s0, n0);
                            p0[n0] = '\0';
                            (out->attr_name).data = p0;
                            (out->attr_name).len = n0;
                        }
                    }
                } else if (key == 2u) {
                    {
                        uint32_t n0 = 0;
                        const char *s0 = mpr_str(r, &n0);
                        char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            memcpy(p0, s0, n0);
                            p0[n0] = '\0';
                            (out->attr_value).data = p0;
                            (out->attr_value).len = n0;
                        }
                    }
                } else {
                    mpr_skip(r);
                }
            } else {
                mpr_skip(r);
                mpr_skip(r);
            }
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one record into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_field_attr *uni_field_attr_decode_new(mp_reader *r, mp_arena *a) {
    uni_field_attr *p = (uni_field_attr *)mpa_alloc(a, sizeof(uni_field_attr));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_field_attr_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

/* Encode `value` as a MessagePack map keyed by the 1-based field numbers
 * (WIT declaration order); `option` fields are omitted when null (proto3
 * presence semantics). Encode only borrows `value`; failures are sticky in
 * `w` (check `mpw_ok`). */
MP_INLINE void uni_record_field_encode(mp_writer *w, const uni_record_field *value) {
    mpw_map_header(w, 3u);
    mpw_u64(w, 1u);
    mpw_str(w, (value->field_name).data, (value->field_name).len);
    mpw_u64(w, 2u);
    uni_data_type_encode(w, &(value->field_type));
    mpw_u64(w, 3u);
    mpw_array_header(w, (value->field_attrs).len);
    for (uint32_t i0 = 0; i0 < (value->field_attrs).len; i0++) {
        uni_field_attr_encode(w, &((value->field_attrs).items[i0]));
    }
}

/* Decode one record into `out`, borrowing nothing from the input: every
 * string, blob, array and boxed value is copied into `a`. Lenient: unknown
 * keys are skipped and missing fields keep their zero default (absent
 * `option` fields decode as null). 0 on success, -1 (with the reader's
 * sticky error set) on malformed input or arena exhaustion. */
MP_INLINE int uni_record_field_decode(mp_reader *r, mp_arena *a, uni_record_field *out) {
    (void)a;
    memset(out, 0, sizeof(*out));
    {
        uint32_t count = mpr_map_header(r);
        for (uint32_t i = 0; i < count && mpr_ok(r); i++) {
            if (mpr_next_is_integer(r)) {
                uint64_t key = mpr_u64(r);
                if (key == 1u) {
                    {
                        uint32_t n0 = 0;
                        const char *s0 = mpr_str(r, &n0);
                        char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            memcpy(p0, s0, n0);
                            p0[n0] = '\0';
                            (out->field_name).data = p0;
                            (out->field_name).len = n0;
                        }
                    }
                } else if (key == 2u) {
                    uni_data_type_decode(r, a, &(out->field_type));
                } else if (key == 3u) {
                    {
                        uint32_t n0 = mpr_array_header(r);
                        uni_field_attr *p0 = (uni_field_attr *)mpa_alloc(a, sizeof(uni_field_attr) * (size_t)n0);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            for (uint32_t i0 = 0; i0 < n0; i0++) {
                                uni_field_attr_decode(r, a, &(p0[i0]));
                            }
                            (out->field_attrs).items = p0;
                            (out->field_attrs).len = n0;
                        }
                    }
                } else {
                    mpr_skip(r);
                }
            } else {
                mpr_skip(r);
                mpr_skip(r);
            }
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one record into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_record_field *uni_record_field_decode_new(mp_reader *r, mp_arena *a) {
    uni_record_field *p = (uni_record_field *)mpa_alloc(a, sizeof(uni_record_field));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_record_field_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

/* Encode `value` as a MessagePack map keyed by the 1-based field numbers
 * (WIT declaration order); `option` fields are omitted when null (proto3
 * presence semantics). Encode only borrows `value`; failures are sticky in
 * `w` (check `mpw_ok`). */
MP_INLINE void uni_record_type_encode(mp_writer *w, const uni_record_type *value) {
    mpw_map_header(w, 2u);
    mpw_u64(w, 1u);
    mpw_str(w, (value->record_name).data, (value->record_name).len);
    mpw_u64(w, 2u);
    mpw_array_header(w, (value->record_fields).len);
    for (uint32_t i0 = 0; i0 < (value->record_fields).len; i0++) {
        uni_record_field_encode(w, &((value->record_fields).items[i0]));
    }
}

/* Decode one record into `out`, borrowing nothing from the input: every
 * string, blob, array and boxed value is copied into `a`. Lenient: unknown
 * keys are skipped and missing fields keep their zero default (absent
 * `option` fields decode as null). 0 on success, -1 (with the reader's
 * sticky error set) on malformed input or arena exhaustion. */
MP_INLINE int uni_record_type_decode(mp_reader *r, mp_arena *a, uni_record_type *out) {
    (void)a;
    memset(out, 0, sizeof(*out));
    {
        uint32_t count = mpr_map_header(r);
        for (uint32_t i = 0; i < count && mpr_ok(r); i++) {
            if (mpr_next_is_integer(r)) {
                uint64_t key = mpr_u64(r);
                if (key == 1u) {
                    {
                        uint32_t n0 = 0;
                        const char *s0 = mpr_str(r, &n0);
                        char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            memcpy(p0, s0, n0);
                            p0[n0] = '\0';
                            (out->record_name).data = p0;
                            (out->record_name).len = n0;
                        }
                    }
                } else if (key == 2u) {
                    {
                        uint32_t n0 = mpr_array_header(r);
                        uni_record_field *p0 = (uni_record_field *)mpa_alloc(a, sizeof(uni_record_field) * (size_t)n0);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            for (uint32_t i0 = 0; i0 < n0; i0++) {
                                uni_record_field_decode(r, a, &(p0[i0]));
                            }
                            (out->record_fields).items = p0;
                            (out->record_fields).len = n0;
                        }
                    }
                } else {
                    mpr_skip(r);
                }
            } else {
                mpr_skip(r);
                mpr_skip(r);
            }
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one record into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_record_type *uni_record_type_decode_new(mp_reader *r, mp_arena *a) {
    uni_record_type *p = (uni_record_type *)mpa_alloc(a, sizeof(uni_record_type));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_record_type_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

#ifdef __cplusplus
}
#endif

#endif /* MUDUD_TYPES_UNI_RECORD_TYPE_H */