// Generated by mudu_gen. Do not edit manually.
/*
 * mududb C binding message types/codecs (mgen message -l c
 * --with-func-codec). Self-contained header: `MP_INLINE` functions only
 * (`static inline` in C, `inline` in C++), no mutable state. Ownership
 * contract: encode borrows its inputs; decode copies every variable-length
 * value into the caller's `mp_arena`; the writer owns its buffer
 * (`mpw_free`). See the package readme.md.
 */
#ifndef MUDUD_TYPES_UNI_SCALAR_H
#define MUDUD_TYPES_UNI_SCALAR_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "mududb/codec/mpack.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    UNI_SCALAR_BOOL = 0u,
    UNI_SCALAR_U8 = 1u,
    UNI_SCALAR_I8 = 2u,
    UNI_SCALAR_U16 = 3u,
    UNI_SCALAR_I16 = 4u,
    UNI_SCALAR_U32 = 5u,
    UNI_SCALAR_I32 = 6u,
    UNI_SCALAR_U64 = 7u,
    UNI_SCALAR_U128 = 8u,
    UNI_SCALAR_I64 = 9u,
    UNI_SCALAR_I128 = 10u,
    UNI_SCALAR_F32 = 11u,
    UNI_SCALAR_F64 = 12u,
    UNI_SCALAR_CHAR = 13u,
    UNI_SCALAR_STRING = 14u,
    UNI_SCALAR_BLOB = 15u,
    UNI_SCALAR_NUMERIC = 16u,
    UNI_SCALAR_DATE = 17u,
    UNI_SCALAR_TIME = 18u,
    UNI_SCALAR_TIMESTAMP = 19u,
    UNI_SCALAR_TIMESTAMP_TZ = 20u,
} uni_scalar;

/* Encode `value` as its case number (u64). */
MP_INLINE void uni_scalar_encode(mp_writer *w, const uni_scalar *value) {
    mpw_u64(w, (uint64_t)*value);
}

/* Decode one case number into `out`; lenient (no range check), matching the
 * host and the other bindings. Result contract of the generated decoders. */
MP_INLINE int uni_scalar_decode(mp_reader *r, mp_arena *a, uni_scalar *out) {
    (void)a;
    *out = (uni_scalar)mpr_u64(r);
    return mpr_ok(r) ? 0 : -1;
}

#ifdef __cplusplus
}
#endif

#endif /* MUDUD_TYPES_UNI_SCALAR_H */