// Generated by mudu_gen. Do not edit manually.
/*
 * mududb C binding message types/codecs (mgen message -l c
 * --with-func-codec). Self-contained header: `MP_INLINE` functions only
 * (`static inline` in C, `inline` in C++), no mutable state. Ownership
 * contract: encode borrows its inputs; decode copies every variable-length
 * value into the caller's `mp_arena`; the writer owns its buffer
 * (`mpw_free`). See the package readme.md.
 */
#ifndef MUDUD_TYPES_UNI_SCALAR_VALUE_H
#define MUDUD_TYPES_UNI_SCALAR_VALUE_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "mududb/codec/mpack.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef MUDUD_FWD_UNI_SCALAR_VALUE
#define MUDUD_FWD_UNI_SCALAR_VALUE
typedef struct uni_scalar_value uni_scalar_value;
MP_INLINE void uni_scalar_value_encode(mp_writer *w, const uni_scalar_value *value);
MP_INLINE int uni_scalar_value_decode(mp_reader *r, mp_arena *a, uni_scalar_value *out);
MP_INLINE uni_scalar_value *uni_scalar_value_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_SCALAR_VALUE */

typedef enum {
    UNI_SCALAR_VALUE_BOOL = 0u,
    UNI_SCALAR_VALUE_U8 = 1u,
    UNI_SCALAR_VALUE_I8 = 2u,
    UNI_SCALAR_VALUE_U16 = 3u,
    UNI_SCALAR_VALUE_I16 = 4u,
    UNI_SCALAR_VALUE_U32 = 5u,
    UNI_SCALAR_VALUE_I32 = 6u,
    UNI_SCALAR_VALUE_U64 = 7u,
    UNI_SCALAR_VALUE_U128 = 8u,
    UNI_SCALAR_VALUE_I64 = 9u,
    UNI_SCALAR_VALUE_I128 = 10u,
    UNI_SCALAR_VALUE_F32 = 11u,
    UNI_SCALAR_VALUE_F64 = 12u,
    UNI_SCALAR_VALUE_CHAR = 13u,
    UNI_SCALAR_VALUE_STRING = 14u,
    UNI_SCALAR_VALUE_BLOB = 15u,
    UNI_SCALAR_VALUE_NUMERIC = 16u,
    UNI_SCALAR_VALUE_DATE = 17u,
    UNI_SCALAR_VALUE_TIME = 18u,
    UNI_SCALAR_VALUE_TIMESTAMP = 19u,
    UNI_SCALAR_VALUE_TIMESTAMP_TZ = 20u,
    UNI_SCALAR_VALUE_NULL = 21u,
} uni_scalar_value_kind;

struct uni_scalar_value {
    uni_scalar_value_kind kind;
    union {
        bool bool_;
        uint8_t u8;
        int8_t i8;
        uint16_t u16;
        int16_t i16;
        uint32_t u32;
        int32_t i32;
        uint64_t u64;
        mp_bin u128;
        int64_t i64;
        mp_bin i128;
        float f32;
        double f64;
        char char_;
        mp_str string;
        mp_bin blob;
        mp_str numeric;
        mp_str date;
        mp_str time;
        mp_str timestamp;
        mp_str timestamp_tz;
    } as;
};

/* Encode `value` as a `[tag, payload]` 2-array; payload-less cases carry a
 * `0u8` placeholder (NOT nil), matching the Rust host's variant serde. An
 * unknown kind flags `w` (check `mpw_ok`) instead of emitting a corrupt
 * value. */
MP_INLINE void uni_scalar_value_encode(mp_writer *w, const uni_scalar_value *value) {
    mpw_array_header(w, 2u);
    mpw_u64(w, (uint64_t)value->kind);
    switch (value->kind) {
    case UNI_SCALAR_VALUE_BOOL:
        mpw_bool(w, value->as.bool_);
        break;
    case UNI_SCALAR_VALUE_U8:
        mpw_u64(w, (uint64_t)(value->as.u8));
        break;
    case UNI_SCALAR_VALUE_I8:
        mpw_i64(w, (int64_t)(value->as.i8));
        break;
    case UNI_SCALAR_VALUE_U16:
        mpw_u64(w, (uint64_t)(value->as.u16));
        break;
    case UNI_SCALAR_VALUE_I16:
        mpw_i64(w, (int64_t)(value->as.i16));
        break;
    case UNI_SCALAR_VALUE_U32:
        mpw_u64(w, (uint64_t)(value->as.u32));
        break;
    case UNI_SCALAR_VALUE_I32:
        mpw_i64(w, (int64_t)(value->as.i32));
        break;
    case UNI_SCALAR_VALUE_U64:
        mpw_u64(w, (uint64_t)(value->as.u64));
        break;
    case UNI_SCALAR_VALUE_U128:
        mpw_array_header(w, (value->as.u128).len);
        for (uint32_t i0 = 0; i0 < (value->as.u128).len; i0++) {
            mpw_u64(w, (value->as.u128).data[i0]);
        }
        break;
    case UNI_SCALAR_VALUE_I64:
        mpw_i64(w, (int64_t)(value->as.i64));
        break;
    case UNI_SCALAR_VALUE_I128:
        mpw_array_header(w, (value->as.i128).len);
        for (uint32_t i0 = 0; i0 < (value->as.i128).len; i0++) {
            mpw_u64(w, (value->as.i128).data[i0]);
        }
        break;
    case UNI_SCALAR_VALUE_F32:
        mpw_f32(w, value->as.f32);
        break;
    case UNI_SCALAR_VALUE_F64:
        mpw_f64(w, value->as.f64);
        break;
    case UNI_SCALAR_VALUE_CHAR:
        mpw_str(w, &(value->as.char_), 1u);
        break;
    case UNI_SCALAR_VALUE_STRING:
        mpw_str(w, (value->as.string).data, (value->as.string).len);
        break;
    case UNI_SCALAR_VALUE_BLOB:
        mpw_array_header(w, (value->as.blob).len);
        for (uint32_t i0 = 0; i0 < (value->as.blob).len; i0++) {
            mpw_u64(w, (value->as.blob).data[i0]);
        }
        break;
    case UNI_SCALAR_VALUE_NUMERIC:
        mpw_str(w, (value->as.numeric).data, (value->as.numeric).len);
        break;
    case UNI_SCALAR_VALUE_DATE:
        mpw_str(w, (value->as.date).data, (value->as.date).len);
        break;
    case UNI_SCALAR_VALUE_TIME:
        mpw_str(w, (value->as.time).data, (value->as.time).len);
        break;
    case UNI_SCALAR_VALUE_TIMESTAMP:
        mpw_str(w, (value->as.timestamp).data, (value->as.timestamp).len);
        break;
    case UNI_SCALAR_VALUE_TIMESTAMP_TZ:
        mpw_str(w, (value->as.timestamp_tz).data, (value->as.timestamp_tz).len);
        break;
    case UNI_SCALAR_VALUE_NULL:
        /* payload-less case: the `0u8` placeholder (NOT nil), matching
         * the Rust host's variant serde. */
        mpw_u64(w, 0u);
        break;
    default:
        /* unknown kind: flag the writer instead of emitting a corrupt value */
        mpw_fail(w);
        break;
    }
}

/* Decode one variant into `value` (arena contract of the generated
 * decoders). 0 on success, -1 (sticky error set) on a malformed shape or an
 * unknown tag. */
MP_INLINE int uni_scalar_value_decode(mp_reader *r, mp_arena *a, uni_scalar_value *value) {
    (void)a;
    memset(value, 0, sizeof(*value));
    if (mpr_array_header(r) != 2u) {
        mpr_fail(r);
        return -1;
    }
    {
        uint64_t tag = mpr_u64(r);
        switch (tag) {
        case 0u:
            value->kind = UNI_SCALAR_VALUE_BOOL;
            value->as.bool_ = mpr_bool(r);
            break;
        case 1u:
            value->kind = UNI_SCALAR_VALUE_U8;
            value->as.u8 = (uint8_t)mpr_u64(r);
            break;
        case 2u:
            value->kind = UNI_SCALAR_VALUE_I8;
            value->as.i8 = (int8_t)mpr_i64(r);
            break;
        case 3u:
            value->kind = UNI_SCALAR_VALUE_U16;
            value->as.u16 = (uint16_t)mpr_u64(r);
            break;
        case 4u:
            value->kind = UNI_SCALAR_VALUE_I16;
            value->as.i16 = (int16_t)mpr_i64(r);
            break;
        case 5u:
            value->kind = UNI_SCALAR_VALUE_U32;
            value->as.u32 = (uint32_t)mpr_u64(r);
            break;
        case 6u:
            value->kind = UNI_SCALAR_VALUE_I32;
            value->as.i32 = (int32_t)mpr_i64(r);
            break;
        case 7u:
            value->kind = UNI_SCALAR_VALUE_U64;
            value->as.u64 = mpr_u64(r);
            break;
        case 8u:
            value->kind = UNI_SCALAR_VALUE_U128;
            {
                uint32_t n0 = mpr_array_header(r);
                uint8_t *p0 = (uint8_t *)mpa_alloc(a, n0);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    for (uint32_t i0 = 0; i0 < n0; i0++) {
                        p0[i0] = (uint8_t)mpr_u64(r);
                    }
                    (value->as.u128).data = p0;
                    (value->as.u128).len = n0;
                }
            }
            break;
        case 9u:
            value->kind = UNI_SCALAR_VALUE_I64;
            value->as.i64 = mpr_i64(r);
            break;
        case 10u:
            value->kind = UNI_SCALAR_VALUE_I128;
            {
                uint32_t n0 = mpr_array_header(r);
                uint8_t *p0 = (uint8_t *)mpa_alloc(a, n0);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    for (uint32_t i0 = 0; i0 < n0; i0++) {
                        p0[i0] = (uint8_t)mpr_u64(r);
                    }
                    (value->as.i128).data = p0;
                    (value->as.i128).len = n0;
                }
            }
            break;
        case 11u:
            value->kind = UNI_SCALAR_VALUE_F32;
            value->as.f32 = mpr_f32(r);
            break;
        case 12u:
            value->kind = UNI_SCALAR_VALUE_F64;
            value->as.f64 = mpr_f64(r);
            break;
        case 13u:
            value->kind = UNI_SCALAR_VALUE_CHAR;
            {
                uint32_t n0 = 0;
                const char *s0 = mpr_str(r, &n0);
                value->as.char_ = n0 > 0 ? s0[0] : '\0';
            }
            break;
        case 14u:
            value->kind = UNI_SCALAR_VALUE_STRING;
            {
                uint32_t n0 = 0;
                const char *s0 = mpr_str(r, &n0);
                char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    memcpy(p0, s0, n0);
                    p0[n0] = '\0';
                    (value->as.string).data = p0;
                    (value->as.string).len = n0;
                }
            }
            break;
        case 15u:
            value->kind = UNI_SCALAR_VALUE_BLOB;
            {
                uint32_t n0 = mpr_array_header(r);
                uint8_t *p0 = (uint8_t *)mpa_alloc(a, n0);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    for (uint32_t i0 = 0; i0 < n0; i0++) {
                        p0[i0] = (uint8_t)mpr_u64(r);
                    }
                    (value->as.blob).data = p0;
                    (value->as.blob).len = n0;
                }
            }
            break;
        case 16u:
            value->kind = UNI_SCALAR_VALUE_NUMERIC;
            {
                uint32_t n0 = 0;
                const char *s0 = mpr_str(r, &n0);
                char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    memcpy(p0, s0, n0);
                    p0[n0] = '\0';
                    (value->as.numeric).data = p0;
                    (value->as.numeric).len = n0;
                }
            }
            break;
        case 17u:
            value->kind = UNI_SCALAR_VALUE_DATE;
            {
                uint32_t n0 = 0;
                const char *s0 = mpr_str(r, &n0);
                char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    memcpy(p0, s0, n0);
                    p0[n0] = '\0';
                    (value->as.date).data = p0;
                    (value->as.date).len = n0;
                }
            }
            break;
        case 18u:
            value->kind = UNI_SCALAR_VALUE_TIME;
            {
                uint32_t n0 = 0;
                const char *s0 = mpr_str(r, &n0);
                char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    memcpy(p0, s0, n0);
                    p0[n0] = '\0';
                    (value->as.time).data = p0;
                    (value->as.time).len = n0;
                }
            }
            break;
        case 19u:
            value->kind = UNI_SCALAR_VALUE_TIMESTAMP;
            {
                uint32_t n0 = 0;
                const char *s0 = mpr_str(r, &n0);
                char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    memcpy(p0, s0, n0);
                    p0[n0] = '\0';
                    (value->as.timestamp).data = p0;
                    (value->as.timestamp).len = n0;
                }
            }
            break;
        case 20u:
            value->kind = UNI_SCALAR_VALUE_TIMESTAMP_TZ;
            {
                uint32_t n0 = 0;
                const char *s0 = mpr_str(r, &n0);
                char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                if (p0 == 0) {
                    mpr_fail(r);
                } else {
                    memcpy(p0, s0, n0);
                    p0[n0] = '\0';
                    (value->as.timestamp_tz).data = p0;
                    (value->as.timestamp_tz).len = n0;
                }
            }
            break;
        case 21u:
            value->kind = UNI_SCALAR_VALUE_NULL;
            /* consume the `0u8` placeholder */
            (void)mpr_u64(r);
            break;
        default:
            mpr_fail(r);
            return -1;
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one variant into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_scalar_value *uni_scalar_value_decode_new(mp_reader *r, mp_arena *a) {
    uni_scalar_value *p = (uni_scalar_value *)mpa_alloc(a, sizeof(uni_scalar_value));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_scalar_value_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

#ifdef __cplusplus
}
#endif

#endif /* MUDUD_TYPES_UNI_SCALAR_VALUE_H */