// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HotspotSeedArgs {
    pub warehouse_id: i32,
    pub hot_rows: i32,
    pub op_index: u64,
}

impl From<HotspotSeedArgs> for super::Reducer {
    fn from(args: HotspotSeedArgs) -> Self {
        Self::HotspotSeed {
            warehouse_id: args.warehouse_id,
            hot_rows: args.hot_rows,
            op_index: args.op_index,
        }
    }
}

impl __sdk::InModule for HotspotSeedArgs {
    type Module = super::RemoteModule;
}

pub struct HotspotSeedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `hotspot_seed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait hotspot_seed {
    /// Request that the remote module invoke the reducer `hotspot_seed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_hotspot_seed`] callbacks.
    fn hotspot_seed(&self, warehouse_id: i32, hot_rows: i32, op_index: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `hotspot_seed`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`HotspotSeedCallbackId`] can be passed to [`Self::remove_on_hotspot_seed`]
    /// to cancel the callback.
    fn on_hotspot_seed(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &u64) + Send + 'static,
    ) -> HotspotSeedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_hotspot_seed`],
    /// causing it not to run in the future.
    fn remove_on_hotspot_seed(&self, callback: HotspotSeedCallbackId);
}

impl hotspot_seed for super::RemoteReducers {
    fn hotspot_seed(&self, warehouse_id: i32, hot_rows: i32, op_index: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "hotspot_seed",
            HotspotSeedArgs {
                warehouse_id,
                hot_rows,
                op_index,
            },
        )
    }
    fn on_hotspot_seed(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &u64) + Send + 'static,
    ) -> HotspotSeedCallbackId {
        HotspotSeedCallbackId(self.imp.on_reducer(
            "hotspot_seed",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::HotspotSeed {
                                    warehouse_id,
                                    hot_rows,
                                    op_index,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, warehouse_id, hot_rows, op_index)
            }),
        ))
    }
    fn remove_on_hotspot_seed(&self, callback: HotspotSeedCallbackId) {
        self.imp.remove_on_reducer("hotspot_seed", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `hotspot_seed`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_hotspot_seed {
    /// Set the call-reducer flags for the reducer `hotspot_seed` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn hotspot_seed(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_hotspot_seed for super::SetReducerFlags {
    fn hotspot_seed(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("hotspot_seed", flags);
    }
}
