// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_type::Item;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item`.
///
/// Obtain a handle from the [`ItemTableAccess::item`] method on [`super::RemoteTables`],
/// like `ctx.db.item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item().on_insert(...)`.
pub struct ItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<Item>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemTableHandle`], which mediates access to the table `item`.
    fn item(&self) -> ItemTableHandle<'_>;
}

impl ItemTableAccess for super::RemoteTables {
    fn item(&self) -> ItemTableHandle<'_> {
        ItemTableHandle {
            imp: self.imp.get_table::<Item>("item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ItemInsertCallbackId(__sdk::CallbackId);
pub struct ItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ItemTableHandle<'ctx> {
    type Row = Item;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Item> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemInsertCallbackId {
        ItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDeleteCallbackId {
        ItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Item>("item");
    _table.add_unique_constraint::<i32>("i_id", |row| &row.i_id);
}
pub struct ItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemTableHandle<'ctx> {
    type UpdateCallbackId = ItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemUpdateCallbackId {
        ItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Item>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Item>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `i_id` unique index on the table `item`,
/// which allows point queries on the field of the same name
/// via the [`ItemIIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item().i_id().find(...)`.
pub struct ItemIIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Item, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemTableHandle<'ctx> {
    /// Get a handle on the `i_id` unique index on the table `item`.
    pub fn i_id(&self) -> ItemIIdUnique<'ctx> {
        ItemIIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("i_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ItemIIdUnique<'ctx> {
    /// Find the subscribed row whose `i_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<Item> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Item`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait itemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Item`.
    fn item(&self) -> __sdk::__query_builder::Table<Item>;
}

impl itemQueryTableAccess for __sdk::QueryTableAccessor {
    fn item(&self) -> __sdk::__query_builder::Table<Item> {
        __sdk::__query_builder::Table::new("item")
    }
}
