// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OrderLine {
    pub pk: u64,
    pub ol_o_id: i32,
    pub ol_d_id: i32,
    pub ol_w_id: i32,
    pub ol_number: i32,
    pub ol_i_id: i32,
    pub ol_supply_w_id: i32,
    pub ol_delivery_d: String,
    pub ol_quantity: i32,
    pub ol_amount: i32,
}

impl __sdk::InModule for OrderLine {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OrderLine`.
///
/// Provides typed access to columns for query building.
pub struct OrderLineCols {
    pub pk: __sdk::__query_builder::Col<OrderLine, u64>,
    pub ol_o_id: __sdk::__query_builder::Col<OrderLine, i32>,
    pub ol_d_id: __sdk::__query_builder::Col<OrderLine, i32>,
    pub ol_w_id: __sdk::__query_builder::Col<OrderLine, i32>,
    pub ol_number: __sdk::__query_builder::Col<OrderLine, i32>,
    pub ol_i_id: __sdk::__query_builder::Col<OrderLine, i32>,
    pub ol_supply_w_id: __sdk::__query_builder::Col<OrderLine, i32>,
    pub ol_delivery_d: __sdk::__query_builder::Col<OrderLine, String>,
    pub ol_quantity: __sdk::__query_builder::Col<OrderLine, i32>,
    pub ol_amount: __sdk::__query_builder::Col<OrderLine, i32>,
}

impl __sdk::__query_builder::HasCols for OrderLine {
    type Cols = OrderLineCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OrderLineCols {
            pk: __sdk::__query_builder::Col::new(table_name, "pk"),
            ol_o_id: __sdk::__query_builder::Col::new(table_name, "ol_o_id"),
            ol_d_id: __sdk::__query_builder::Col::new(table_name, "ol_d_id"),
            ol_w_id: __sdk::__query_builder::Col::new(table_name, "ol_w_id"),
            ol_number: __sdk::__query_builder::Col::new(table_name, "ol_number"),
            ol_i_id: __sdk::__query_builder::Col::new(table_name, "ol_i_id"),
            ol_supply_w_id: __sdk::__query_builder::Col::new(table_name, "ol_supply_w_id"),
            ol_delivery_d: __sdk::__query_builder::Col::new(table_name, "ol_delivery_d"),
            ol_quantity: __sdk::__query_builder::Col::new(table_name, "ol_quantity"),
            ol_amount: __sdk::__query_builder::Col::new(table_name, "ol_amount"),
        }
    }
}

/// Indexed column accessor struct for the table `OrderLine`.
///
/// Provides typed access to indexed columns for query building.
pub struct OrderLineIxCols {
    pub pk: __sdk::__query_builder::IxCol<OrderLine, u64>,
}

impl __sdk::__query_builder::HasIxCols for OrderLine {
    type IxCols = OrderLineIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OrderLineIxCols {
            pk: __sdk::__query_builder::IxCol::new(table_name, "pk"),
        }
    }
}
