// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeckillBuyArgs {
    pub item_id: i32,
    pub order_id: i32,
    pub user_id: i32,
    pub amount: i32,
    pub payload: String,
    pub op_index: u64,
}

impl From<SeckillBuyArgs> for super::Reducer {
    fn from(args: SeckillBuyArgs) -> Self {
        Self::SeckillBuy {
            item_id: args.item_id,
            order_id: args.order_id,
            user_id: args.user_id,
            amount: args.amount,
            payload: args.payload,
            op_index: args.op_index,
        }
    }
}

impl __sdk::InModule for SeckillBuyArgs {
    type Module = super::RemoteModule;
}

pub struct SeckillBuyCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seckill_buy`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seckill_buy {
    /// Request that the remote module invoke the reducer `seckill_buy` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_seckill_buy`] callbacks.
    fn seckill_buy(
        &self,
        item_id: i32,
        order_id: i32,
        user_id: i32,
        amount: i32,
        payload: String,
        op_index: u64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `seckill_buy`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SeckillBuyCallbackId`] can be passed to [`Self::remove_on_seckill_buy`]
    /// to cancel the callback.
    fn on_seckill_buy(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32, &i32, &String, &u64)
        + Send
        + 'static,
    ) -> SeckillBuyCallbackId;
    /// Cancel a callback previously registered by [`Self::on_seckill_buy`],
    /// causing it not to run in the future.
    fn remove_on_seckill_buy(&self, callback: SeckillBuyCallbackId);
}

impl seckill_buy for super::RemoteReducers {
    fn seckill_buy(
        &self,
        item_id: i32,
        order_id: i32,
        user_id: i32,
        amount: i32,
        payload: String,
        op_index: u64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "seckill_buy",
            SeckillBuyArgs {
                item_id,
                order_id,
                user_id,
                amount,
                payload,
                op_index,
            },
        )
    }
    fn on_seckill_buy(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32, &i32, &String, &u64)
        + Send
        + 'static,
    ) -> SeckillBuyCallbackId {
        SeckillBuyCallbackId(self.imp.on_reducer(
            "seckill_buy",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::SeckillBuy {
                                    item_id,
                                    order_id,
                                    user_id,
                                    amount,
                                    payload,
                                    op_index,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, item_id, order_id, user_id, amount, payload, op_index)
            }),
        ))
    }
    fn remove_on_seckill_buy(&self, callback: SeckillBuyCallbackId) {
        self.imp.remove_on_reducer("seckill_buy", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `seckill_buy`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_seckill_buy {
    /// Set the call-reducer flags for the reducer `seckill_buy` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn seckill_buy(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_seckill_buy for super::SetReducerFlags {
    fn seckill_buy(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("seckill_buy", flags);
    }
}
