// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stock_type::Stock;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stock`.
///
/// Obtain a handle from the [`StockTableAccess::stock`] method on [`super::RemoteTables`],
/// like `ctx.db.stock()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stock().on_insert(...)`.
pub struct StockTableHandle<'ctx> {
    imp: __sdk::TableHandle<Stock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stock`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StockTableHandle`], which mediates access to the table `stock`.
    fn stock(&self) -> StockTableHandle<'_>;
}

impl StockTableAccess for super::RemoteTables {
    fn stock(&self) -> StockTableHandle<'_> {
        StockTableHandle {
            imp: self.imp.get_table::<Stock>("stock"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StockInsertCallbackId(__sdk::CallbackId);
pub struct StockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StockTableHandle<'ctx> {
    type Row = Stock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Stock> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StockInsertCallbackId {
        StockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StockDeleteCallbackId {
        StockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Stock>("stock");
    _table.add_unique_constraint::<u64>("pk", |row| &row.pk);
}
pub struct StockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StockTableHandle<'ctx> {
    type UpdateCallbackId = StockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StockUpdateCallbackId {
        StockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Stock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Stock>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `pk` unique index on the table `stock`,
/// which allows point queries on the field of the same name
/// via the [`StockPkUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stock().pk().find(...)`.
pub struct StockPkUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Stock, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StockTableHandle<'ctx> {
    /// Get a handle on the `pk` unique index on the table `stock`.
    pub fn pk(&self) -> StockPkUnique<'ctx> {
        StockPkUnique {
            imp: self.imp.get_unique_constraint::<u64>("pk"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StockPkUnique<'ctx> {
    /// Find the subscribed row whose `pk` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Stock> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Stock`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait stockQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Stock`.
    fn stock(&self) -> __sdk::__query_builder::Table<Stock>;
}

impl stockQueryTableAccess for __sdk::QueryTableAccessor {
    fn stock(&self) -> __sdk::__query_builder::Table<Stock> {
        __sdk::__query_builder::Table::new("stock")
    }
}
