// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Stock {
    pub pk: u64,
    pub s_w_id: i32,
    pub s_i_id: i32,
    pub s_quantity: i32,
    pub s_ytd: i32,
    pub s_order_cnt: i32,
    pub s_remote_cnt: i32,
}

impl __sdk::InModule for Stock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Stock`.
///
/// Provides typed access to columns for query building.
pub struct StockCols {
    pub pk: __sdk::__query_builder::Col<Stock, u64>,
    pub s_w_id: __sdk::__query_builder::Col<Stock, i32>,
    pub s_i_id: __sdk::__query_builder::Col<Stock, i32>,
    pub s_quantity: __sdk::__query_builder::Col<Stock, i32>,
    pub s_ytd: __sdk::__query_builder::Col<Stock, i32>,
    pub s_order_cnt: __sdk::__query_builder::Col<Stock, i32>,
    pub s_remote_cnt: __sdk::__query_builder::Col<Stock, i32>,
}

impl __sdk::__query_builder::HasCols for Stock {
    type Cols = StockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StockCols {
            pk: __sdk::__query_builder::Col::new(table_name, "pk"),
            s_w_id: __sdk::__query_builder::Col::new(table_name, "s_w_id"),
            s_i_id: __sdk::__query_builder::Col::new(table_name, "s_i_id"),
            s_quantity: __sdk::__query_builder::Col::new(table_name, "s_quantity"),
            s_ytd: __sdk::__query_builder::Col::new(table_name, "s_ytd"),
            s_order_cnt: __sdk::__query_builder::Col::new(table_name, "s_order_cnt"),
            s_remote_cnt: __sdk::__query_builder::Col::new(table_name, "s_remote_cnt"),
        }
    }
}

/// Indexed column accessor struct for the table `Stock`.
///
/// Provides typed access to indexed columns for query building.
pub struct StockIxCols {
    pub pk: __sdk::__query_builder::IxCol<Stock, u64>,
    pub s_w_id: __sdk::__query_builder::IxCol<Stock, i32>,
}

impl __sdk::__query_builder::HasIxCols for Stock {
    type IxCols = StockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StockIxCols {
            pk: __sdk::__query_builder::IxCol::new(table_name, "pk"),
            s_w_id: __sdk::__query_builder::IxCol::new(table_name, "s_w_id"),
        }
    }
}
