// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TpccNewOrderArgs {
    pub warehouse_id: i32,
    pub district_id: i32,
    pub customer_id: i32,
    pub item_ids: Vec<i32>,
    pub supplier_warehouse_ids: Vec<i32>,
    pub quantities: Vec<i32>,
    pub op_index: u64,
}

impl From<TpccNewOrderArgs> for super::Reducer {
    fn from(args: TpccNewOrderArgs) -> Self {
        Self::TpccNewOrder {
            warehouse_id: args.warehouse_id,
            district_id: args.district_id,
            customer_id: args.customer_id,
            item_ids: args.item_ids,
            supplier_warehouse_ids: args.supplier_warehouse_ids,
            quantities: args.quantities,
            op_index: args.op_index,
        }
    }
}

impl __sdk::InModule for TpccNewOrderArgs {
    type Module = super::RemoteModule;
}

pub struct TpccNewOrderCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `tpcc_new_order`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait tpcc_new_order {
    /// Request that the remote module invoke the reducer `tpcc_new_order` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_tpcc_new_order`] callbacks.
    fn tpcc_new_order(
        &self,
        warehouse_id: i32,
        district_id: i32,
        customer_id: i32,
        item_ids: Vec<i32>,
        supplier_warehouse_ids: Vec<i32>,
        quantities: Vec<i32>,
        op_index: u64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `tpcc_new_order`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TpccNewOrderCallbackId`] can be passed to [`Self::remove_on_tpcc_new_order`]
    /// to cancel the callback.
    fn on_tpcc_new_order(
        &self,
        callback: impl FnMut(
            &super::ReducerEventContext,
            &i32,
            &i32,
            &i32,
            &Vec<i32>,
            &Vec<i32>,
            &Vec<i32>,
            &u64,
        ) + Send
        + 'static,
    ) -> TpccNewOrderCallbackId;
    /// Cancel a callback previously registered by [`Self::on_tpcc_new_order`],
    /// causing it not to run in the future.
    fn remove_on_tpcc_new_order(&self, callback: TpccNewOrderCallbackId);
}

impl tpcc_new_order for super::RemoteReducers {
    fn tpcc_new_order(
        &self,
        warehouse_id: i32,
        district_id: i32,
        customer_id: i32,
        item_ids: Vec<i32>,
        supplier_warehouse_ids: Vec<i32>,
        quantities: Vec<i32>,
        op_index: u64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "tpcc_new_order",
            TpccNewOrderArgs {
                warehouse_id,
                district_id,
                customer_id,
                item_ids,
                supplier_warehouse_ids,
                quantities,
                op_index,
            },
        )
    }
    fn on_tpcc_new_order(
        &self,
        mut callback: impl FnMut(
            &super::ReducerEventContext,
            &i32,
            &i32,
            &i32,
            &Vec<i32>,
            &Vec<i32>,
            &Vec<i32>,
            &u64,
        ) + Send
        + 'static,
    ) -> TpccNewOrderCallbackId {
        TpccNewOrderCallbackId(self.imp.on_reducer(
            "tpcc_new_order",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::TpccNewOrder {
                                    warehouse_id,
                                    district_id,
                                    customer_id,
                                    item_ids,
                                    supplier_warehouse_ids,
                                    quantities,
                                    op_index,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    warehouse_id,
                    district_id,
                    customer_id,
                    item_ids,
                    supplier_warehouse_ids,
                    quantities,
                    op_index,
                )
            }),
        ))
    }
    fn remove_on_tpcc_new_order(&self, callback: TpccNewOrderCallbackId) {
        self.imp.remove_on_reducer("tpcc_new_order", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `tpcc_new_order`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_tpcc_new_order {
    /// Set the call-reducer flags for the reducer `tpcc_new_order` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn tpcc_new_order(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_tpcc_new_order for super::SetReducerFlags {
    fn tpcc_new_order(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("tpcc_new_order", flags);
    }
}
