// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Warehouse {
    pub w_id: i32,
    pub w_name: String,
    pub w_tax: i32,
    pub w_ytd: i32,
}

impl __sdk::InModule for Warehouse {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Warehouse`.
///
/// Provides typed access to columns for query building.
pub struct WarehouseCols {
    pub w_id: __sdk::__query_builder::Col<Warehouse, i32>,
    pub w_name: __sdk::__query_builder::Col<Warehouse, String>,
    pub w_tax: __sdk::__query_builder::Col<Warehouse, i32>,
    pub w_ytd: __sdk::__query_builder::Col<Warehouse, i32>,
}

impl __sdk::__query_builder::HasCols for Warehouse {
    type Cols = WarehouseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WarehouseCols {
            w_id: __sdk::__query_builder::Col::new(table_name, "w_id"),
            w_name: __sdk::__query_builder::Col::new(table_name, "w_name"),
            w_tax: __sdk::__query_builder::Col::new(table_name, "w_tax"),
            w_ytd: __sdk::__query_builder::Col::new(table_name, "w_ytd"),
        }
    }
}

/// Indexed column accessor struct for the table `Warehouse`.
///
/// Provides typed access to indexed columns for query building.
pub struct WarehouseIxCols {
    pub w_id: __sdk::__query_builder::IxCol<Warehouse, i32>,
}

impl __sdk::__query_builder::HasIxCols for Warehouse {
    type IxCols = WarehouseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WarehouseIxCols {
            w_id: __sdk::__query_builder::IxCol::new(table_name, "w_id"),
        }
    }
}
