// Generated by `wit-bindgen` style compatibility shim.
#nullable enable

#if !NET9_0_OR_GREATER
namespace System.Runtime.InteropServices
{
    internal partial class WasmImportLinkageAttribute : global::System.Attribute {}
}
#endif
