#nullable enable

using System.Buffers;
using MessagePack;
using MessagePack.Formatters;
using mududb.types;

namespace mududb.codec;

/// <summary>
/// Hand-written bridge between the <c>uni-data-value</c> envelope a Mudu host
/// passes across the procedure byte pipe and the MessagePack wire shape the
/// mgen-generated C# record codecs (the <c>XxxFormatter</c> classes in the
/// files carrying the "Generated by mudu_gen" header) consume and produce.
///
/// A user-defined record argument travels as a <see cref="UniDataValueRecord"/>:
/// field entries in WIT declaration order, field names possibly empty (the
/// host drops them — positional semantics). <see cref="RecordFieldValues"/>
/// transcodes that envelope into the integer-keyed MessagePack map (1-based
/// field numbers) a generated <c>XxxFormatter.Deserialize</c> reads;
/// <see cref="RecordFromFieldValues"/> is the symmetric parse of the map a
/// generated <c>XxxFormatter.Serialize</c> writes, producing the record-case
/// envelope for a procedure return value (field names empty, like the host's).
///
/// The host's transactable scalar vocabulary (<c>uni_to</c>/<c>uni_from</c> in
/// mudu_binding) has no Bool/U8..U32/U64 cases: booleans cross as i32 (0/1 —
/// the desc declares them I32, the same family the procedure scalar table
/// uses), unsigned 8-32-bit integers as i32, and u64 as i64. On the encode
/// side this bridge emits exactly that vocabulary; on the decode side the
/// leniency lives in the generated decoders themselves (integer reads accept
/// any marker width, and bool fields accept the i32 0/1 form).
///
/// Decode stays lenient end to end: the generated formatters skip field
/// numbers they do not declare and default the missing ones. On encode, a
/// field the generated formatter omitted (a null WIT <c>option&lt;T&gt;</c>
/// field) is gap-filled with the Null scalar so declaration positions are
/// preserved (trailing omitted slots cannot be recovered and shrink the
/// record, which the host decodes leniently).
/// </summary>
public static class RecordBridge
{
    /// <summary>
    /// Unwraps a <see cref="UniDataValue"/> record-case envelope into the
    /// integer-keyed MessagePack map bytes (position i becomes key i+1, the
    /// WIT declaration order) a generated <c>XxxFormatter</c> consumes.
    /// Field values transcode to the plain MessagePack wire model recursively
    /// (nested records become nested integer-keyed maps, arrays become
    /// MessagePack arrays, byte strings become MessagePack bin, the Null
    /// scalar becomes nil). A non-record input is an error.
    /// </summary>
    public static byte[] RecordFieldValues(UniDataValue value)
    {
        if (value is not UniDataValueRecord record)
        {
            throw new global::System.IO.InvalidDataException(
                $"expected a UniDataValue record, got {value?.GetType()}");
        }

        var buffer = new ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteMapHeader(record.Inner.Count);
        for (var i = 0; i < record.Inner.Count; i++)
        {
            writer.Write((ulong)(i + 1));
            WriteDatumWire(record.Inner[i].FieldValue, ref writer);
        }

        writer.Flush();
        return buffer.WrittenMemory.ToArray();
    }

    /// <summary>
    /// Parses the integer-keyed MessagePack map bytes a generated
    /// <c>XxxFormatter.Serialize</c> produces and wraps the positional field
    /// values in the <see cref="UniDataValue"/> record-case envelope the host
    /// expects back. Field numbers are 1-based; a missing slot (an omitted
    /// option field) encodes as the Null scalar so declaration positions are
    /// preserved, and non-integer keys are skipped like the generated
    /// decoders do. Field values convert to the host's transactable scalar
    /// vocabulary (see the class summary): booleans become I32 (0/1),
    /// integers become I32 or I64 by range, and a u64 value beyond
    /// <c>long.MaxValue</c> is an error (the host cannot carry it).
    /// </summary>
    public static UniDataValue RecordFromFieldValues(ReadOnlyMemory<byte> fieldMapBytes)
    {
        var reader = new MessagePackReader(fieldMapBytes);
        return ReadWireRecord(ref reader);
    }

    /// <summary>
    /// Composes <see cref="RecordFieldValues"/> with a generated record
    /// formatter: the guest-side decode of a record-typed procedure
    /// parameter.
    /// </summary>
    public static T FromValue<T>(UniDataValue value, IMessagePackFormatter<T> formatter)
    {
        var reader = new MessagePackReader(RecordFieldValues(value));
        return formatter.Deserialize(ref reader, null!);
    }

    /// <summary>
    /// Composes a generated record formatter with
    /// <see cref="RecordFromFieldValues"/>: the guest-side encode of a
    /// record-typed procedure result.
    /// </summary>
    public static UniDataValue ToValue<T>(T value, IMessagePackFormatter<T> formatter)
    {
        var buffer = new ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        formatter.Serialize(ref writer, value, null!);
        writer.Flush();
        return RecordFromFieldValues(buffer.WrittenMemory);
    }

    // ---- envelope -> wire ----

    private static void WriteDatumWire(UniDataValue value, ref MessagePackWriter writer)
    {
        switch (value)
        {
            case UniDataValueScalar scalar:
                WriteScalarWire(scalar.Inner, ref writer);
                return;
            case UniDataValueArray array:
                writer.WriteArrayHeader(array.Inner.Count);
                foreach (var item in array.Inner)
                {
                    WriteDatumWire(item, ref writer);
                }

                return;
            case UniDataValueRecord record:
                writer.WriteMapHeader(record.Inner.Count);
                for (var i = 0; i < record.Inner.Count; i++)
                {
                    writer.Write((ulong)(i + 1));
                    WriteDatumWire(record.Inner[i].FieldValue, ref writer);
                }

                return;
            case UniDataValueBinary binary:
                writer.Write(binary.Inner.ToArray());
                return;
            default:
                throw new global::System.IO.InvalidDataException(
                    $"unknown UniDataValue kind {value?.GetType()}");
        }
    }

    private static void WriteScalarWire(UniScalarValue scalar, ref MessagePackWriter writer)
    {
        switch (scalar)
        {
            case UniScalarValueNull:
                writer.WriteNil();
                return;
            case UniScalarValueBool v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueU8 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueU16 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueU32 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueU64 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueI8 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueI16 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueI32 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueI64 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueF32 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueF64 v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueChar v:
                writer.Write(v.Inner.ToString());
                return;
            case UniScalarValueString v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueNumeric v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueDate v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueTime v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueTimestamp v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueTimestampTz v:
                writer.Write(v.Inner);
                return;
            case UniScalarValueBlob v:
                writer.Write(v.Inner.ToArray());
                return;
            default:
                // 128-bit scalars (U128/I128) have no generated-codec record
                // field form and cannot be declared in WIT record fields.
                throw new global::System.IO.InvalidDataException(
                    $"record bridge: unsupported UniScalarValue kind {scalar?.GetType()}");
        }
    }

    // ---- wire -> envelope ----

    private static UniDataValue ReadWireRecord(ref MessagePackReader reader)
    {
        var byKey = new global::System.Collections.Generic.SortedDictionary<long, UniDataValue>();
        var count = reader.ReadMapHeader();
        for (var i = 0; i < count; i++)
        {
            // Mirrors the generated decoders' lenient key handling: a
            // non-integer key is skipped together with its value.
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            var key = reader.ReadInt64();
            if (key <= 0)
            {
                reader.Skip();
                continue;
            }

            byKey[key] = ReadWireDatum(ref reader);
        }

        var fields = new global::System.Collections.Generic.List<UniDataValueField>();
        long position = 0;
        foreach (var (key, datum) in byKey)
        {
            while (++position < key)
            {
                fields.Add(new UniDataValueField { FieldName = string.Empty, FieldValue = NullDatum() });
            }

            fields.Add(new UniDataValueField { FieldName = string.Empty, FieldValue = datum });
        }

        return new UniDataValueRecord { Inner = fields };
    }

    private static UniDataValue ReadWireDatum(ref MessagePackReader reader)
    {
        switch (reader.NextMessagePackType)
        {
            case MessagePackType.Nil:
                reader.Skip();
                return NullDatum();
            case MessagePackType.Boolean:
                // the host vocabulary has no Bool: booleans cross as i32 (0/1)
                return I32Datum(reader.ReadBoolean() ? 1 : 0);
            case MessagePackType.Integer:
                if (reader.NextCode == MessagePackCode.UInt64)
                {
                    var unsigned = reader.ReadUInt64();
                    if (unsigned > long.MaxValue)
                    {
                        throw new global::System.IO.InvalidDataException(
                            $"u64 value {unsigned} overflows the host i64 vocabulary");
                    }

                    return I64Datum((long)unsigned);
                }

                var v = reader.ReadInt64();
                return v is >= int.MinValue and <= int.MaxValue ? I32Datum((int)v) : I64Datum(v);
            case MessagePackType.Float:
                if (reader.NextCode == MessagePackCode.Float32)
                {
                    return new UniDataValueScalar
                    {
                        Inner = new UniScalarValueF32 { Inner = reader.ReadSingle() },
                    };
                }

                return new UniDataValueScalar
                {
                    Inner = new UniScalarValueF64 { Inner = reader.ReadDouble() },
                };
            case MessagePackType.String:
                return new UniDataValueScalar
                {
                    Inner = new UniScalarValueString { Inner = reader.ReadString()! },
                };
            case MessagePackType.Binary:
                return new UniDataValueScalar
                {
                    Inner = new UniScalarValueBlob
                    {
                        Inner = global::System.Buffers.BuffersExtensions
                            .ToArray(reader.ReadBytes()!.Value)
                            .ToList(),
                    },
                };
            case MessagePackType.Array:
            {
                var n = reader.ReadArrayHeader();
                var items = new global::System.Collections.Generic.List<UniDataValue>(n);
                for (var i = 0; i < n; i++)
                {
                    items.Add(ReadWireDatum(ref reader));
                }

                return new UniDataValueArray { Inner = items };
            }

            case MessagePackType.Map:
                return ReadWireRecord(ref reader);
            default:
                throw new global::System.IO.InvalidDataException(
                    $"record bridge: unsupported MessagePack type {reader.NextMessagePackType}");
        }
    }

    // ---- small datum constructors ----

    private static UniDataValue NullDatum()
    {
        return new UniDataValueScalar { Inner = new UniScalarValueNull { Inner = 0 } };
    }

    private static UniDataValue I32Datum(int value)
    {
        return new UniDataValueScalar { Inner = new UniScalarValueI32 { Inner = value } };
    }

    private static UniDataValue I64Datum(long value)
    {
        return new UniDataValueScalar { Inner = new UniScalarValueI64 { Inner = value } };
    }
}
