//! SyscallPayload v1 codec: 16-byte MSSP header plus a MessagePack body.
//!
//! This module implements the guest→host syscall wire format defined by
//! `doc/cn/contract/syscall_payload_v1.md`. Every syscall request and every
//! syscall response is a self-describing frame:
//!
//! ```text
//! +-------------------------------------------+
//! | Header (16 bytes, all fields big-endian)  |
//! |   offset  0: magic        = 0x4D53_5350   |
//! |   offset  4: version      = 1             |
//! |   offset  8: flags        = 0 (reserved)  |
//! |   offset 12: message_kind (MessageKind)   |
//! +-------------------------------------------+
//! | Body (single MessagePack value)           |
//! +-------------------------------------------+
//! ```
//!
//! The magic and supported version range are registered in `mudu::compat`
//! under `FormatKind::SyscallPayload`. Integrity rules:
//!
//! - fewer than `HEADER_LEN` bytes: `ErrorCode::CorruptedData`;
//! - bad magic: `ErrorCode::CorruptedData` (via the compatibility registry);
//! - version outside `[1, 1]`: `ErrorCode::UnsupportedFormatVersion`;
//! - nonzero `flags`: `ErrorCode::CorruptedData`;
//! - `0` or unknown `message_kind`: `ErrorCode::Decode`;
//! - malformed MessagePack body or invalid UTF-8: `ErrorCode::Decode`.
//!
//! Body layout follows the project-controlled MessagePack rules of the
//! contract: records and request argument lists are maps keyed by the
//! 1-based field/parameter numbers, variants are `[tag, payload]` 2-arrays
//! (empty payload becomes a `0u8` placeholder), `option` maps to nil,
//! `result<T, E>` maps to `[ok_tag, value]` with `0u8` = ok / `1u8` = err,
//! strings are MessagePack str and byte strings are MessagePack bin. All
//! body values are built and parsed through the `mp_wire` runtime
//! ([`crate::universal::mp_wire`]).
//!
//! The per-kind request/result codec pairs for the 23 `uni-syscall.wit`
//! functions are generated by `mudu_gen` (see [`generated`]) and re-exported
//! through the thin `RS<...>`/`MuduError` adapters in `router`. They all
//! operate on **complete frames** (header included): `encode_*` functions
//! return a full frame and `decode_*` functions validate the header and
//! reject frames whose message kind does not match the decoder's kind.
//!
//! The header/frame helpers and the `result` body helpers below stay
//! hand-written on purpose: the header error taxonomy comes from the
//! `mudu::compat` registry (which the generated code deliberately does not
//! depend on) and the body helpers are public API pinned by the contract
//! tests.

mod generated;
pub mod migrate;
mod router;

pub use router::*;

use crate::codec::adapter::{error_from_mu, error_to_mu};
use crate::universal::mp_wire::{FromValue, ToValue, Value, WireError, decode_value, encode_value};
use crate::universal::uni_error::UniError;
use mudu::common::result::RS;
use mudu::compat::{
    CompatibilityMatrix, FormatKind, SYSCALL_PAYLOAD_CURRENT_VERSION, check_magic_and_version,
    corrupted,
};
use mudu::error::{ErrorCode, MuduError};
use mudu::mudu_error;

/// Length in bytes of the fixed syscall payload header.
pub const HEADER_LEN: usize = 16;

const FORMAT: FormatKind = FormatKind::SyscallPayload;
const MAGIC: u32 = CompatibilityMatrix::magic(FormatKind::SyscallPayload);
const VERSION: u32 = SYSCALL_PAYLOAD_CURRENT_VERSION;

/// The aggregated `syscall_schema` descriptor JSON
/// ([`crate::universal::uni_schema_desc::UniSchemaDesc`]) covering every WIT
/// file of the MSSP syscall contract, embedded for descriptor-driven
/// consumers (language runtimes, tooling). Regenerated together with the
/// codec (see `REGENERATE.md`); the Rust host codec itself is generated code
/// and does not read it at runtime.
pub const SYSCALL_SCHEMA_DESC_JSON: &str = include_str!("syscall_schema.desc.json");

/// Syscall message kinds carried in the header's `message_kind` field.
/// The discriminants identify the 23 `uni-syscall.wit` functions and are used
/// by host and guest to route frames. `0` and unknown values are rejected by
/// [`decode_header`]. The discriminants are pinned to the same 1-based WIT
/// declaration order as the generated
/// [`generated::uni_syscall::MessageKind`]; the two enums are kept in sync by
/// the golden corpus and the `message_kind_values_and_header_roundtrip` test.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, num_enum::IntoPrimitive, num_enum::TryFromPrimitive,
)]
#[repr(u32)]
pub enum MessageKind {
    /// `query` — SQL query.
    Query = 1,
    /// `command` — SQL command.
    Command = 2,
    /// `batch` — batched SQL command.
    Batch = 3,
    /// `open-session` — open a KV session.
    Open = 4,
    /// `close-session` — close a KV session.
    Close = 5,
    /// `get` — KV point lookup.
    Get = 6,
    /// `put` — KV insert/update.
    Put = 7,
    /// `delete` — KV removal.
    Delete = 8,
    /// `range` — KV range scan.
    Range = 9,
    /// `fs-open` — open a file.
    FsOpen = 10,
    /// `fs-close` — close a file descriptor.
    FsClose = 11,
    /// `fs-read` — read at the current position.
    FsRead = 12,
    /// `fs-write` — write at the current position.
    FsWrite = 13,
    /// `fs-pread` — positional read.
    FsPread = 14,
    /// `fs-pwrite` — positional write.
    FsPwrite = 15,
    /// `fs-lseek` — reposition a file descriptor.
    FsLseek = 16,
    /// `fs-fstat` — stat an open file descriptor.
    FsFstat = 17,
    /// `fs-stat` — stat a path.
    FsStat = 18,
    /// `fs-fsync` — flush a file descriptor.
    FsFsync = 19,
    /// `fs-readdir` — list a directory.
    FsReaddir = 20,
    /// `relation-get` — point read of a relation row by primary key.
    RelationGet = 21,
    /// `relation-update` — read-modify-write of a relation row by primary key.
    RelationUpdate = 22,
    /// `relation-insert` — insert of a relation row; duplicate keys fail.
    RelationInsert = 23,
}

/// Encodes the fixed 16-byte header for `kind`.
pub fn encode_header(kind: MessageKind) -> [u8; HEADER_LEN] {
    let mut out = [0u8; HEADER_LEN];
    out[0..4].copy_from_slice(&MAGIC.to_be_bytes());
    out[4..8].copy_from_slice(&VERSION.to_be_bytes());
    // flags at out[8..12] stay zero.
    out[12..16].copy_from_slice(&u32::from(kind).to_be_bytes());
    out
}

/// Decodes and validates the fixed 16-byte header, returning the message kind.
///
/// See the module-level documentation for the integrity rules and the error
/// codes they map to.
pub fn decode_header(input: &[u8]) -> RS<MessageKind> {
    if input.len() < HEADER_LEN {
        return Err(corrupted(FORMAT, "header shorter than 16 bytes").into_mudu_error());
    }
    let magic = be_u32(input, 0);
    let version = be_u32(input, 4);
    check_magic_and_version(FORMAT, magic, version).map_err(MuduError::from)?;
    let flags = be_u32(input, 8);
    if flags != 0 {
        return Err(
            corrupted(FORMAT, format!("nonzero header flags {flags:#x}")).into_mudu_error(),
        );
    }
    let kind_raw = be_u32(input, 12);
    MessageKind::try_from(kind_raw).map_err(|_| {
        mudu_error!(
            ErrorCode::Decode,
            format!("unknown syscall message kind {kind_raw}")
        )
    })
}

/// Encodes a complete frame: the 16-byte header followed by `body`.
pub fn encode_frame(kind: MessageKind, body: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(HEADER_LEN + body.len());
    out.extend_from_slice(&encode_header(kind));
    out.extend_from_slice(body);
    out
}

/// Splits a frame into its validated message kind and the borrowed body slice.
pub fn decode_frame(input: &[u8]) -> RS<(MessageKind, &[u8])> {
    let kind = decode_header(input)?;
    Ok((kind, &input[HEADER_LEN..]))
}

/// Encodes a `result<T, E>` body: `[0u8, value]` on success,
/// `[1u8, UniError]` on error.
pub fn encode_result_body<T: ToValue>(result: &RS<T>) -> Vec<u8> {
    match result {
        Ok(value) => encode_value(&Value::Array(vec![Value::from(0u8), value.to_value()])),
        Err(error) => encode_value(&Value::Array(vec![
            Value::from(1u8),
            error_to_mu(error.clone()).to_value(),
        ])),
    }
}

/// Encodes a unit `result<_, E>` body: `[0u8, 0u8]` on success,
/// `[1u8, UniError]` on error. The second element is the `0u8` placeholder
/// used for payload-less cases.
pub fn encode_result_unit_body(result: &RS<()>) -> Vec<u8> {
    match result {
        Ok(()) => encode_value(&Value::Array(vec![Value::from(0u8), Value::from(0u8)])),
        Err(error) => encode_value(&Value::Array(vec![
            Value::from(1u8),
            error_to_mu(error.clone()).to_value(),
        ])),
    }
}

/// Decodes a `result<T, E>` body: `[0u8, value]` becomes `Ok(value)` and
/// `[1u8, UniError]` becomes `Err(...)` with the error reconstructed from the
/// universal error record.
pub fn decode_result_body<T: FromValue>(body: &[u8]) -> RS<T> {
    match decode_wire_result(body)? {
        Ok(value) => Ok(T::from_value(&value).map_err(wire_error_to_mudu)?),
        Err(error) => Err(error_from_mu(
            UniError::from_value(&error).map_err(wire_error_to_mudu)?,
        )),
    }
}

/// Decodes a unit `result<_, E>` body: `[0u8, 0u8]` becomes `Ok(())` and
/// `[1u8, UniError]` becomes `Err(...)`.
pub fn decode_result_unit(body: &[u8]) -> RS<()> {
    match decode_wire_result(body)? {
        Ok(_) => Ok(()),
        Err(error) => Err(error_from_mu(
            UniError::from_value(&error).map_err(wire_error_to_mudu)?,
        )),
    }
}

/// Decodes a `[ok_tag, value]` result body into the raw value arm or the raw
/// error arm.
fn decode_wire_result(body: &[u8]) -> RS<Result<Value, Value>> {
    let value = decode_value(body).map_err(wire_error_to_mudu)?;
    let items = value.as_array().map_err(wire_error_to_mudu)?;
    if items.len() != 2 {
        return Err(mudu_error!(
            ErrorCode::Decode,
            format!(
                "result body must be a 2-element [ok_tag, value] array, found {} elements",
                items.len()
            )
        ));
    }
    let tag = u32::from_value(&items[0]).map_err(wire_error_to_mudu)?;
    match tag {
        0 => Ok(Ok(items[1].clone())),
        1 => Ok(Err(items[1].clone())),
        _ => Err(mudu_error!(
            ErrorCode::Decode,
            format!("unknown result tag {tag}, expected 0u8 or 1u8")
        )),
    }
}

/// Maps a wire-runtime decode error to a `MuduError`.
fn wire_error_to_mudu(error: WireError) -> MuduError {
    mudu_error!(ErrorCode::Decode, error.message)
}

/// Reads a big-endian `u32` at `offset`; `input` must be at least
/// `offset + 4` bytes long (guaranteed by the [`HEADER_LEN`] check).
fn be_u32(input: &[u8], offset: usize) -> u32 {
    let mut bytes = [0u8; 4];
    bytes.copy_from_slice(&input[offset..offset + 4]);
    u32::from_be_bytes(bytes)
}

/// Validates a frame and checks it carries the expected message kind,
/// returning the borrowed body.
///
/// The router runs this before delegating to the generated per-function
/// decoders so that header violations keep the exact `mudu::compat` error
/// codes; any failure the generated decoder can still produce afterwards is
/// a body-level `ErrorCode::Decode`.
fn decode_typed_frame(expected: MessageKind, frame: &[u8]) -> RS<&[u8]> {
    let (kind, body) = decode_frame(frame)?;
    if kind != expected {
        return Err(mudu_error!(
            ErrorCode::Decode,
            format!(
                "unexpected syscall message kind {}, expected {}",
                u32::from(kind),
                u32::from(expected)
            )
        ));
    }
    Ok(body)
}

/// Maps a generated-codec protocol error to a `MuduError`.
///
/// The router pre-validates the header with [`decode_typed_frame`], so the
/// only failures reachable here are kind mismatches (already excluded) and
/// malformed bodies: both are `ErrorCode::Decode`.
fn frame_error_to_mudu(error: generated::uni_syscall::SyscallFrameError) -> MuduError {
    mudu_error!(ErrorCode::Decode, error.message)
}

#[cfg(test)]
#[path = "syscall_payload_test.rs"]
mod syscall_payload_test;
