// Generated by mudu_gen. Do not edit manually.
/*
 * mududb C binding message types/codecs (mgen message -l c
 * --with-func-codec). Self-contained header: `MP_INLINE` functions only
 * (`static inline` in C, `inline` in C++), no mutable state. Ownership
 * contract: encode borrows its inputs; decode copies every variable-length
 * value into the caller's `mp_arena`; the writer owns its buffer
 * (`mpw_free`). See the package readme.md.
 */
#ifndef MUDUD_TYPES_UNI_QUERY_ARGV_H
#define MUDUD_TYPES_UNI_QUERY_ARGV_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "mududb/codec/mpack.h"
#include "mududb/types/UniOid.h"
#include "mududb/types/UniSqlStmt.h"
#include "mududb/types/UniSqlParam.h"
#include "mududb/types/UniRecordType.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef MUDUD_FWD_UNI_QUERY_ARGV
#define MUDUD_FWD_UNI_QUERY_ARGV
typedef struct uni_query_argv uni_query_argv;
MP_INLINE void uni_query_argv_encode(mp_writer *w, const uni_query_argv *value);
MP_INLINE int uni_query_argv_decode(mp_reader *r, mp_arena *a, uni_query_argv *out);
MP_INLINE uni_query_argv *uni_query_argv_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_QUERY_ARGV */

struct uni_query_argv {
    uni_oid oid;
    uni_sql_stmt query;
    uni_sql_param param_list;
    uni_record_type param_desc;
    bool param_desc_is_null;
};

/* Encode `value` as a MessagePack map keyed by the 1-based field numbers
 * (WIT declaration order); `option` fields are omitted when null (proto3
 * presence semantics). Encode only borrows `value`; failures are sticky in
 * `w` (check `mpw_ok`). */
MP_INLINE void uni_query_argv_encode(mp_writer *w, const uni_query_argv *value) {
    mpw_map_header(w, 4u - 1u + (value->param_desc_is_null ? 0u : 1u));
    mpw_u64(w, 1u);
    uni_oid_encode(w, &(value->oid));
    mpw_u64(w, 2u);
    uni_sql_stmt_encode(w, &(value->query));
    mpw_u64(w, 3u);
    uni_sql_param_encode(w, &(value->param_list));
    if (!value->param_desc_is_null) {
        mpw_u64(w, 4u);
        uni_record_type_encode(w, &(value->param_desc));
    }
}

/* Decode one record into `out`, borrowing nothing from the input: every
 * string, blob, array and boxed value is copied into `a`. Lenient: unknown
 * keys are skipped and missing fields keep their zero default (absent
 * `option` fields decode as null). 0 on success, -1 (with the reader's
 * sticky error set) on malformed input or arena exhaustion. */
MP_INLINE int uni_query_argv_decode(mp_reader *r, mp_arena *a, uni_query_argv *out) {
    (void)a;
    memset(out, 0, sizeof(*out));
    out->param_desc_is_null = 1;
    {
        uint32_t count = mpr_map_header(r);
        for (uint32_t i = 0; i < count && mpr_ok(r); i++) {
            if (mpr_next_is_integer(r)) {
                uint64_t key = mpr_u64(r);
                if (key == 1u) {
                    uni_oid_decode(r, a, &(out->oid));
                } else if (key == 2u) {
                    uni_sql_stmt_decode(r, a, &(out->query));
                } else if (key == 3u) {
                    uni_sql_param_decode(r, a, &(out->param_list));
                } else if (key == 4u) {
                    if (mpr_try_nil(r)) {
                        out->param_desc_is_null = 1;
                    } else {
                        out->param_desc_is_null = 0;
                        uni_record_type_decode(r, a, &(out->param_desc));
                    }
                } else {
                    mpr_skip(r);
                }
            } else {
                mpr_skip(r);
                mpr_skip(r);
            }
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one record into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_query_argv *uni_query_argv_decode_new(mp_reader *r, mp_arena *a) {
    uni_query_argv *p = (uni_query_argv *)mpa_alloc(a, sizeof(uni_query_argv));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_query_argv_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

#ifdef __cplusplus
}
#endif

#endif /* MUDUD_TYPES_UNI_QUERY_ARGV_H */