// Generated by mudu_gen. Do not edit manually.
/*
 * mududb C binding message types/codecs (mgen message -l c
 * --with-func-codec). Self-contained header: `MP_INLINE` functions only
 * (`static inline` in C, `inline` in C++), no mutable state. Ownership
 * contract: encode borrows its inputs; decode copies every variable-length
 * value into the caller's `mp_arena`; the writer owns its buffer
 * (`mpw_free`). See the package readme.md.
 */
#ifndef MUDUD_TYPES_UNI_RESULT_SET_H
#define MUDUD_TYPES_UNI_RESULT_SET_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "mududb/codec/mpack.h"
#include "mududb/types/UniTupleRow.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef MUDUD_FWD_UNI_RESULT_SET
#define MUDUD_FWD_UNI_RESULT_SET
typedef struct uni_result_set uni_result_set;
MP_INLINE void uni_result_set_encode(mp_writer *w, const uni_result_set *value);
MP_INLINE int uni_result_set_decode(mp_reader *r, mp_arena *a, uni_result_set *out);
MP_INLINE uni_result_set *uni_result_set_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_RESULT_SET */

typedef struct { uni_tuple_row *items; uint32_t len; } uni_result_set_row_set_list;
struct uni_result_set {
    bool eof;
    uni_result_set_row_set_list row_set;
    mp_bin cursor;
};

/* Encode `value` as a MessagePack map keyed by the 1-based field numbers
 * (WIT declaration order); `option` fields are omitted when null (proto3
 * presence semantics). Encode only borrows `value`; failures are sticky in
 * `w` (check `mpw_ok`). */
MP_INLINE void uni_result_set_encode(mp_writer *w, const uni_result_set *value) {
    mpw_map_header(w, 3u);
    mpw_u64(w, 1u);
    mpw_bool(w, value->eof);
    mpw_u64(w, 2u);
    mpw_array_header(w, (value->row_set).len);
    for (uint32_t i0 = 0; i0 < (value->row_set).len; i0++) {
        uni_tuple_row_encode(w, &((value->row_set).items[i0]));
    }
    mpw_u64(w, 3u);
    mpw_array_header(w, (value->cursor).len);
    for (uint32_t i0 = 0; i0 < (value->cursor).len; i0++) {
        mpw_u64(w, (value->cursor).data[i0]);
    }
}

/* Decode one record into `out`, borrowing nothing from the input: every
 * string, blob, array and boxed value is copied into `a`. Lenient: unknown
 * keys are skipped and missing fields keep their zero default (absent
 * `option` fields decode as null). 0 on success, -1 (with the reader's
 * sticky error set) on malformed input or arena exhaustion. */
MP_INLINE int uni_result_set_decode(mp_reader *r, mp_arena *a, uni_result_set *out) {
    (void)a;
    memset(out, 0, sizeof(*out));
    {
        uint32_t count = mpr_map_header(r);
        for (uint32_t i = 0; i < count && mpr_ok(r); i++) {
            if (mpr_next_is_integer(r)) {
                uint64_t key = mpr_u64(r);
                if (key == 1u) {
                    out->eof = mpr_bool(r);
                } else if (key == 2u) {
                    {
                        uint32_t n0 = mpr_array_header(r);
                        uni_tuple_row *p0 = (uni_tuple_row *)mpa_alloc(a, sizeof(uni_tuple_row) * (size_t)n0);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            for (uint32_t i0 = 0; i0 < n0; i0++) {
                                uni_tuple_row_decode(r, a, &(p0[i0]));
                            }
                            (out->row_set).items = p0;
                            (out->row_set).len = n0;
                        }
                    }
                } else if (key == 3u) {
                    {
                        uint32_t n0 = mpr_array_header(r);
                        uint8_t *p0 = (uint8_t *)mpa_alloc(a, n0);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            for (uint32_t i0 = 0; i0 < n0; i0++) {
                                p0[i0] = (uint8_t)mpr_u64(r);
                            }
                            (out->cursor).data = p0;
                            (out->cursor).len = n0;
                        }
                    }
                } else {
                    mpr_skip(r);
                }
            } else {
                mpr_skip(r);
                mpr_skip(r);
            }
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one record into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_result_set *uni_result_set_decode_new(mp_reader *r, mp_arena *a) {
    uni_result_set *p = (uni_result_set *)mpa_alloc(a, sizeof(uni_result_set));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_result_set_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

#ifdef __cplusplus
}
#endif

#endif /* MUDUD_TYPES_UNI_RESULT_SET_H */