// Generated by mudu_gen. Do not edit manually.
/*
 * mududb C binding message types/codecs (mgen message -l c
 * --with-func-codec). Self-contained header: `MP_INLINE` functions only
 * (`static inline` in C, `inline` in C++), no mutable state. Ownership
 * contract: encode borrows its inputs; decode copies every variable-length
 * value into the caller's `mp_arena`; the writer owns its buffer
 * (`mpw_free`). See the package readme.md.
 */
#ifndef MUDUD_TYPES_UNI_SQL_STMT_H
#define MUDUD_TYPES_UNI_SQL_STMT_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "mududb/codec/mpack.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef MUDUD_FWD_UNI_SQL_STMT
#define MUDUD_FWD_UNI_SQL_STMT
typedef struct uni_sql_stmt uni_sql_stmt;
MP_INLINE void uni_sql_stmt_encode(mp_writer *w, const uni_sql_stmt *value);
MP_INLINE int uni_sql_stmt_decode(mp_reader *r, mp_arena *a, uni_sql_stmt *out);
MP_INLINE uni_sql_stmt *uni_sql_stmt_decode_new(mp_reader *r, mp_arena *a);
#endif /* MUDUD_FWD_UNI_SQL_STMT */

struct uni_sql_stmt {
    mp_str sql_string;
};

/* Encode `value` as a MessagePack map keyed by the 1-based field numbers
 * (WIT declaration order); `option` fields are omitted when null (proto3
 * presence semantics). Encode only borrows `value`; failures are sticky in
 * `w` (check `mpw_ok`). */
MP_INLINE void uni_sql_stmt_encode(mp_writer *w, const uni_sql_stmt *value) {
    mpw_map_header(w, 1u);
    mpw_u64(w, 1u);
    mpw_str(w, (value->sql_string).data, (value->sql_string).len);
}

/* Decode one record into `out`, borrowing nothing from the input: every
 * string, blob, array and boxed value is copied into `a`. Lenient: unknown
 * keys are skipped and missing fields keep their zero default (absent
 * `option` fields decode as null). 0 on success, -1 (with the reader's
 * sticky error set) on malformed input or arena exhaustion. */
MP_INLINE int uni_sql_stmt_decode(mp_reader *r, mp_arena *a, uni_sql_stmt *out) {
    (void)a;
    memset(out, 0, sizeof(*out));
    {
        uint32_t count = mpr_map_header(r);
        for (uint32_t i = 0; i < count && mpr_ok(r); i++) {
            if (mpr_next_is_integer(r)) {
                uint64_t key = mpr_u64(r);
                if (key == 1u) {
                    {
                        uint32_t n0 = 0;
                        const char *s0 = mpr_str(r, &n0);
                        char *p0 = (char *)mpa_alloc(a, (size_t)n0 + 1u);
                        if (p0 == 0) {
                            mpr_fail(r);
                        } else {
                            memcpy(p0, s0, n0);
                            p0[n0] = '\0';
                            (out->sql_string).data = p0;
                            (out->sql_string).len = n0;
                        }
                    }
                } else {
                    mpr_skip(r);
                }
            } else {
                mpr_skip(r);
                mpr_skip(r);
            }
        }
    }
    return mpr_ok(r) ? 0 : -1;
}

/* Decode one record into freshly arena-allocated storage; 0 on failure
 * (the reader's sticky error is set). Boxes of this type decode through
 * this function, so headers referencing it by pointer never need its
 * `sizeof`. */
MP_INLINE uni_sql_stmt *uni_sql_stmt_decode_new(mp_reader *r, mp_arena *a) {
    uni_sql_stmt *p = (uni_sql_stmt *)mpa_alloc(a, sizeof(uni_sql_stmt));
    if (p == 0) {
        mpr_fail(r);
        return 0;
    }
    if (uni_sql_stmt_decode(r, a, p) != 0) {
        return 0;
    }
    return p;
}

#ifdef __cplusplus
}
#endif

#endif /* MUDUD_TYPES_UNI_SQL_STMT_H */