// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;





[MessagePackFormatter(typeof(UniCommandReturnFormatter))]
public interface UniCommandReturn
{
    public UniCommandReturnKind Kind();
}

public enum UniCommandReturnKind {

   Ok = 0,

   Err = 1,

}



public class UniCommandReturnOk : UniCommandReturn
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniCommandReturnOk()
    {
        Inner = new UniCommandResult();
    }
    

    public required UniCommandResult Inner  { get; set; }

    public UniCommandReturnKind Kind() {
        return UniCommandReturnKind.Ok;
    }

    public static UniCommandReturnKind KindStatic() {
        return UniCommandReturnKind.Ok;
    }

    public static UniCommandReturnOk AsOk(UniCommandReturn value)
    {
        switch (value)
        {
            case UniCommandReturnOk  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}

public class UniCommandReturnErr : UniCommandReturn
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniCommandReturnErr()
    {
        Inner = new UniError();
    }
    

    public required UniError Inner  { get; set; }

    public UniCommandReturnKind Kind() {
        return UniCommandReturnKind.Err;
    }

    public static UniCommandReturnKind KindStatic() {
        return UniCommandReturnKind.Err;
    }

    public static UniCommandReturnErr AsErr(UniCommandReturn value)
    {
        switch (value)
        {
            case UniCommandReturnErr  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}


public class UniCommandReturnFormatter : IMessagePackFormatter<UniCommandReturn?>
{
    /// The proto3-style default instance of the variant: the first declared
    /// case carrying its own default payload. Record fields of this variant
    /// type initialize to this value, so a field missing from the wire map
    /// decodes to the default case instead of null.
    public static UniCommandReturn DefaultInstance()
    {
        
        return new UniCommandReturnOk { Inner = new UniCommandResult() };
        
    }

    public void Serialize(ref MessagePackWriter writer, UniCommandReturn? value, MessagePackSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNil();
            return;
        }

        writer.WriteArrayHeader(2);
        writer.Write((uint)value.Kind());
        switch (value.Kind())
        {
            
            case UniCommandReturnKind.Ok:
                
                new UniCommandResultFormatter().Serialize(ref writer, ((UniCommandReturnOk)value).Inner, options);

                
                break;
            
            case UniCommandReturnKind.Err:
                
                new UniErrorFormatter().Serialize(ref writer, ((UniCommandReturnErr)value).Inner, options);

                
                break;
            
            default:
                throw new global::System.InvalidOperationException($"Unknown kind: {value.Kind()}");
        }
    }

    public UniCommandReturn? Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        if (reader.TryReadNil())
        {
            return null;
        }

        var count = reader.ReadArrayHeader();
        if (count != 2)
        {
            throw new global::System.InvalidOperationException($"Expected array of length 2, got {count}");
        }

        var tag = reader.ReadUInt32();
        switch (tag)
        {
            
            case 0:
                
                var okInner = new UniCommandResultFormatter().Deserialize(ref reader, options)!;

                return new UniCommandReturnOk { Inner = okInner };
                
            
            case 1:
                
                var errInner = new UniErrorFormatter().Deserialize(ref reader, options)!;

                return new UniCommandReturnErr { Inner = errInner };
                
            
            default:
                throw new global::System.InvalidOperationException($"Unknown tag: {tag}");
        }
    }
}


[MessagePackFormatter(typeof(UniCommandResultFormatter))]
public struct UniCommandResult {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniCommandResult()
    {
        
        AffectedRows = 0;
        
    }
    
    
    
    public ulong AffectedRows { get; set; }
    
}

public class UniCommandResultFormatter : IMessagePackFormatter<UniCommandResult>
{
    public void Serialize(ref MessagePackWriter writer, UniCommandResult value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(1);
        
        writer.Write(1);
        writer.Write(value.AffectedRows);

        
    }

    public UniCommandResult Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniCommandResult();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.AffectedRows = reader.ReadUInt64();

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}