// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;





[MessagePackFormatter(typeof(UniDataValueFormatter))]
public interface UniDataValue
{
    public UniDataValueKind Kind();
}

public enum UniDataValueKind {

   Scalar = 0,

   Array = 1,

   Record = 2,

   Binary = 3,

}



public class UniDataValueScalar : UniDataValue
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniDataValueScalar()
    {
        Inner = UniScalarValueFormatter.DefaultInstance();
    }
    

    public required UniScalarValue Inner  { get; set; }

    public UniDataValueKind Kind() {
        return UniDataValueKind.Scalar;
    }

    public static UniDataValueKind KindStatic() {
        return UniDataValueKind.Scalar;
    }

    public static UniDataValueScalar AsScalar(UniDataValue value)
    {
        switch (value)
        {
            case UniDataValueScalar  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}

public class UniDataValueArray : UniDataValue
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniDataValueArray()
    {
        Inner = [];
    }
    

    public required List<UniDataValue> Inner  { get; set; }

    public UniDataValueKind Kind() {
        return UniDataValueKind.Array;
    }

    public static UniDataValueKind KindStatic() {
        return UniDataValueKind.Array;
    }

    public static UniDataValueArray AsArray(UniDataValue value)
    {
        switch (value)
        {
            case UniDataValueArray  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}

public class UniDataValueRecord : UniDataValue
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniDataValueRecord()
    {
        Inner = [];
    }
    

    public required List<UniDataValueField> Inner  { get; set; }

    public UniDataValueKind Kind() {
        return UniDataValueKind.Record;
    }

    public static UniDataValueKind KindStatic() {
        return UniDataValueKind.Record;
    }

    public static UniDataValueRecord AsRecord(UniDataValue value)
    {
        switch (value)
        {
            case UniDataValueRecord  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}

public class UniDataValueBinary : UniDataValue
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniDataValueBinary()
    {
        Inner = [];
    }
    

    public required List<byte> Inner  { get; set; }

    public UniDataValueKind Kind() {
        return UniDataValueKind.Binary;
    }

    public static UniDataValueKind KindStatic() {
        return UniDataValueKind.Binary;
    }

    public static UniDataValueBinary AsBinary(UniDataValue value)
    {
        switch (value)
        {
            case UniDataValueBinary  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}


public class UniDataValueFormatter : IMessagePackFormatter<UniDataValue?>
{
    /// The proto3-style default instance of the variant: the first declared
    /// case carrying its own default payload. Record fields of this variant
    /// type initialize to this value, so a field missing from the wire map
    /// decodes to the default case instead of null.
    public static UniDataValue DefaultInstance()
    {
        
        return new UniDataValueScalar { Inner = UniScalarValueFormatter.DefaultInstance() };
        
    }

    public void Serialize(ref MessagePackWriter writer, UniDataValue? value, MessagePackSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNil();
            return;
        }

        writer.WriteArrayHeader(2);
        writer.Write((uint)value.Kind());
        switch (value.Kind())
        {
            
            case UniDataValueKind.Scalar:
                
                new UniScalarValueFormatter().Serialize(ref writer, ((UniDataValueScalar)value).Inner, options);

                
                break;
            
            case UniDataValueKind.Array:
                
                if (((UniDataValueArray)value).Inner is null)
                {
                    writer.WriteNil();
                }
                else
                {
                    writer.WriteArrayHeader(((UniDataValueArray)value).Inner.Count);
                    foreach (var __e0 in ((UniDataValueArray)value).Inner)
                    {
                        new UniDataValueFormatter().Serialize(ref writer, __e0, options);
                    }
                }

                
                break;
            
            case UniDataValueKind.Record:
                
                if (((UniDataValueRecord)value).Inner is null)
                {
                    writer.WriteNil();
                }
                else
                {
                    writer.WriteArrayHeader(((UniDataValueRecord)value).Inner.Count);
                    foreach (var __e0 in ((UniDataValueRecord)value).Inner)
                    {
                        new UniDataValueFieldFormatter().Serialize(ref writer, __e0, options);
                    }
                }

                
                break;
            
            case UniDataValueKind.Binary:
                
                if (((UniDataValueBinary)value).Inner is null)
                {
                    writer.WriteNil();
                }
                else
                {
                    writer.WriteArrayHeader(((UniDataValueBinary)value).Inner.Count);
                    foreach (var __e0 in ((UniDataValueBinary)value).Inner)
                    {
                        writer.Write(__e0);
                    }
                }

                
                break;
            
            default:
                throw new global::System.InvalidOperationException($"Unknown kind: {value.Kind()}");
        }
    }

    public UniDataValue? Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        if (reader.TryReadNil())
        {
            return null;
        }

        var count = reader.ReadArrayHeader();
        if (count != 2)
        {
            throw new global::System.InvalidOperationException($"Expected array of length 2, got {count}");
        }

        var tag = reader.ReadUInt32();
        switch (tag)
        {
            
            case 0:
                
                var scalarInner = new UniScalarValueFormatter().Deserialize(ref reader, options)!;

                return new UniDataValueScalar { Inner = scalarInner };
                
            
            case 1:
                
                List<UniDataValue> arrayInner;
                if (reader.TryReadNil())
                {
                    arrayInner = null!;
                }
                else
                {
                    var __c1 = reader.ReadArrayHeader();
                    var __l1 = new List<UniDataValue>(__c1);
                    for (var __i1 = 0; __i1 < __c1; __i1++)
                    {
                        __l1.Add(new UniDataValueFormatter().Deserialize(ref reader, options));
                    }
                    arrayInner = __l1;
                }

                return new UniDataValueArray { Inner = arrayInner };
                
            
            case 2:
                
                List<UniDataValueField> recordInner;
                if (reader.TryReadNil())
                {
                    recordInner = null!;
                }
                else
                {
                    var __c1 = reader.ReadArrayHeader();
                    var __l1 = new List<UniDataValueField>(__c1);
                    for (var __i1 = 0; __i1 < __c1; __i1++)
                    {
                        __l1.Add(new UniDataValueFieldFormatter().Deserialize(ref reader, options));
                    }
                    recordInner = __l1;
                }

                return new UniDataValueRecord { Inner = recordInner };
                
            
            case 3:
                
                List<byte> binaryInner;
                if (reader.TryReadNil())
                {
                    binaryInner = null!;
                }
                else
                {
                    var __c1 = reader.ReadArrayHeader();
                    var __l1 = new List<byte>(__c1);
                    for (var __i1 = 0; __i1 < __c1; __i1++)
                    {
                        __l1.Add(reader.ReadByte());
                    }
                    binaryInner = __l1;
                }

                return new UniDataValueBinary { Inner = binaryInner };
                
            
            default:
                throw new global::System.InvalidOperationException($"Unknown tag: {tag}");
        }
    }
}


[MessagePackFormatter(typeof(UniDataValueFieldFormatter))]
public struct UniDataValueField {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniDataValueField()
    {
        
        FieldName = string.Empty;
        
        FieldValue = UniDataValueFormatter.DefaultInstance();
        
    }
    
    
    
    public required string FieldName { get; set; }
    
    
    public required UniDataValue FieldValue { get; set; }
    
}

public class UniDataValueFieldFormatter : IMessagePackFormatter<UniDataValueField>
{
    public void Serialize(ref MessagePackWriter writer, UniDataValueField value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(2);
        
        writer.Write(1);
        if (value.FieldName is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.FieldName);
        }

        
        writer.Write(2);
        new UniDataValueFormatter().Serialize(ref writer, value.FieldValue, options);

        
    }

    public UniDataValueField Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniDataValueField();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.FieldName = reader.ReadString()!;

                    break;
                }
                
                case 2:
                {
        value.FieldValue = new UniDataValueFormatter().Deserialize(ref reader, options)!;

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}