// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniErrorFormatter))]
public struct UniError {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniError()
    {
        
        ErrCode = 0;
        
        ErrMsg = string.Empty;
        
        ErrSrc = string.Empty;
        
        ErrLoc = string.Empty;
        
        ErrDetails = [];
        
    }
    
    
    
    public uint ErrCode { get; set; }
    
    
    public required string ErrMsg { get; set; }
    
    
    public required string ErrSrc { get; set; }
    
    
    public required string ErrLoc { get; set; }
    
    
    public required List<byte> ErrDetails { get; set; }
    
}

public class UniErrorFormatter : IMessagePackFormatter<UniError>
{
    public void Serialize(ref MessagePackWriter writer, UniError value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(5);
        
        writer.Write(1);
        writer.Write(value.ErrCode);

        
        writer.Write(2);
        if (value.ErrMsg is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.ErrMsg);
        }

        
        writer.Write(3);
        if (value.ErrSrc is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.ErrSrc);
        }

        
        writer.Write(4);
        if (value.ErrLoc is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.ErrLoc);
        }

        
        writer.Write(5);
        if (value.ErrDetails is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.ErrDetails.Count);
            foreach (var __e0 in value.ErrDetails)
            {
                writer.Write(__e0);
            }
        }

        
    }

    public UniError Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniError();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.ErrCode = reader.ReadUInt32();

                    break;
                }
                
                case 2:
                {
        value.ErrMsg = reader.ReadString()!;

                    break;
                }
                
                case 3:
                {
        value.ErrSrc = reader.ReadString()!;

                    break;
                }
                
                case 4:
                {
        value.ErrLoc = reader.ReadString()!;

                    break;
                }
                
                case 5:
                {
        if (reader.TryReadNil())
        {
            value.ErrDetails = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<byte>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(reader.ReadByte());
            }
            value.ErrDetails = __l1;
        }

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}