// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniFsOpenArgvFormatter))]
public struct UniFsOpenArgv {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniFsOpenArgv()
    {
        
        Session = new UniOid();
        
        Oid = new UniOid();
        
        Path = string.Empty;
        
        Flags = 0;
        
    }
    
    
    
    public required UniOid Session { get; set; }
    
    
    public required UniOid Oid { get; set; }
    
    
    public required string Path { get; set; }
    
    
    public uint Flags { get; set; }
    
}

public class UniFsOpenArgvFormatter : IMessagePackFormatter<UniFsOpenArgv>
{
    public void Serialize(ref MessagePackWriter writer, UniFsOpenArgv value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(4);
        
        writer.Write(1);
        new UniOidFormatter().Serialize(ref writer, value.Session, options);

        
        writer.Write(2);
        new UniOidFormatter().Serialize(ref writer, value.Oid, options);

        
        writer.Write(3);
        if (value.Path is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.Path);
        }

        
        writer.Write(4);
        writer.Write(value.Flags);

        
    }

    public UniFsOpenArgv Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniFsOpenArgv();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.Session = new UniOidFormatter().Deserialize(ref reader, options)!;

                    break;
                }
                
                case 2:
                {
        value.Oid = new UniOidFormatter().Deserialize(ref reader, options)!;

                    break;
                }
                
                case 3:
                {
        value.Path = reader.ReadString()!;

                    break;
                }
                
                case 4:
                {
        value.Flags = reader.ReadUInt32();

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}