// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniFsDirentFormatter))]
public struct UniFsDirent {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniFsDirent()
    {
        
        Name = string.Empty;
        
        IsDir = false;
        
        Length = 0;
        
    }
    
    
    
    public required string Name { get; set; }
    
    
    public bool IsDir { get; set; }
    
    
    public ulong Length { get; set; }
    
}

public class UniFsDirentFormatter : IMessagePackFormatter<UniFsDirent>
{
    public void Serialize(ref MessagePackWriter writer, UniFsDirent value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(3);
        
        writer.Write(1);
        if (value.Name is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.Name);
        }

        
        writer.Write(2);
        writer.Write(value.IsDir);

        
        writer.Write(3);
        writer.Write(value.Length);

        
    }

    public UniFsDirent Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniFsDirent();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.Name = reader.ReadString()!;

                    break;
                }
                
                case 2:
                {
        value.IsDir = (reader.NextMessagePackType == MessagePackType.Integer ? (reader.ReadInt64() switch { 0 => false, 1 => true, _ => throw new global::System.IO.InvalidDataException("MSSP expected a bool encoded as 0/1") }) : reader.ReadBoolean());

                    break;
                }
                
                case 3:
                {
        value.Length = reader.ReadUInt64();

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}