// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




// object id

[MessagePackFormatter(typeof(UniOidFormatter))]
public struct UniOid {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniOid()
    {
        
        H = 0;
        
        L = 0;
        
    }
    
    
    
    // higher 64 bits
    
    public ulong H { get; set; }
    
    
    // lower 64 bits
    
    public ulong L { get; set; }
    
}

public class UniOidFormatter : IMessagePackFormatter<UniOid>
{
    public void Serialize(ref MessagePackWriter writer, UniOid value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(2);
        
        writer.Write(1);
        writer.Write(value.H);

        
        writer.Write(2);
        writer.Write(value.L);

        
    }

    public UniOid Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniOid();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.H = reader.ReadUInt64();

                    break;
                }
                
                case 2:
                {
        value.L = reader.ReadUInt64();

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}