// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;





[MessagePackFormatter(typeof(UniQueryReturnFormatter))]
public interface UniQueryReturn
{
    public UniQueryReturnKind Kind();
}

public enum UniQueryReturnKind {

   Ok = 0,

   Err = 1,

}



public class UniQueryReturnOk : UniQueryReturn
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniQueryReturnOk()
    {
        Inner = new UniQueryResult();
    }
    

    public required UniQueryResult Inner  { get; set; }

    public UniQueryReturnKind Kind() {
        return UniQueryReturnKind.Ok;
    }

    public static UniQueryReturnKind KindStatic() {
        return UniQueryReturnKind.Ok;
    }

    public static UniQueryReturnOk AsOk(UniQueryReturn value)
    {
        switch (value)
        {
            case UniQueryReturnOk  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}

public class UniQueryReturnErr : UniQueryReturn
{
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniQueryReturnErr()
    {
        Inner = new UniError();
    }
    

    public required UniError Inner  { get; set; }

    public UniQueryReturnKind Kind() {
        return UniQueryReturnKind.Err;
    }

    public static UniQueryReturnKind KindStatic() {
        return UniQueryReturnKind.Err;
    }

    public static UniQueryReturnErr AsErr(UniQueryReturn value)
    {
        switch (value)
        {
            case UniQueryReturnErr  v:
                return v;
            default:
                throw new global::System.InvalidOperationException($"Unknown type: {value?.GetType()}");
        }
    }
}


public class UniQueryReturnFormatter : IMessagePackFormatter<UniQueryReturn?>
{
    /// The proto3-style default instance of the variant: the first declared
    /// case carrying its own default payload. Record fields of this variant
    /// type initialize to this value, so a field missing from the wire map
    /// decodes to the default case instead of null.
    public static UniQueryReturn DefaultInstance()
    {
        
        return new UniQueryReturnOk { Inner = new UniQueryResult() };
        
    }

    public void Serialize(ref MessagePackWriter writer, UniQueryReturn? value, MessagePackSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNil();
            return;
        }

        writer.WriteArrayHeader(2);
        writer.Write((uint)value.Kind());
        switch (value.Kind())
        {
            
            case UniQueryReturnKind.Ok:
                
                new UniQueryResultFormatter().Serialize(ref writer, ((UniQueryReturnOk)value).Inner, options);

                
                break;
            
            case UniQueryReturnKind.Err:
                
                new UniErrorFormatter().Serialize(ref writer, ((UniQueryReturnErr)value).Inner, options);

                
                break;
            
            default:
                throw new global::System.InvalidOperationException($"Unknown kind: {value.Kind()}");
        }
    }

    public UniQueryReturn? Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        if (reader.TryReadNil())
        {
            return null;
        }

        var count = reader.ReadArrayHeader();
        if (count != 2)
        {
            throw new global::System.InvalidOperationException($"Expected array of length 2, got {count}");
        }

        var tag = reader.ReadUInt32();
        switch (tag)
        {
            
            case 0:
                
                var okInner = new UniQueryResultFormatter().Deserialize(ref reader, options)!;

                return new UniQueryReturnOk { Inner = okInner };
                
            
            case 1:
                
                var errInner = new UniErrorFormatter().Deserialize(ref reader, options)!;

                return new UniQueryReturnErr { Inner = errInner };
                
            
            default:
                throw new global::System.InvalidOperationException($"Unknown tag: {tag}");
        }
    }
}


[MessagePackFormatter(typeof(UniQueryResultFormatter))]
public struct UniQueryResult {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniQueryResult()
    {
        
        TupleDesc = new UniRecordType();
        
        ResultSet = new UniResultSet();
        
    }
    
    
    
    public required UniRecordType TupleDesc { get; set; }
    
    
    public required UniResultSet ResultSet { get; set; }
    
}

public class UniQueryResultFormatter : IMessagePackFormatter<UniQueryResult>
{
    public void Serialize(ref MessagePackWriter writer, UniQueryResult value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(2);
        
        writer.Write(1);
        new UniRecordTypeFormatter().Serialize(ref writer, value.TupleDesc, options);

        
        writer.Write(2);
        new UniResultSetFormatter().Serialize(ref writer, value.ResultSet, options);

        
    }

    public UniQueryResult Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniQueryResult();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.TupleDesc = new UniRecordTypeFormatter().Deserialize(ref reader, options)!;

                    break;
                }
                
                case 2:
                {
        value.ResultSet = new UniResultSetFormatter().Deserialize(ref reader, options)!;

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}