// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniFieldAttrFormatter))]
public struct UniFieldAttr {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniFieldAttr()
    {
        
        AttrName = string.Empty;
        
        AttrValue = string.Empty;
        
    }
    
    
    
    public required string AttrName { get; set; }
    
    
    public required string AttrValue { get; set; }
    
}

public class UniFieldAttrFormatter : IMessagePackFormatter<UniFieldAttr>
{
    public void Serialize(ref MessagePackWriter writer, UniFieldAttr value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(2);
        
        writer.Write(1);
        if (value.AttrName is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.AttrName);
        }

        
        writer.Write(2);
        if (value.AttrValue is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.AttrValue);
        }

        
    }

    public UniFieldAttr Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniFieldAttr();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.AttrName = reader.ReadString()!;

                    break;
                }
                
                case 2:
                {
        value.AttrValue = reader.ReadString()!;

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}


[MessagePackFormatter(typeof(UniRecordFieldFormatter))]
public struct UniRecordField {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniRecordField()
    {
        
        FieldName = string.Empty;
        
        FieldType = UniDataTypeFormatter.DefaultInstance();
        
        FieldAttrs = [];
        
    }
    
    
    
    public required string FieldName { get; set; }
    
    
    public required UniDataType FieldType { get; set; }
    
    
    public required List<UniFieldAttr> FieldAttrs { get; set; }
    
}

public class UniRecordFieldFormatter : IMessagePackFormatter<UniRecordField>
{
    public void Serialize(ref MessagePackWriter writer, UniRecordField value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(3);
        
        writer.Write(1);
        if (value.FieldName is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.FieldName);
        }

        
        writer.Write(2);
        new UniDataTypeFormatter().Serialize(ref writer, value.FieldType, options);

        
        writer.Write(3);
        if (value.FieldAttrs is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.FieldAttrs.Count);
            foreach (var __e0 in value.FieldAttrs)
            {
                new UniFieldAttrFormatter().Serialize(ref writer, __e0, options);
            }
        }

        
    }

    public UniRecordField Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniRecordField();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.FieldName = reader.ReadString()!;

                    break;
                }
                
                case 2:
                {
        value.FieldType = new UniDataTypeFormatter().Deserialize(ref reader, options)!;

                    break;
                }
                
                case 3:
                {
        if (reader.TryReadNil())
        {
            value.FieldAttrs = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<UniFieldAttr>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(new UniFieldAttrFormatter().Deserialize(ref reader, options));
            }
            value.FieldAttrs = __l1;
        }

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}


[MessagePackFormatter(typeof(UniRecordTypeFormatter))]
public struct UniRecordType {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniRecordType()
    {
        
        RecordName = string.Empty;
        
        RecordFields = [];
        
    }
    
    
    
    public required string RecordName { get; set; }
    
    
    public required List<UniRecordField> RecordFields { get; set; }
    
}

public class UniRecordTypeFormatter : IMessagePackFormatter<UniRecordType>
{
    public void Serialize(ref MessagePackWriter writer, UniRecordType value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(2);
        
        writer.Write(1);
        if (value.RecordName is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.RecordName);
        }

        
        writer.Write(2);
        if (value.RecordFields is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.RecordFields.Count);
            foreach (var __e0 in value.RecordFields)
            {
                new UniRecordFieldFormatter().Serialize(ref writer, __e0, options);
            }
        }

        
    }

    public UniRecordType Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniRecordType();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.RecordName = reader.ReadString()!;

                    break;
                }
                
                case 2:
                {
        if (reader.TryReadNil())
        {
            value.RecordFields = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<UniRecordField>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(new UniRecordFieldFormatter().Deserialize(ref reader, options));
            }
            value.RecordFields = __l1;
        }

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}