// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniResultTypeFormatter))]
public struct UniResultType {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniResultType()
    {
        
        Ok = default;
        
        Err = default;
        
    }
    
    
    
    public UniDataType? Ok { get; set; }
    
    
    public UniDataType? Err { get; set; }
    
}

public class UniResultTypeFormatter : IMessagePackFormatter<UniResultType>
{
    public void Serialize(ref MessagePackWriter writer, UniResultType value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order). WIT option fields are omitted
        // when they hold no value (proto3 presence semantics); decode
        // treats a missing key as the default.
        writer.WriteMapHeader(2 - 1 + (value.Ok is not null ? 1 : 0) - 1 + (value.Err is not null ? 1 : 0));
        
        
        if (value.Ok is not null)
        {
            writer.Write(1);
        if (value.Ok is null)
        {
            writer.WriteNil();
        }
        else
        {
            new UniDataTypeFormatter().Serialize(ref writer, value.Ok, options);
        }

        }
        
        
        
        if (value.Err is not null)
        {
            writer.Write(2);
        if (value.Err is null)
        {
            writer.WriteNil();
        }
        else
        {
            new UniDataTypeFormatter().Serialize(ref writer, value.Err, options);
        }

        }
        
        
    }

    public UniResultType Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniResultType();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.Ok = new UniDataTypeFormatter().Deserialize(ref reader, options);

                    break;
                }
                
                case 2:
                {
        value.Err = new UniDataTypeFormatter().Deserialize(ref reader, options);

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}