// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniSqlParamFormatter))]
public struct UniSqlParam {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniSqlParam()
    {
        
        Params = [];
        
        ParamNames = default;
        
    }
    
    
    
    public required List<UniDataValue> Params { get; set; }
    
    
    public List<string>? ParamNames { get; set; }
    
}

public class UniSqlParamFormatter : IMessagePackFormatter<UniSqlParam>
{
    public void Serialize(ref MessagePackWriter writer, UniSqlParam value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order). WIT option fields are omitted
        // when they hold no value (proto3 presence semantics); decode
        // treats a missing key as the default.
        writer.WriteMapHeader(2 - 1 + (value.ParamNames is not null ? 1 : 0));
        
        
        writer.Write(1);
        if (value.Params is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.Params.Count);
            foreach (var __e0 in value.Params)
            {
                new UniDataValueFormatter().Serialize(ref writer, __e0, options);
            }
        }

        
        
        
        if (value.ParamNames is not null)
        {
            writer.Write(2);
        if (value.ParamNames is null)
        {
            writer.WriteNil();
        }
        else
        {
            if (value.ParamNames is null)
            {
                writer.WriteNil();
            }
            else
            {
                writer.WriteArrayHeader(value.ParamNames.Count);
                foreach (var __e0 in value.ParamNames)
                {
                    if (__e0 is null)
                    {
                        writer.WriteNil();
                    }
                    else
                    {
                        writer.Write(__e0);
                    }
                }
            }
        }

        }
        
        
    }

    public UniSqlParam Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniSqlParam();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        if (reader.TryReadNil())
        {
            value.Params = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<UniDataValue>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(new UniDataValueFormatter().Deserialize(ref reader, options));
            }
            value.Params = __l1;
        }

                    break;
                }
                
                case 2:
                {
        value.ParamNames = MessagePackSerializer.Deserialize<List<string>?>(ref reader, options);

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}