// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniSqlStmtFormatter))]
public struct UniSqlStmt {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniSqlStmt()
    {
        
        SqlString = string.Empty;
        
    }
    
    
    
    public required string SqlString { get; set; }
    
}

public class UniSqlStmtFormatter : IMessagePackFormatter<UniSqlStmt>
{
    public void Serialize(ref MessagePackWriter writer, UniSqlStmt value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(1);
        
        writer.Write(1);
        if (value.SqlString is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.SqlString);
        }

        
    }

    public UniSqlStmt Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniSqlStmt();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.SqlString = reader.ReadString()!;

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}