// Generated by mudu_gen. Do not edit manually.
namespace mududb.types {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




[MessagePackFormatter(typeof(UniTupleRowFormatter))]
public struct UniTupleRow {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UniTupleRow()
    {
        
        Fields = [];
        
    }
    
    
    
    public required List<UniDataValue> Fields { get; set; }
    
}

public class UniTupleRowFormatter : IMessagePackFormatter<UniTupleRow>
{
    public void Serialize(ref MessagePackWriter writer, UniTupleRow value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(1);
        
        writer.Write(1);
        if (value.Fields is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.Fields.Count);
            foreach (var __e0 in value.Fields)
            {
                new UniDataValueFormatter().Serialize(ref writer, __e0, options);
            }
        }

        
    }

    public UniTupleRow Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new UniTupleRow();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        if (reader.TryReadNil())
        {
            value.Fields = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<UniDataValue>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(new UniDataValueFormatter().Deserialize(ref reader, options));
            }
            value.Fields = __l1;
        }

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

}