[package]
name = "mudu_wasm"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]

[dependencies]
mudu = { workspace = true }
mudu_macro = { workspace = true }
sys_interface = { workspace = true }