[env]
# WASM filename
WASM_FILE = "mudu_wasm.wasm"

# output wasm module folder in project
WASM_DEST_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/wasm_module"

# build setting, default is release
PROFILE = "release"


[tasks.set-debug]
script_runner = "@shell"
# set for debug build
script = [
    "profile = \"debug\"",
    "set_env PROFILE = \"${profile}\"",
    "echo \"Build profile set to: ${profile}\""
]

[tasks.build-wasm]
# build WASM file
command = "cargo"
args = ["build", "--target", "wasm32-wasip1", "--${PROFILE}"]

[tasks.copy-wasm]

dependencies = ["copy-wasm-windows-task", "copy-wasm-unix-task"]


[tasks.copy-wasm-unix-task]
condition = { platforms = ["linux", "mac"] }
# copy WASM file to destination
script = [
    # build destination
    "mkdir -p ${WASM_DEST_DIR}",
    # copy file
    "copy ${CARGO_TARGET_DIR}/wasm32-wasip1/${PROFILE}/${WASM_FILE} ${WASM_DEST_DIR}",
    # output result
    "echo \"Copied ${source_path} to ${WASM_DEST_DIR}\""
]

[tasks.copy-wasm-windows-task]
condition = { platforms = ["windows"] }
script = '''
set WASM_DEST_DIR="%CARGO_MAKE_WORKING_DIRECTORY%\\wasm_module"
set WASM_SRC_PATH="%CARGO_MAKE_WORKING_DIRECTORY%\..\\target\\wasm32-wasip1\\%PROFILE%\\%WASM_FILE%"
mkdir "%WASM_DEST_DIR%"
echo %WASM_SRC_PATH%
echo %WASM_DEST_DIR%
echo copying WASM file...
copy /Y "%WASM_SRC_PATH%" "%WASM_DEST_DIR%"
'''

[tasks.build-release]
# build release WASM and copy
dependencies = ["build-wasm", "copy-wasm"]

[tasks.build-debug]
# build debug WASM and copy
dependencies = ["set-debug", "build-wasm", "copy-wasm"]

[tasks.build]
# default：build release
alias = "build-release"

[tasks.default]
alias = "build"