use crate:universal:uni-oid/uni-oid;
use crate:universal:uni-data-value/uni-data-value;


interface universal {
    record uni-procedure-param {
        procedure: u64,
        session: uni-oid,
        param-list: list<uni-data-value>
    }
}
