use crate:universal:uni-oid/uni-oid;
use crate:universal:uni-sql-stmt/uni-sql-stmt;
use crate:universal:uni-sql-param/uni-sql-param;
use crate:universal:uni-record-type/uni-record-type;

interface universal {
    record uni-query-argv {
        oid:uni-oid,
        query:uni-sql-stmt,
        param-list:uni-sql-param,
        param-desc: option<uni-record-type>,
    }
}