use crate:universal:uni-data-type/uni-data-type;

interface universal {
record uni-field-attr {
    attr-name: string,
    attr-value: string,
}

record uni-record-field {
    field-name: string,
    field-type: uni-data-type,
    field-attrs: list<uni-field-attr>
}

record uni-record-type {
    record-name:string,
    record-fields:list<uni-record-field>
}
}
