[package]
name = "mudu_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
sql_parser = {workspace = true}
mudu = {workspace = true}
mudu_gen = {workspace = true}
wasmtime = {version = "33.0.0"}
anyhow = "1.0.98"
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
bincode = { version = "2.0.1" , features = ["serde"]}
uuid = { version = "1.17.0", features = ["v4"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
postgres = {version = "0.19.10"}