// Generated by mudu_gen. Do not edit manually.

import { MpackWriter, MpackReader } from "./mpack";



// Records shared by the funcs below; note that the tree-sitter-wit


export class MuOid {
    
    
    h: u64 = 0;
    
    
    l: u64 = 0;
    
}

export class MuOidCodec {
    static encode(value: MuOid, writer: MpackWriter): void {
        writer.writeMapHeader(2);
        
        writer.writeU64(1);
        writer.writeU64(value.h);
        
        writer.writeU64(2);
        writer.writeU64(value.l);
        
    }

    static decode(reader: MpackReader): MuOid {
        const value = new MuOid();
        const count = reader.readMapHeader();
        for (let i: u32 = 0; i < count; i++) {
            const key = reader.readMapKey();
            
            
            if (key == 1) {
                value.h = reader.readU64();
            } 
            else if (key == 2) {
                value.l = reader.readU64();
            } else {
                reader.skipValue();
            }
            
        }
        return value;
    }
}



export class MuError {
    
    
    err_code: u32 = 0;
    
    
    err_msg: string = "";
    
    
    err_details: Uint8Array = new Uint8Array(0);
    
}

export class MuErrorCodec {
    static encode(value: MuError, writer: MpackWriter): void {
        writer.writeMapHeader(3);
        
        writer.writeU64(1);
        writer.writeU64(value.err_code as u64);
        
        writer.writeU64(2);
        writer.writeString(value.err_msg);
        
        writer.writeU64(3);
        writer.writeArrayHeader(value.err_details.length);
        for (let i = 0; i < value.err_details.length; i++) {
            writer.writeU64(value.err_details[i]);
        }
        
    }

    static decode(reader: MpackReader): MuError {
        const value = new MuError();
        const count = reader.readMapHeader();
        for (let i: u32 = 0; i < count; i++) {
            const key = reader.readMapKey();
            
            
            if (key == 1) {
                value.err_code = reader.readU64() as u32;
            } 
            else if (key == 2) {
                value.err_msg = reader.readString();
            } 
            else if (key == 3) {
                {
                    const n = reader.readArrayHeader() as i32;
                    const arr = new Uint8Array(n);
                    for (let i = 0; i < n; i++) {
                        arr[i] = reader.readU64() as u8;
                    }
                    value.err_details = arr;
                }
            } else {
                reader.skipValue();
            }
            
        }
        return value;
    }
}



export class MuEntry {
    
    
    key: Uint8Array = new Uint8Array(0);
    
    
    value: Uint8Array = new Uint8Array(0);
    
}

export class MuEntryCodec {
    static encode(value: MuEntry, writer: MpackWriter): void {
        writer.writeMapHeader(2);
        
        writer.writeU64(1);
        writer.writeArrayHeader(value.key.length);
        for (let i = 0; i < value.key.length; i++) {
            writer.writeU64(value.key[i]);
        }
        
        writer.writeU64(2);
        writer.writeArrayHeader(value.value.length);
        for (let i = 0; i < value.value.length; i++) {
            writer.writeU64(value.value[i]);
        }
        
    }

    static decode(reader: MpackReader): MuEntry {
        const value = new MuEntry();
        const count = reader.readMapHeader();
        for (let i: u32 = 0; i < count; i++) {
            const key = reader.readMapKey();
            
            
            if (key == 1) {
                {
                    const n = reader.readArrayHeader() as i32;
                    const arr = new Uint8Array(n);
                    for (let i = 0; i < n; i++) {
                        arr[i] = reader.readU64() as u8;
                    }
                    value.key = arr;
                }
            } 
            else if (key == 2) {
                {
                    const n = reader.readArrayHeader() as i32;
                    const arr = new Uint8Array(n);
                    for (let i = 0; i < n; i++) {
                        arr[i] = reader.readU64() as u8;
                    }
                    value.value = arr;
                }
            } else {
                reader.skipValue();
            }
            
        }
        return value;
    }
}

// Length in bytes of the fixed syscall payload header.
export const MSSP_HEADER_LEN: i32 = 16;
const MSSP_MAGIC: u32 = 0x4D535350;
const MSSP_VERSION: u32 = 1;

// Syscall message kinds carried in the header's `message_kind` field. The
// discriminants identify the WIT functions of this file and are pinned to
// their 1-based declaration order; `0` and unknown values are rejected by
// `decodeHeader`.
export enum MessageKind {
    
    
    Get = 1,
    
    
    Put = 2,
    
    
    Scan = 3,
    
}

// Convert a raw header value into a message kind; throws on `0` and unknown
// values.
export function messageKindFromU32(raw: u32): MessageKind {
    switch (raw) {
        
        case 1:
            return MessageKind.Get;
        
        case 2:
            return MessageKind.Put;
        
        case 3:
            return MessageKind.Scan;
        
        default:
            throw new Error(`MSSP unknown syscall message kind ${raw}`);
    }
}

// Encodes the fixed 16-byte header for `kind`.
export function encodeHeader(kind: MessageKind): Uint8Array {
    const out = new Uint8Array(MSSP_HEADER_LEN);
    writeBeU32(out, 0, MSSP_MAGIC);
    writeBeU32(out, 4, MSSP_VERSION);
    // flags at [8..12] stay zero.
    writeBeU32(out, 12, kind as u32);
    return out;
}

// Decodes and validates the fixed 16-byte header, returning the message
// kind; throws on any integrity violation.
export function decodeHeader(frame: Uint8Array): MessageKind {
    if (frame.length < MSSP_HEADER_LEN) {
        throw new Error(`MSSP header shorter than ${MSSP_HEADER_LEN} bytes (${frame.length})`);
    }
    const magic = readBeU32(frame, 0);
    if (magic !== MSSP_MAGIC) {
        throw new Error(`MSSP bad magic 0x${magic.toString(16)}, expected 0x${MSSP_MAGIC.toString(16)}`);
    }
    const version = readBeU32(frame, 4);
    if (version !== MSSP_VERSION) {
        throw new Error(`MSSP unsupported payload version ${version}, supported range is [1, 1]`);
    }
    const flags = readBeU32(frame, 8);
    if (flags !== 0) {
        throw new Error(`MSSP nonzero header flags 0x${flags.toString(16)}`);
    }
    return messageKindFromU32(readBeU32(frame, 12));
}

// Encodes a complete frame: the 16-byte header followed by `body`.
export function encodeFrame(kind: MessageKind, body: Uint8Array): Uint8Array {
    const out = new Uint8Array(MSSP_HEADER_LEN + body.length);
    out.set(encodeHeader(kind), 0);
    out.set(body, MSSP_HEADER_LEN);
    return out;
}

// Validates a frame, checks it carries the expected message kind, and
// returns the body.
export function expectFrameBody(frame: Uint8Array, expected: MessageKind): Uint8Array {
    const kind = decodeHeader(frame);
    if (kind !== expected) {
        const kindRaw = kind as u32;
        const expectedRaw = expected as u32;
        throw new Error(`MSSP unexpected syscall message kind ${kindRaw}, expected ${expectedRaw}`);
    }
    return frame.subarray(MSSP_HEADER_LEN);
}

function readBeU32(frame: Uint8Array, offset: i32): u32 {
    return ((frame[offset] as u32) << 24)
        | ((frame[offset + 1] as u32) << 16)
        | ((frame[offset + 2] as u32) << 8)
        | (frame[offset + 3] as u32);
}

function writeBeU32(out: Uint8Array, offset: i32, value: u32): void {
    out[offset] = (value >>> 24) as u8;
    out[offset + 1] = (value >>> 16) as u8;
    out[offset + 2] = (value >>> 8) as u8;
    out[offset + 3] = value as u8;
}




export class GetRequest {
    
    oid: MuOid = new MuOid();
    
    key: Uint8Array = new Uint8Array(0);
    
}


export function encodeGetRequest(oid: MuOid, key: Uint8Array): Uint8Array {
    const writer = new MpackWriter();
        writer.writeMapHeader(2);
        writer.writeU64(1);
        MuOidCodec.encode(oid, writer);
        writer.writeU64(2);
        writer.writeBin(key);
    return encodeFrame(MessageKind.Get, writer.toBytes());
}


export function decodeGetRequest(frame: Uint8Array): GetRequest {
    const reader = new MpackReader(expectFrameBody(frame, MessageKind.Get));
    const value = new GetRequest();
    const count = reader.readMapHeader();
    for (let i: u32 = 0; i < count; i++) {
        const key = reader.readMapKey();
        
        if (key == 1) {
            value.oid = MuOidCodec.decode(reader);
        } 
        else if (key == 2) {
            value.key = reader.readBin();
        } else {
            reader.skipValue();
        }
    }
    if (!reader.isDone()) {
        throw new Error("trailing bytes after syscall payload body");
    }
    return value;
}



export class GetResult {
    
    value: Uint8Array | null = null;
    
    error: MuError | null = null;

    
    static ok(value: Uint8Array | null): GetResult {
        const result = new GetResult();
        result.value = value;
        return result;
    }
    

    static err(error: MuError): GetResult {
        const result = new GetResult();
        result.error = error;
        return result;
    }

    get isOk(): bool {
        return this.error === null;
    }
}


export function encodeGetResult(result: GetResult): Uint8Array {
    const writer = new MpackWriter();
    writer.writeArrayHeader(2);
    const error = result.error;
    if (error !== null) {
        writer.writeU64(1);
        MuErrorCodec.encode(error!, writer);
    } else {
        writer.writeU64(0);
            {
                const opt = result.value;
                if (opt === null) {
                    writer.writeNil();
                } else {
                    writer.writeBin(opt!);
                }
            }
    }
    return encodeFrame(MessageKind.Get, writer.toBytes());
}

export function decodeGetResult(frame: Uint8Array): GetResult {
    const reader = new MpackReader(expectFrameBody(frame, MessageKind.Get));
    const count = reader.readArrayHeader();
    if (count !== 2) {
        throw new Error(`Expected array of length 2, got ${count}`);
    }
    const tag = reader.readU64() as u8;
    if (tag === 0) {
        const result = new GetResult();
            if (reader.tryNil()) {
                result.value = null;
            } else {
                result.value = reader.readBin();
            }
        if (!reader.isDone()) {
            throw new Error("trailing bytes after syscall payload body");
        }
        return result;
    }
    if (tag === 1) {
        const result = GetResult.err(MuErrorCodec.decode(reader));
        if (!reader.isDone()) {
            throw new Error("trailing bytes after syscall payload body");
        }
        return result;
    }
    throw new Error(`MSSP unknown result tag ${tag}, expected 0 (ok) or 1 (err)`);
}





export class PutRequest {
    
    oid: MuOid = new MuOid();
    
    entry: MuEntry = new MuEntry();
    
}


export function encodePutRequest(oid: MuOid, entry: MuEntry): Uint8Array {
    const writer = new MpackWriter();
        writer.writeMapHeader(2);
        writer.writeU64(1);
        MuOidCodec.encode(oid, writer);
        writer.writeU64(2);
        MuEntryCodec.encode(entry, writer);
    return encodeFrame(MessageKind.Put, writer.toBytes());
}


export function decodePutRequest(frame: Uint8Array): PutRequest {
    const reader = new MpackReader(expectFrameBody(frame, MessageKind.Put));
    const value = new PutRequest();
    const count = reader.readMapHeader();
    for (let i: u32 = 0; i < count; i++) {
        const key = reader.readMapKey();
        
        if (key == 1) {
            value.oid = MuOidCodec.decode(reader);
        } 
        else if (key == 2) {
            value.entry = MuEntryCodec.decode(reader);
        } else {
            reader.skipValue();
        }
    }
    if (!reader.isDone()) {
        throw new Error("trailing bytes after syscall payload body");
    }
    return value;
}



export class PutResult {
    
    error: MuError | null = null;

    
    static ok(): PutResult {
        return new PutResult();
    }
    

    static err(error: MuError): PutResult {
        const result = new PutResult();
        result.error = error;
        return result;
    }

    get isOk(): bool {
        return this.error === null;
    }
}


export function encodePutResult(result: PutResult): Uint8Array {
    const writer = new MpackWriter();
    writer.writeArrayHeader(2);
    const error = result.error;
    if (error !== null) {
        writer.writeU64(1);
        MuErrorCodec.encode(error!, writer);
    } else {
        // unit success: the `0u8` placeholder payload
        writer.writeU64(0);
        writer.writeU64(0);
    }
    return encodeFrame(MessageKind.Put, writer.toBytes());
}

export function decodePutResult(frame: Uint8Array): PutResult {
    const reader = new MpackReader(expectFrameBody(frame, MessageKind.Put));
    const count = reader.readArrayHeader();
    if (count !== 2) {
        throw new Error(`Expected array of length 2, got ${count}`);
    }
    const tag = reader.readU64() as u8;
    if (tag === 0) {
        // consume the `0u8` placeholder payload
        reader.readU64();
        if (!reader.isDone()) {
            throw new Error("trailing bytes after syscall payload body");
        }
        return new PutResult();
    }
    if (tag === 1) {
        const result = PutResult.err(MuErrorCodec.decode(reader));
        if (!reader.isDone()) {
            throw new Error("trailing bytes after syscall payload body");
        }
        return result;
    }
    throw new Error(`MSSP unknown result tag ${tag}, expected 0 (ok) or 1 (err)`);
}





export class ScanRequest {
    
    oid: MuOid = new MuOid();
    
    prefix: Uint8Array = new Uint8Array(0);
    
}


export function encodeScanRequest(oid: MuOid, prefix: Uint8Array): Uint8Array {
    const writer = new MpackWriter();
        writer.writeMapHeader(2);
        writer.writeU64(1);
        MuOidCodec.encode(oid, writer);
        writer.writeU64(2);
        writer.writeBin(prefix);
    return encodeFrame(MessageKind.Scan, writer.toBytes());
}


export function decodeScanRequest(frame: Uint8Array): ScanRequest {
    const reader = new MpackReader(expectFrameBody(frame, MessageKind.Scan));
    const value = new ScanRequest();
    const count = reader.readMapHeader();
    for (let i: u32 = 0; i < count; i++) {
        const key = reader.readMapKey();
        
        if (key == 1) {
            value.oid = MuOidCodec.decode(reader);
        } 
        else if (key == 2) {
            value.prefix = reader.readBin();
        } else {
            reader.skipValue();
        }
    }
    if (!reader.isDone()) {
        throw new Error("trailing bytes after syscall payload body");
    }
    return value;
}



export class ScanResult {
    
    value: Array<MuEntry> = new Array<MuEntry>(0);
    
    error: MuError | null = null;

    
    static ok(value: Array<MuEntry>): ScanResult {
        const result = new ScanResult();
        result.value = value;
        return result;
    }
    

    static err(error: MuError): ScanResult {
        const result = new ScanResult();
        result.error = error;
        return result;
    }

    get isOk(): bool {
        return this.error === null;
    }
}


export function encodeScanResult(result: ScanResult): Uint8Array {
    const writer = new MpackWriter();
    writer.writeArrayHeader(2);
    const error = result.error;
    if (error !== null) {
        writer.writeU64(1);
        MuErrorCodec.encode(error!, writer);
    } else {
        writer.writeU64(0);
            writer.writeArrayHeader(result.value.length);
            for (let i = 0; i < result.value.length; i++) {
                const item = result.value[i];
                MuEntryCodec.encode(item, writer);
            }
    }
    return encodeFrame(MessageKind.Scan, writer.toBytes());
}

export function decodeScanResult(frame: Uint8Array): ScanResult {
    const reader = new MpackReader(expectFrameBody(frame, MessageKind.Scan));
    const count = reader.readArrayHeader();
    if (count !== 2) {
        throw new Error(`Expected array of length 2, got ${count}`);
    }
    const tag = reader.readU64() as u8;
    if (tag === 0) {
        const result = new ScanResult();
            {
                const n = reader.readArrayHeader() as i32;
                const arr = new Array<MuEntry>(n);
                for (let i = 0; i < n; i++) {
                    arr[i] = MuEntryCodec.decode(reader);
                }
                result.value = arr;
            }
        if (!reader.isDone()) {
            throw new Error("trailing bytes after syscall payload body");
        }
        return result;
    }
    if (tag === 1) {
        const result = ScanResult.err(MuErrorCodec.decode(reader));
        if (!reader.isDone()) {
            throw new Error("trailing bytes after syscall payload body");
        }
        return result;
    }
    throw new Error(`MSSP unknown result tag ${tag}, expected 0 (ok) or 1 (err)`);
}

