// Generated by mudu_gen. Do not edit manually.
namespace MuduDb {

using MessagePack;
using MessagePack.Formatters;
using System.Collections.Generic;




// Records shared by the funcs below; note that the tree-sitter-wit

[MessagePackFormatter(typeof(MuOidFormatter))]
public struct MuOid {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public MuOid()
    {
        
        H = 0;
        
        L = 0;
        
    }
    
    
    
    public ulong H { get; set; }
    
    
    public ulong L { get; set; }
    
}

public class MuOidFormatter : IMessagePackFormatter<MuOid>
{
    public void Serialize(ref MessagePackWriter writer, MuOid value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(2);
        
        writer.Write(1);
        writer.Write(value.H);

        
        writer.Write(2);
        writer.Write(value.L);

        
    }

    public MuOid Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new MuOid();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.H = reader.ReadUInt64();

                    break;
                }
                
                case 2:
                {
        value.L = reader.ReadUInt64();

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}


[MessagePackFormatter(typeof(MuErrorFormatter))]
public struct MuError {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public MuError()
    {
        
        ErrCode = 0;
        
        ErrMsg = string.Empty;
        
        ErrDetails = [];
        
    }
    
    
    
    public uint ErrCode { get; set; }
    
    
    public required string ErrMsg { get; set; }
    
    
    public required List<byte> ErrDetails { get; set; }
    
}

public class MuErrorFormatter : IMessagePackFormatter<MuError>
{
    public void Serialize(ref MessagePackWriter writer, MuError value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(3);
        
        writer.Write(1);
        writer.Write(value.ErrCode);

        
        writer.Write(2);
        if (value.ErrMsg is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.Write(value.ErrMsg);
        }

        
        writer.Write(3);
        if (value.ErrDetails is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.ErrDetails.Count);
            foreach (var __e0 in value.ErrDetails)
            {
                writer.Write(__e0);
            }
        }

        
    }

    public MuError Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new MuError();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        value.ErrCode = reader.ReadUInt32();

                    break;
                }
                
                case 2:
                {
        value.ErrMsg = reader.ReadString()!;

                    break;
                }
                
                case 3:
                {
        if (reader.TryReadNil())
        {
            value.ErrDetails = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<byte>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(reader.ReadByte());
            }
            value.ErrDetails = __l1;
        }

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}


[MessagePackFormatter(typeof(MuEntryFormatter))]
public struct MuEntry {
    
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public MuEntry()
    {
        
        Key = [];
        
        Value = [];
        
    }
    
    
    
    public required List<byte> Key { get; set; }
    
    
    public required List<byte> Value { get; set; }
    
}

public class MuEntryFormatter : IMessagePackFormatter<MuEntry>
{
    public void Serialize(ref MessagePackWriter writer, MuEntry value, MessagePackSerializerOptions options)
    {
        // The record encodes as a MessagePack map keyed by the 1-based field
        // numbers (WIT declaration order).
        writer.WriteMapHeader(2);
        
        writer.Write(1);
        if (value.Key is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.Key.Count);
            foreach (var __e0 in value.Key)
            {
                writer.Write(__e0);
            }
        }

        
        writer.Write(2);
        if (value.Value is null)
        {
            writer.WriteNil();
        }
        else
        {
            writer.WriteArrayHeader(value.Value.Count);
            foreach (var __e0 in value.Value)
            {
                writer.Write(__e0);
            }
        }

        
    }

    public MuEntry Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        // Decode is lenient: integer keys of any MessagePack width are
        // accepted, non-integer and unknown keys are skipped, key order is
        // arbitrary, and missing fields keep the constructor defaults
        // (proto3 semantics).
        var count = reader.ReadMapHeader();
        var value = new MuEntry();
        for (var __i = 0; __i < count; __i++)
        {
            if (reader.NextMessagePackType != MessagePackType.Integer)
            {
                reader.Skip();
                reader.Skip();
                continue;
            }

            switch (reader.ReadInt64())
            {
                
                case 1:
                {
        if (reader.TryReadNil())
        {
            value.Key = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<byte>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(reader.ReadByte());
            }
            value.Key = __l1;
        }

                    break;
                }
                
                case 2:
                {
        if (reader.TryReadNil())
        {
            value.Value = null!;
        }
        else
        {
            var __c1 = reader.ReadArrayHeader();
            var __l1 = new List<byte>(__c1);
            for (var __i1 = 0; __i1 < __c1; __i1++)
            {
                __l1.Add(reader.ReadByte());
            }
            value.Value = __l1;
        }

                    break;
                }
                
                default:
                    reader.Skip();
                    break;
            }
        }

        return value;
    }
}

/// Syscall message kinds carried in the MSSP header's `message_kind` field.
/// The discriminants identify the WIT functions of this file and are pinned
/// to their 1-based declaration order; `0` and unknown values are rejected by
/// <see cref="SyscallPayload.DecodeFrame"/>.
public enum MessageKind : uint
{
    
    
    Get = 1,
    
    
    Put = 2,
    
    
    Scan = 3,
    
}

/// Outcome of a decoded MSSP result body: either the success value or the
/// <see cref="MuError"/> carried by the `[1, error]` arm.
public readonly struct SyscallResult<T>
{
    private readonly T value;

    internal SyscallResult(T value)
    {
        this.value = value;
        Error = null;
    }

    internal SyscallResult(MuError error)
    {
        value = default!;
        Error = error;
    }

    public bool IsOk => Error is null;

    public bool IsErr => Error is not null;

    public T? Value => IsOk ? value : default;

    public MuError? Error { get; }
}

/// SyscallPayload v1 (MSSP) codec: the 16-byte header plus a MessagePack body.
///
/// Every syscall request and response is a self-describing frame: a 16-byte
/// big-endian header (magic `MSSP`, version 1, reserved flags 0, message
/// kind) followed by a single MessagePack body. Request bodies are
/// integer-keyed MessagePack maps of the WIT-declared arguments (1-based
/// parameter numbers); result bodies are `[ok_tag, value]` pairs with `0` =
/// ok and `1` = err; unit results use the `[0, 0]` placeholder form. Record
/// arguments nest as their own integer-keyed maps.
///
/// Error style: frame/header/structural violations (bad magic, unsupported
/// version, nonzero flags, unknown or mismatched kind, malformed bodies)
/// throw <see cref="global::System.IO.InvalidDataException"/> — they are
/// protocol errors, not business errors. Business errors carried in the
/// `[1, MuError]` result arm are returned as values.
public static class SyscallPayload
{
    /// Length in bytes of the fixed syscall payload header.
    public const int HeaderLen = 16;

    /// Frame magic: ASCII `MSSP`.
    public const uint Magic = 0x4D535350;

    /// The only payload format version this codec reads and writes.
    public const uint Version = 1;

    /// Encodes the fixed 16-byte header for `kind`.
    public static byte[] EncodeHeader(MessageKind kind)
    {
        var header = new byte[HeaderLen];
        global::System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(new global::System.Span<byte>(header, 0, 4), Magic);
        global::System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(new global::System.Span<byte>(header, 4, 4), Version);
        // flags at [8..12] stay zero.
        global::System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(new global::System.Span<byte>(header, 12, 4), (uint)kind);
        return header;
    }

    /// Encodes a complete frame: the 16-byte header followed by `body`.
    public static byte[] EncodeFrame(MessageKind kind, global::System.ReadOnlySpan<byte> body)
    {
        var frame = new byte[HeaderLen + body.Length];
        EncodeHeader(kind).CopyTo(frame, 0);
        body.CopyTo(new global::System.Span<byte>(frame, HeaderLen, body.Length));
        return frame;
    }

    /// Validates the header and returns the declared message kind.
    public static MessageKind DecodeHeader(global::System.ReadOnlyMemory<byte> frame)
    {
        if (frame.Length < HeaderLen)
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP header shorter than {HeaderLen} bytes ({frame.Length})");
        }

        var span = frame.Span;
        var magic = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(span.Slice(0, 4));
        if (magic != Magic)
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP bad magic 0x{magic:X8}, expected 0x{Magic:X8}");
        }

        var version = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(span.Slice(4, 4));
        if (version != Version)
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP unsupported payload version {version}, supported range is [1, 1]");
        }

        var flags = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(span.Slice(8, 4));
        if (flags != 0)
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP nonzero header flags 0x{flags:X8}");
        }

        var kindRaw = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(span.Slice(12, 4));
        if (kindRaw == 0 || !global::System.Enum.IsDefined((MessageKind)kindRaw))
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP unknown syscall message kind {kindRaw}");
        }

        return (MessageKind)kindRaw;
    }

    /// Splits a frame into its validated message kind and body.
    public static (MessageKind Kind, global::System.ReadOnlyMemory<byte> Body) DecodeFrame(
        global::System.ReadOnlyMemory<byte> frame)
    {
        var kind = DecodeHeader(frame);
        return (kind, frame.Slice(HeaderLen));
    }

    /// Validates a frame, checks it carries the expected message kind, and
    /// returns the body.
    public static global::System.ReadOnlyMemory<byte> ExpectFrame(
        MessageKind expected,
        global::System.ReadOnlyMemory<byte> frame)
    {
        var (kind, body) = DecodeFrame(frame);
        if (kind != expected)
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP unexpected syscall message kind {(uint)kind}, expected {(uint)expected}");
        }

        return body;
    }

    // ---- request framing ----

    /// Encodes a request frame whose body is the integer-keyed MessagePack
    /// map `{1: arg}` (1-based WIT parameter numbers).
    public static byte[] EncodeRequestFrame<T1>(
        MessageKind kind,
        T1 arg1,
        MessagePackSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteMapHeader(1);
        writer.Write(1);
        UniCodec.SerializeValue(ref writer, arg1, options);
        writer.Flush();
        return EncodeFrame(kind, buffer.WrittenSpan);
    }

    /// Encodes a request frame whose body is the map `{1: arg1, 2: arg2}`.
    public static byte[] EncodeRequestFrame<T1, T2>(
        MessageKind kind,
        T1 arg1,
        T2 arg2,
        MessagePackSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteMapHeader(2);
        writer.Write(1);
        UniCodec.SerializeValue(ref writer, arg1, options);
        writer.Write(2);
        UniCodec.SerializeValue(ref writer, arg2, options);
        writer.Flush();
        return EncodeFrame(kind, buffer.WrittenSpan);
    }

    /// Encodes a request frame whose body is the map `{1: arg1, 2: arg2, 3: arg3}`.
    public static byte[] EncodeRequestFrame<T1, T2, T3>(
        MessageKind kind,
        T1 arg1,
        T2 arg2,
        T3 arg3,
        MessagePackSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteMapHeader(3);
        writer.Write(1);
        UniCodec.SerializeValue(ref writer, arg1, options);
        writer.Write(2);
        UniCodec.SerializeValue(ref writer, arg2, options);
        writer.Write(3);
        UniCodec.SerializeValue(ref writer, arg3, options);
        writer.Flush();
        return EncodeFrame(kind, buffer.WrittenSpan);
    }

    /// Encodes a request frame whose body is the map `{1: arg1, 2: arg2, 3: arg3, 4: arg4}`.
    public static byte[] EncodeRequestFrame<T1, T2, T3, T4>(
        MessageKind kind,
        T1 arg1,
        T2 arg2,
        T3 arg3,
        T4 arg4,
        MessagePackSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteMapHeader(4);
        writer.Write(1);
        UniCodec.SerializeValue(ref writer, arg1, options);
        writer.Write(2);
        UniCodec.SerializeValue(ref writer, arg2, options);
        writer.Write(3);
        UniCodec.SerializeValue(ref writer, arg3, options);
        writer.Write(4);
        UniCodec.SerializeValue(ref writer, arg4, options);
        writer.Flush();
        return EncodeFrame(kind, buffer.WrittenSpan);
    }

    /// Encodes a request frame whose body is the map `{1: arg1, 2: arg2, 3: arg3, 4: arg4, 5: arg5}`.
    public static byte[] EncodeRequestFrame<T1, T2, T3, T4, T5>(
        MessageKind kind,
        T1 arg1,
        T2 arg2,
        T3 arg3,
        T4 arg4,
        T5 arg5,
        MessagePackSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteMapHeader(5);
        writer.Write(1);
        UniCodec.SerializeValue(ref writer, arg1, options);
        writer.Write(2);
        UniCodec.SerializeValue(ref writer, arg2, options);
        writer.Write(3);
        UniCodec.SerializeValue(ref writer, arg3, options);
        writer.Write(4);
        UniCodec.SerializeValue(ref writer, arg4, options);
        writer.Write(5);
        UniCodec.SerializeValue(ref writer, arg5, options);
        writer.Flush();
        return EncodeFrame(kind, buffer.WrittenSpan);
    }

    /// Decodes a request body holding the argument map of one WIT parameter.
    public static T1 DecodeRequestBody<T1>(
        global::System.ReadOnlyMemory<byte> body,
        MessagePackSerializerOptions? options = null)
    {
        var reader = new MessagePackReader(body);
        var count = reader.ReadMapHeader();
        var arg1 = UniCodec.DefaultValue<T1>();
        for (var __i = 0; __i < count; __i++)
        {
            switch (ReadRequestKey(ref reader))
            {
                case 1:
                    arg1 = UniCodec.DeserializeValue<T1>(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }
        }

        EnsureConsumed(ref reader, body);
        return arg1!;
    }

    /// Decodes a request body holding the argument map of two WIT parameters.
    public static (T1, T2) DecodeRequestBody<T1, T2>(
        global::System.ReadOnlyMemory<byte> body,
        MessagePackSerializerOptions? options = null)
    {
        var reader = new MessagePackReader(body);
        var count = reader.ReadMapHeader();
        var arg1 = UniCodec.DefaultValue<T1>();
        var arg2 = UniCodec.DefaultValue<T2>();
        for (var __i = 0; __i < count; __i++)
        {
            switch (ReadRequestKey(ref reader))
            {
                case 1:
                    arg1 = UniCodec.DeserializeValue<T1>(ref reader, options);
                    break;
                case 2:
                    arg2 = UniCodec.DeserializeValue<T2>(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }
        }

        EnsureConsumed(ref reader, body);
        return (arg1!, arg2!);
    }

    /// Decodes a request body holding the argument map of three WIT parameters.
    public static (T1, T2, T3) DecodeRequestBody<T1, T2, T3>(
        global::System.ReadOnlyMemory<byte> body,
        MessagePackSerializerOptions? options = null)
    {
        var reader = new MessagePackReader(body);
        var count = reader.ReadMapHeader();
        var arg1 = UniCodec.DefaultValue<T1>();
        var arg2 = UniCodec.DefaultValue<T2>();
        var arg3 = UniCodec.DefaultValue<T3>();
        for (var __i = 0; __i < count; __i++)
        {
            switch (ReadRequestKey(ref reader))
            {
                case 1:
                    arg1 = UniCodec.DeserializeValue<T1>(ref reader, options);
                    break;
                case 2:
                    arg2 = UniCodec.DeserializeValue<T2>(ref reader, options);
                    break;
                case 3:
                    arg3 = UniCodec.DeserializeValue<T3>(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }
        }

        EnsureConsumed(ref reader, body);
        return (arg1!, arg2!, arg3!);
    }

    /// Decodes a request body holding the argument map of four WIT parameters.
    public static (T1, T2, T3, T4) DecodeRequestBody<T1, T2, T3, T4>(
        global::System.ReadOnlyMemory<byte> body,
        MessagePackSerializerOptions? options = null)
    {
        var reader = new MessagePackReader(body);
        var count = reader.ReadMapHeader();
        var arg1 = UniCodec.DefaultValue<T1>();
        var arg2 = UniCodec.DefaultValue<T2>();
        var arg3 = UniCodec.DefaultValue<T3>();
        var arg4 = UniCodec.DefaultValue<T4>();
        for (var __i = 0; __i < count; __i++)
        {
            switch (ReadRequestKey(ref reader))
            {
                case 1:
                    arg1 = UniCodec.DeserializeValue<T1>(ref reader, options);
                    break;
                case 2:
                    arg2 = UniCodec.DeserializeValue<T2>(ref reader, options);
                    break;
                case 3:
                    arg3 = UniCodec.DeserializeValue<T3>(ref reader, options);
                    break;
                case 4:
                    arg4 = UniCodec.DeserializeValue<T4>(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }
        }

        EnsureConsumed(ref reader, body);
        return (arg1!, arg2!, arg3!, arg4!);
    }

    /// Decodes a request body holding the argument map of five WIT parameters.
    public static (T1, T2, T3, T4, T5) DecodeRequestBody<T1, T2, T3, T4, T5>(
        global::System.ReadOnlyMemory<byte> body,
        MessagePackSerializerOptions? options = null)
    {
        var reader = new MessagePackReader(body);
        var count = reader.ReadMapHeader();
        var arg1 = UniCodec.DefaultValue<T1>();
        var arg2 = UniCodec.DefaultValue<T2>();
        var arg3 = UniCodec.DefaultValue<T3>();
        var arg4 = UniCodec.DefaultValue<T4>();
        var arg5 = UniCodec.DefaultValue<T5>();
        for (var __i = 0; __i < count; __i++)
        {
            switch (ReadRequestKey(ref reader))
            {
                case 1:
                    arg1 = UniCodec.DeserializeValue<T1>(ref reader, options);
                    break;
                case 2:
                    arg2 = UniCodec.DeserializeValue<T2>(ref reader, options);
                    break;
                case 3:
                    arg3 = UniCodec.DeserializeValue<T3>(ref reader, options);
                    break;
                case 4:
                    arg4 = UniCodec.DeserializeValue<T4>(ref reader, options);
                    break;
                case 5:
                    arg5 = UniCodec.DeserializeValue<T5>(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }
        }

        EnsureConsumed(ref reader, body);
        return (arg1!, arg2!, arg3!, arg4!, arg5!);
    }

    /// Reads one request-map key. Non-integer keys are skipped outright (they
    /// cannot be WIT parameter numbers) and report -1 so the caller skips the
    /// value; integer keys of any MessagePack width are accepted (lenient
    /// decode).
    private static long ReadRequestKey(ref MessagePackReader reader)
    {
        if (reader.NextMessagePackType != MessagePackType.Integer)
        {
            reader.Skip();
            return -1;
        }

        return reader.ReadInt64();
    }

    // ---- result framing ----

    /// Encodes a success result body: `[0, value]`.
    public static byte[] EncodeResultBody<T>(T value, MessagePackSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteArrayHeader(2);
        writer.Write((byte)0);
        UniCodec.SerializeValue(ref writer, value, options);
        writer.Flush();
        return buffer.WrittenSpan.ToArray();
    }

    /// Encodes an error result body: `[1, MuError]`.
    public static byte[] EncodeResultErrorBody(MuError error, MessagePackSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteArrayHeader(2);
        writer.Write((byte)1);
        UniCodec.SerializeValue(ref writer, error, options);
        writer.Flush();
        return buffer.WrittenSpan.ToArray();
    }

    /// Encodes a unit success result body: `[0, 0]`.
    public static byte[] EncodeUnitResultBody()
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>();
        var writer = new MessagePackWriter(buffer);
        writer.WriteArrayHeader(2);
        writer.Write((byte)0);
        writer.Write((byte)0);
        writer.Flush();
        return buffer.WrittenSpan.ToArray();
    }

    /// Encodes a complete success result frame: header plus `[0, value]`.
    public static byte[] EncodeResultFrame<T>(MessageKind kind, T value, MessagePackSerializerOptions? options = null)
    {
        return EncodeFrame(kind, EncodeResultBody(value, options));
    }

    /// Encodes a complete error result frame: header plus `[1, MuError]`.
    public static byte[] EncodeResultErrorFrame(MessageKind kind, MuError error, MessagePackSerializerOptions? options = null)
    {
        return EncodeFrame(kind, EncodeResultErrorBody(error, options));
    }

    /// Encodes a complete unit success result frame: header plus `[0, 0]`.
    public static byte[] EncodeUnitResultFrame(MessageKind kind)
    {
        return EncodeFrame(kind, EncodeUnitResultBody());
    }

    /// Decodes a result frame body `[ok_tag, value]` into the success value
    /// or the carried <see cref="MuError"/>.
    public static SyscallResult<T> DecodeResultFrame<T>(
        MessageKind expected,
        byte[] frame,
        MessagePackSerializerOptions? options = null)
    {
        return DecodeResultBody<T>(ExpectFrame(expected, frame), options);
    }

    /// Decodes a result body `[ok_tag, value]`.
    public static SyscallResult<T> DecodeResultBody<T>(
        global::System.ReadOnlyMemory<byte> body,
        MessagePackSerializerOptions? options = null)
    {
        var reader = new MessagePackReader(body);
        ReadArrayHeader(ref reader, 2);
        var tag = reader.ReadByte();
        switch (tag)
        {
            case 0:
                var value = UniCodec.DeserializeValue<T>(ref reader, options);
                EnsureConsumed(ref reader, body);
                return new SyscallResult<T>(value!);
            case 1:
                var error = UniCodec.DeserializeValue<MuError>(ref reader, options);
                EnsureConsumed(ref reader, body);
                return new SyscallResult<T>(error);
            default:
                throw new global::System.IO.InvalidDataException(
                    $"MSSP unknown result tag {tag}, expected 0 (ok) or 1 (err)");
        }
    }

    /// Decodes a unit result frame (`[0, 0]` / `[1, MuError]`),
    /// returning the carried error or `null` on success.
    public static MuError? DecodeUnitResultFrame(
        MessageKind expected,
        byte[] frame,
        MessagePackSerializerOptions? options = null)
    {
        var body = ExpectFrame(expected, frame);
        var reader = new MessagePackReader(body);
        ReadArrayHeader(ref reader, 2);
        var tag = reader.ReadByte();
        switch (tag)
        {
            case 0:
                reader.Skip();
                EnsureConsumed(ref reader, body);
                return null;
            case 1:
                var error = UniCodec.DeserializeValue<MuError>(ref reader, options);
                EnsureConsumed(ref reader, body);
                return error;
            default:
                throw new global::System.IO.InvalidDataException(
                    $"MSSP unknown result tag {tag}, expected 0 (ok) or 1 (err)");
        }
    }

    private static void ReadArrayHeader(ref MessagePackReader reader, int expected)
    {
        var count = reader.ReadArrayHeader();
        if (count != expected)
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP expected MessagePack array of length {expected}, got {count}");
        }
    }

    private static void EnsureConsumed(ref MessagePackReader reader, global::System.ReadOnlyMemory<byte> body)
    {
        if (reader.Consumed != body.Length)
        {
            throw new global::System.IO.InvalidDataException(
                $"MSSP trailing bytes after MessagePack body ({reader.Consumed} of {body.Length} consumed)");
        }
    }
}

/// Resolver-free MessagePack (de)serialization used by
/// <see cref="SyscallPayload"/> body framing.
///
/// When the caller supplies explicit <see cref="MessagePackSerializerOptions"/>
/// every call delegates to <see cref="MessagePackSerializer"/> unchanged.
/// With `null` options the value is written/read directly: scalars and
/// strings use the minimal-width <see cref="MessagePackWriter"/>/
/// <see cref="MessagePackReader"/> primitives (byte-identical to the built-in
/// formatters the standard resolver would select), generated DTOs use their
/// attributed formatters, and arrays/`List{T}`/value tuples recurse
/// element-wise. The default path never constructs
/// <see cref="MessagePackSerializerOptions"/> — and therefore never touches
/// `MessagePackSecurity` (whose static initializer requires
/// `RandomNumberGenerator`) or the Reflection.Emit resolver chain — so the
/// generated codec runs on the wasi-wasm NativeAOT target where any options
/// construction throws <see cref="global::System.PlatformNotSupportedException"/>.
public static class UniCodec
{
    /// Serializes `value`, using the caller's options when supplied and the
    /// resolver-free path otherwise.
    public static void SerializeValue<T>(ref MessagePackWriter writer, T value, MessagePackSerializerOptions? options)
    {
        if (options is not null)
        {
            MessagePackSerializer.Serialize(ref writer, value, options);
            return;
        }

        SerializeObject(ref writer, value);
    }

    /// Deserializes a `T`, using the caller's options when supplied and the
    /// resolver-free path otherwise.
    public static T DeserializeValue<T>(ref MessagePackReader reader, MessagePackSerializerOptions? options)
    {
        if (options is not null)
        {
            return MessagePackSerializer.Deserialize<T>(ref reader, options)!;
        }

        return (T)DeserializeObject(ref reader, typeof(T))!;
    }

    /// The proto3-style default of a request argument whose key is absent
    /// from the request map: zero for value types, empty for strings, arrays
    /// and `List{T}`, `default` for everything else.
    public static T DefaultValue<T>()
    {
        var type = typeof(T);
        if (type == typeof(string))
        {
            return (T)(object)string.Empty;
        }

        if (type.IsArray)
        {
            return (T)(object)global::System.Array.CreateInstance(type.GetElementType()!, 0);
        }

        if (type.IsGenericType
            && type.GetGenericTypeDefinition() == typeof(global::System.Collections.Generic.List<>))
        {
            return (T)global::System.Activator.CreateInstance(type)!;
        }

        return default!;
    }

    private static void SerializeObject(ref MessagePackWriter writer, object? value)
    {
        switch (value)
        {
            case null:
                writer.WriteNil();
                return;
            case bool v:
                writer.Write(v);
                return;
            case byte v:
                writer.Write(v);
                return;
            case sbyte v:
                writer.Write(v);
                return;
            case short v:
                writer.Write(v);
                return;
            case ushort v:
                writer.Write(v);
                return;
            case int v:
                writer.Write(v);
                return;
            case uint v:
                writer.Write(v);
                return;
            case long v:
                writer.Write(v);
                return;
            case ulong v:
                writer.Write(v);
                return;
            case float v:
                writer.Write(v);
                return;
            case double v:
                writer.Write(v);
                return;
            case char v:
                // A WIT char travels as a single-character string, not the
                // ushort marker MessagePack-CSharp's own char write uses.
                writer.Write(v.ToString());
                return;
            case string v:
                writer.Write(v);
                return;
            case byte[] v:
                writer.Write(v);
                return;
            default:
                break;
        }

        var type = value.GetType();
        if (TrySerializeDto(ref writer, value))
        {
            return;
        }

        if (value is global::System.Runtime.CompilerServices.ITuple tuple)
        {
            writer.WriteArrayHeader(tuple.Length);
            for (var i = 0; i < tuple.Length; i++)
            {
                SerializeObject(ref writer, tuple[i]);
            }

            return;
        }

        if (type.IsEnum)
        {
            var underlying = global::System.Enum.GetUnderlyingType(type);
            if (global::System.Type.GetTypeCode(underlying) == global::System.TypeCode.UInt64)
            {
                writer.Write(global::System.Convert.ToUInt64(value, global::System.Globalization.CultureInfo.InvariantCulture));
            }
            else
            {
                writer.Write(global::System.Convert.ToInt64(value, global::System.Globalization.CultureInfo.InvariantCulture));
            }

            return;
        }

        if (value is global::System.Collections.ICollection collection)
        {
            writer.WriteArrayHeader(collection.Count);
            foreach (var item in collection)
            {
                SerializeObject(ref writer, item);
            }

            return;
        }

        throw new global::System.NotSupportedException(
            $"UniCodec cannot serialize a value of type {type} without MessagePackSerializerOptions");
    }

    private static object? DeserializeObject(ref MessagePackReader reader, global::System.Type type)
    {
        if (reader.TryReadNil())
        {
            return null;
        }

        if (type == typeof(string))
        {
            return reader.ReadString();
        }

        if (type == typeof(byte[]))
        {
            // Func-level blobs are MessagePack bin; the array-of-int form is
            // accepted leniently (it is the record-context shape of
            // `list<u8>`).
            if (reader.NextMessagePackType == MessagePackType.Array)
            {
                var count = reader.ReadArrayHeader();
                var array = new byte[count];
                for (var i = 0; i < count; i++)
                {
                    array[i] = reader.ReadByte();
                }

                return array;
            }

            var bytes = reader.ReadBytes();
            return bytes.HasValue ? global::System.Buffers.BuffersExtensions.ToArray(bytes.Value) : null;
        }

        if (type == typeof(bool))
        {
            return reader.ReadBoolean();
        }

        if (type == typeof(byte))
        {
            return reader.ReadByte();
        }

        if (type == typeof(sbyte))
        {
            return reader.ReadSByte();
        }

        if (type == typeof(short))
        {
            return reader.ReadInt16();
        }

        if (type == typeof(ushort))
        {
            return reader.ReadUInt16();
        }

        if (type == typeof(int))
        {
            return reader.ReadInt32();
        }

        if (type == typeof(uint))
        {
            return reader.ReadUInt32();
        }

        if (type == typeof(long))
        {
            return reader.ReadInt64();
        }

        if (type == typeof(ulong))
        {
            return reader.ReadUInt64();
        }

        if (type == typeof(float))
        {
            return reader.ReadSingle();
        }

        if (type == typeof(double))
        {
            return reader.ReadDouble();
        }

        if (type == typeof(char))
        {
            var text = reader.ReadString();
            if (text is { Length: 1 })
            {
                return text[0];
            }

            throw new global::System.IO.InvalidDataException(
                "MSSP expected a single-character string for a char value");
        }

        if (TryDeserializeDto(ref reader, type, out var dto))
        {
            return dto;
        }

        if (type.IsEnum)
        {
            var underlying = DeserializeObject(ref reader, global::System.Enum.GetUnderlyingType(type));
            return global::System.Enum.ToObject(type, underlying!);
        }

        if (type.IsArray)
        {
            var elementType = type.GetElementType()!;
            var count = reader.ReadArrayHeader();
            var array = global::System.Array.CreateInstance(elementType, (int)count);
            for (var i = 0; i < (int)count; i++)
            {
                array.SetValue(DeserializeObject(ref reader, elementType), i);
            }

            return array;
        }

        if (type.IsGenericType)
        {
            var definition = type.GetGenericTypeDefinition();
            if (definition == typeof(global::System.Collections.Generic.List<>))
            {
                var elementType = type.GenericTypeArguments[0];
                var count = reader.ReadArrayHeader();
                var list = (global::System.Collections.IList)global::System.Activator.CreateInstance(type, (int)count)!;
                for (var i = 0; i < (int)count; i++)
                {
                    list.Add(DeserializeObject(ref reader, elementType));
                }

                return list;
            }

            if (definition == typeof(global::System.Nullable<>))
            {
                return DeserializeObject(ref reader, type.GenericTypeArguments[0]);
            }

            if (definition == typeof(global::System.ValueTuple<,>) || definition == typeof(global::System.ValueTuple<,,>))
            {
                var elementTypes = type.GenericTypeArguments;
                var count = reader.ReadArrayHeader();
                if (count != elementTypes.Length)
                {
                    throw new global::System.IO.InvalidDataException(
                        $"MSSP expected MessagePack array of length {elementTypes.Length}, got {count}");
                }

                var items = new object?[elementTypes.Length];
                for (var i = 0; i < elementTypes.Length; i++)
                {
                    items[i] = DeserializeObject(ref reader, elementTypes[i]);
                }

                return global::System.Activator.CreateInstance(type, items)!;
            }
        }

        throw new global::System.NotSupportedException(
            $"UniCodec cannot deserialize type {type} without MessagePackSerializerOptions");
    }

    /// Writes a generated DTO with its own formatter; returns `false` when
    /// `value` is not one of the generated universal types. The static type
    /// switch keeps every formatter rooted under IL trimming/AOT (no
    /// resolver, no attribute reflection).
    private static bool TrySerializeDto(ref MessagePackWriter writer, object value)
    {
        switch (value)
        {
            
            case MuEntry v:
                new MuEntryFormatter().Serialize(ref writer, v, null!);
                return true;
            
            case MuError v:
                new MuErrorFormatter().Serialize(ref writer, v, null!);
                return true;
            
            case MuOid v:
                new MuOidFormatter().Serialize(ref writer, v, null!);
                return true;
            
            default:
                return false;
        }
    }

    /// Reads a generated DTO with its own formatter into the boxed `dto`;
    /// returns `false` when `type` is not one of the generated universal
    /// types.
    private static bool TryDeserializeDto(ref MessagePackReader reader, global::System.Type type, out object? dto)
    {
        
        if (type == typeof(MuEntry))
        {
            dto = new MuEntryFormatter().Deserialize(ref reader, null!);
            return true;
        }

        
        if (type == typeof(MuError))
        {
            dto = new MuErrorFormatter().Deserialize(ref reader, null!);
            return true;
        }

        
        if (type == typeof(MuOid))
        {
            dto = new MuOidFormatter().Deserialize(ref reader, null!);
            return true;
        }

        
        dto = null;
        return false;
    }
}


public static partial class SimpleFunc
{
    
    /// Encodes a `Get` request frame.
    public static byte[] EncodeGetRequest(MuOid oid, byte[] key, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.EncodeRequestFrame(MessageKind.Get, oid, key, options);
    }

    /// Decodes a `Get` request frame's argument map into its
    /// positional values.
    public static (MuOid, byte[]) DecodeGetRequest(byte[] frame, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.DecodeRequestBody<MuOid, byte[]>(
            SyscallPayload.ExpectFrame(MessageKind.Get, frame), options);
    }
    

    
    /// Encodes a `Get` result frame: body `[0, value]` or
    /// `[1, error]`.
    public static byte[] EncodeGetResult(SyscallResult<byte[]?> result, MessagePackSerializerOptions? options = null)
    {
        return result.IsOk
            ? SyscallPayload.EncodeResultFrame(MessageKind.Get, result.Value!, options)
            : SyscallPayload.EncodeResultErrorFrame(MessageKind.Get, result.Error.GetValueOrDefault(), options);
    }

    /// Decodes a `Get` result frame.
    public static SyscallResult<byte[]?> DecodeGetResult(byte[] frame, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.DecodeResultFrame<byte[]?>(MessageKind.Get, frame, options);
    }
    
}


public static partial class SimpleFunc
{
    
    /// Encodes a `Put` request frame.
    public static byte[] EncodePutRequest(MuOid oid, MuEntry entry, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.EncodeRequestFrame(MessageKind.Put, oid, entry, options);
    }

    /// Decodes a `Put` request frame's argument map into its
    /// positional values.
    public static (MuOid, MuEntry) DecodePutRequest(byte[] frame, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.DecodeRequestBody<MuOid, MuEntry>(
            SyscallPayload.ExpectFrame(MessageKind.Put, frame), options);
    }
    

    
    /// Encodes a `Put` unit result frame: body `[0, 0]` or
    /// `[1, error]`; pass `null` for success.
    public static byte[] EncodePutResult(MuError? error, MessagePackSerializerOptions? options = null)
    {
        return error is null
            ? SyscallPayload.EncodeUnitResultFrame(MessageKind.Put)
            : SyscallPayload.EncodeResultErrorFrame(MessageKind.Put, error.Value, options);
    }

    /// Decodes a `Put` unit result frame, returning the carried
    /// error or `null` on success.
    public static MuError? DecodePutResult(byte[] frame, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.DecodeUnitResultFrame(MessageKind.Put, frame, options);
    }
    
}


public static partial class SimpleFunc
{
    
    /// Encodes a `Scan` request frame.
    public static byte[] EncodeScanRequest(MuOid oid, byte[] prefix, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.EncodeRequestFrame(MessageKind.Scan, oid, prefix, options);
    }

    /// Decodes a `Scan` request frame's argument map into its
    /// positional values.
    public static (MuOid, byte[]) DecodeScanRequest(byte[] frame, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.DecodeRequestBody<MuOid, byte[]>(
            SyscallPayload.ExpectFrame(MessageKind.Scan, frame), options);
    }
    

    
    /// Encodes a `Scan` result frame: body `[0, value]` or
    /// `[1, error]`.
    public static byte[] EncodeScanResult(SyscallResult<List<MuEntry>> result, MessagePackSerializerOptions? options = null)
    {
        return result.IsOk
            ? SyscallPayload.EncodeResultFrame(MessageKind.Scan, result.Value!, options)
            : SyscallPayload.EncodeResultErrorFrame(MessageKind.Scan, result.Error.GetValueOrDefault(), options);
    }

    /// Decodes a `Scan` result frame.
    public static SyscallResult<List<MuEntry>> DecodeScanResult(byte[] frame, MessagePackSerializerOptions? options = null)
    {
        return SyscallPayload.DecodeResultFrame<List<MuEntry>>(MessageKind.Scan, frame, options);
    }
    
}

}