// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package system represents the imported interface "mududb:api/system".
package system

import (
	"go.bytecodealliance.org/cm"
)

// Query represents the imported function "query".
//
//	query: func(query-in: list<u8>) -> list<u8>
//
//go:nosplit
func Query(queryIn cm.List[uint8]) (result cm.List[uint8]) {
	queryIn0, queryIn1 := cm.LowerList(queryIn)
	wasmimport_Query((*uint8)(queryIn0), (uint32)(queryIn1), &result)
	return
}

// Fetch represents the imported function "fetch".
//
//	fetch: func(query-result: list<u8>) -> list<u8>
//
//go:nosplit
func Fetch(queryResult cm.List[uint8]) (result cm.List[uint8]) {
	queryResult0, queryResult1 := cm.LowerList(queryResult)
	wasmimport_Fetch((*uint8)(queryResult0), (uint32)(queryResult1), &result)
	return
}

// Command represents the imported function "command".
//
//	command: func(command-in: list<u8>) -> list<u8>
//
//go:nosplit
func Command(commandIn cm.List[uint8]) (result cm.List[uint8]) {
	commandIn0, commandIn1 := cm.LowerList(commandIn)
	wasmimport_Command((*uint8)(commandIn0), (uint32)(commandIn1), &result)
	return
}

// Batch represents the imported function "batch".
//
//	batch: func(batch-in: list<u8>) -> list<u8>
//
//go:nosplit
func Batch(batchIn cm.List[uint8]) (result cm.List[uint8]) {
	batchIn0, batchIn1 := cm.LowerList(batchIn)
	wasmimport_Batch((*uint8)(batchIn0), (uint32)(batchIn1), &result)
	return
}

// Open represents the imported function "open".
//
//	open: func(open-in: list<u8>) -> list<u8>
//
//go:nosplit
func Open(openIn cm.List[uint8]) (result cm.List[uint8]) {
	openIn0, openIn1 := cm.LowerList(openIn)
	wasmimport_Open((*uint8)(openIn0), (uint32)(openIn1), &result)
	return
}

// Close represents the imported function "close".
//
//	close: func(close-in: list<u8>) -> list<u8>
//
//go:nosplit
func Close(closeIn cm.List[uint8]) (result cm.List[uint8]) {
	closeIn0, closeIn1 := cm.LowerList(closeIn)
	wasmimport_Close((*uint8)(closeIn0), (uint32)(closeIn1), &result)
	return
}

// Get represents the imported function "get".
//
//	get: func(get-in: list<u8>) -> list<u8>
//
//go:nosplit
func Get(getIn cm.List[uint8]) (result cm.List[uint8]) {
	getIn0, getIn1 := cm.LowerList(getIn)
	wasmimport_Get((*uint8)(getIn0), (uint32)(getIn1), &result)
	return
}

// Put represents the imported function "put".
//
//	put: func(put-in: list<u8>) -> list<u8>
//
//go:nosplit
func Put(putIn cm.List[uint8]) (result cm.List[uint8]) {
	putIn0, putIn1 := cm.LowerList(putIn)
	wasmimport_Put((*uint8)(putIn0), (uint32)(putIn1), &result)
	return
}

// Delete represents the imported function "delete".
//
//	delete: func(delete-in: list<u8>) -> list<u8>
//
//go:nosplit
func Delete(deleteIn cm.List[uint8]) (result cm.List[uint8]) {
	deleteIn0, deleteIn1 := cm.LowerList(deleteIn)
	wasmimport_Delete((*uint8)(deleteIn0), (uint32)(deleteIn1), &result)
	return
}

// Range represents the imported function "range".
//
//	range: func(range-in: list<u8>) -> list<u8>
//
//go:nosplit
func Range(rangeIn cm.List[uint8]) (result cm.List[uint8]) {
	rangeIn0, rangeIn1 := cm.LowerList(rangeIn)
	wasmimport_Range((*uint8)(rangeIn0), (uint32)(rangeIn1), &result)
	return
}

// RelationGet represents the imported function "relation-get".
//
//	relation-get: func(relation-get-in: list<u8>) -> list<u8>
//
//go:nosplit
func RelationGet(relationGetIn cm.List[uint8]) (result cm.List[uint8]) {
	relationGetIn0, relationGetIn1 := cm.LowerList(relationGetIn)
	wasmimport_RelationGet((*uint8)(relationGetIn0), (uint32)(relationGetIn1), &result)
	return
}

// RelationUpdate represents the imported function "relation-update".
//
//	relation-update: func(relation-update-in: list<u8>) -> list<u8>
//
//go:nosplit
func RelationUpdate(relationUpdateIn cm.List[uint8]) (result cm.List[uint8]) {
	relationUpdateIn0, relationUpdateIn1 := cm.LowerList(relationUpdateIn)
	wasmimport_RelationUpdate((*uint8)(relationUpdateIn0), (uint32)(relationUpdateIn1), &result)
	return
}

// RelationInsert represents the imported function "relation-insert".
//
//	relation-insert: func(relation-insert-in: list<u8>) -> list<u8>
//
//go:nosplit
func RelationInsert(relationInsertIn cm.List[uint8]) (result cm.List[uint8]) {
	relationInsertIn0, relationInsertIn1 := cm.LowerList(relationInsertIn)
	wasmimport_RelationInsert((*uint8)(relationInsertIn0), (uint32)(relationInsertIn1), &result)
	return
}

// FsOpen represents the imported function "fs-open".
//
//	fs-open: func(fs-open-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsOpen(fsOpenIn cm.List[uint8]) (result cm.List[uint8]) {
	fsOpenIn0, fsOpenIn1 := cm.LowerList(fsOpenIn)
	wasmimport_FsOpen((*uint8)(fsOpenIn0), (uint32)(fsOpenIn1), &result)
	return
}

// FsClose represents the imported function "fs-close".
//
//	fs-close: func(fs-close-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsClose(fsCloseIn cm.List[uint8]) (result cm.List[uint8]) {
	fsCloseIn0, fsCloseIn1 := cm.LowerList(fsCloseIn)
	wasmimport_FsClose((*uint8)(fsCloseIn0), (uint32)(fsCloseIn1), &result)
	return
}

// FsRead represents the imported function "fs-read".
//
//	fs-read: func(fs-read-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsRead(fsReadIn cm.List[uint8]) (result cm.List[uint8]) {
	fsReadIn0, fsReadIn1 := cm.LowerList(fsReadIn)
	wasmimport_FsRead((*uint8)(fsReadIn0), (uint32)(fsReadIn1), &result)
	return
}

// FsWrite represents the imported function "fs-write".
//
//	fs-write: func(fs-write-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsWrite(fsWriteIn cm.List[uint8]) (result cm.List[uint8]) {
	fsWriteIn0, fsWriteIn1 := cm.LowerList(fsWriteIn)
	wasmimport_FsWrite((*uint8)(fsWriteIn0), (uint32)(fsWriteIn1), &result)
	return
}

// FsPread represents the imported function "fs-pread".
//
//	fs-pread: func(fs-pread-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsPread(fsPreadIn cm.List[uint8]) (result cm.List[uint8]) {
	fsPreadIn0, fsPreadIn1 := cm.LowerList(fsPreadIn)
	wasmimport_FsPread((*uint8)(fsPreadIn0), (uint32)(fsPreadIn1), &result)
	return
}

// FsPwrite represents the imported function "fs-pwrite".
//
//	fs-pwrite: func(fs-pwrite-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsPwrite(fsPwriteIn cm.List[uint8]) (result cm.List[uint8]) {
	fsPwriteIn0, fsPwriteIn1 := cm.LowerList(fsPwriteIn)
	wasmimport_FsPwrite((*uint8)(fsPwriteIn0), (uint32)(fsPwriteIn1), &result)
	return
}

// FsLseek represents the imported function "fs-lseek".
//
//	fs-lseek: func(fs-lseek-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsLseek(fsLseekIn cm.List[uint8]) (result cm.List[uint8]) {
	fsLseekIn0, fsLseekIn1 := cm.LowerList(fsLseekIn)
	wasmimport_FsLseek((*uint8)(fsLseekIn0), (uint32)(fsLseekIn1), &result)
	return
}

// FsFstat represents the imported function "fs-fstat".
//
//	fs-fstat: func(fs-fstat-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsFstat(fsFstatIn cm.List[uint8]) (result cm.List[uint8]) {
	fsFstatIn0, fsFstatIn1 := cm.LowerList(fsFstatIn)
	wasmimport_FsFstat((*uint8)(fsFstatIn0), (uint32)(fsFstatIn1), &result)
	return
}

// FsStat represents the imported function "fs-stat".
//
//	fs-stat: func(fs-stat-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsStat(fsStatIn cm.List[uint8]) (result cm.List[uint8]) {
	fsStatIn0, fsStatIn1 := cm.LowerList(fsStatIn)
	wasmimport_FsStat((*uint8)(fsStatIn0), (uint32)(fsStatIn1), &result)
	return
}

// FsFsync represents the imported function "fs-fsync".
//
//	fs-fsync: func(fs-fsync-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsFsync(fsFsyncIn cm.List[uint8]) (result cm.List[uint8]) {
	fsFsyncIn0, fsFsyncIn1 := cm.LowerList(fsFsyncIn)
	wasmimport_FsFsync((*uint8)(fsFsyncIn0), (uint32)(fsFsyncIn1), &result)
	return
}

// FsReaddir represents the imported function "fs-readdir".
//
//	fs-readdir: func(fs-readdir-in: list<u8>) -> list<u8>
//
//go:nosplit
func FsReaddir(fsReaddirIn cm.List[uint8]) (result cm.List[uint8]) {
	fsReaddirIn0, fsReaddirIn1 := cm.LowerList(fsReaddirIn)
	wasmimport_FsReaddir((*uint8)(fsReaddirIn0), (uint32)(fsReaddirIn1), &result)
	return
}
