@startuml
participant APP
box "DB" #LightBlue
participant Runtime
participant Kernel
end box

APP -> Runtime: request Tx
group In DB Processing
Runtime --> Kernel: query Q1
Runtime <-- Kernel: Q1 result set response
Runtime --> Runtime: do something T1
Runtime --> Kernel: query Q2
Runtime <-- Kernel: Q2 result set response
Runtime --> Runtime: do something T2
Runtime --> Kernel: command C1
Runtime <-- Kernel: C1 end
Runtime --> Kernel: commit
Runtime <-- Kernel: commit success
end
APP <-- Runtime: Tx response

@enduml