// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
use crate::universal::uni_data_type::UniDataType;
#[derive(Debug, Clone)]
pub struct UniFieldAttr {
    pub attr_name: String,
    pub attr_value: String,
}
impl Default for UniFieldAttr {
    fn default() -> Self {
        Self {
            attr_name: Default::default(),
            attr_value: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniFieldAttr {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.attr_name).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                (&self.attr_value).to_value(),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniFieldAttr {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut attr_name = None;
        let mut attr_value = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => attr_name = Some(String::from_value(val)?),
                2 => attr_value = Some(String::from_value(val)?),
                _ => {}
            }
        }
        Ok(Self {
            attr_name: attr_name.unwrap_or_default(),
            attr_value: attr_value.unwrap_or_default(),
        })
    }
}
#[derive(Debug, Clone)]
pub struct UniRecordField {
    pub field_name: String,
    pub field_type: UniDataType,
    pub field_attrs: Vec<UniFieldAttr>,
}
impl Default for UniRecordField {
    fn default() -> Self {
        Self {
            field_name: Default::default(),
            field_type: Default::default(),
            field_attrs: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniRecordField {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.field_name).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                (&self.field_type).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(3u32),
                to_array(&self.field_attrs, |item| (item).to_value()),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniRecordField {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut field_name = None;
        let mut field_type = None;
        let mut field_attrs = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => field_name = Some(String::from_value(val)?),
                2 => field_type = Some(UniDataType::from_value(val)?),
                3 => {
                    field_attrs = Some(from_array(val, |item| UniFieldAttr::from_value(item))?);
                }
                _ => {}
            }
        }
        Ok(Self {
            field_name: field_name.unwrap_or_default(),
            field_type: field_type.unwrap_or_default(),
            field_attrs: field_attrs.unwrap_or_default(),
        })
    }
}
#[derive(Debug, Clone)]
pub struct UniRecordType {
    pub record_name: String,
    pub record_fields: Vec<UniRecordField>,
}
impl Default for UniRecordType {
    fn default() -> Self {
        Self {
            record_name: Default::default(),
            record_fields: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniRecordType {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.record_name).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                to_array(&self.record_fields, |item| (item).to_value()),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniRecordType {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut record_name = None;
        let mut record_fields = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => record_name = Some(String::from_value(val)?),
                2 => {
                    record_fields = Some(from_array(val, |item| UniRecordField::from_value(item))?);
                }
                _ => {}
            }
        }
        Ok(Self {
            record_name: record_name.unwrap_or_default(),
            record_fields: record_fields.unwrap_or_default(),
        })
    }
}
