// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
use crate::universal::uni_data_value::UniDataValue;
use crate::universal::uni_oid::UniOid;
#[derive(Debug, Clone)]
pub struct UniProcedureParam {
    pub procedure: u64,
    pub session: UniOid,
    pub param_list: Vec<UniDataValue>,
}
impl Default for UniProcedureParam {
    fn default() -> Self {
        Self {
            procedure: Default::default(),
            session: Default::default(),
            param_list: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniProcedureParam {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        crate::universal::mp_wire::Value::Map(vec![
            (
                crate::universal::mp_wire::Value::from(1u32),
                (&self.procedure).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(2u32),
                (&self.session).to_value(),
            ),
            (
                crate::universal::mp_wire::Value::from(3u32),
                to_array(&self.param_list, |item| (item).to_value()),
            ),
        ])
    }
}
impl crate::universal::mp_wire::FromValue for UniProcedureParam {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut procedure = None;
        let mut session = None;
        let mut param_list = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => procedure = Some(u64::from_value(val)?),
                2 => session = Some(UniOid::from_value(val)?),
                3 => {
                    param_list = Some(from_array(val, |item| UniDataValue::from_value(item))?);
                }
                _ => {}
            }
        }
        Ok(Self {
            procedure: procedure.unwrap_or_default(),
            session: session.unwrap_or_default(),
            param_list: param_list.unwrap_or_default(),
        })
    }
}
