// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
#[derive(Debug, Clone)]
pub enum UniScalarValue {
    Bool(bool),
    U8(u8),
    I8(i8),
    U16(u16),
    I16(i16),
    U32(u32),
    I32(i32),
    U64(u64),
    U128(Vec<u8>),
    I64(i64),
    I128(Vec<u8>),
    F32(f32),
    F64(f64),
    Char(char),
    String(String),
    Blob(Vec<u8>),
    Numeric(String),
    Date(String),
    Time(String),
    Timestamp(String),
    TimestampTz(String),
    Null,
}
impl Default for UniScalarValue {
    fn default() -> Self {
        Self::Bool(Default::default())
    }
}
impl UniScalarValue {
    pub fn from_bool(inner: bool) -> Self {
        Self::Bool(inner)
    }
    pub fn as_bool(&self) -> Option<&bool> {
        match self {
            Self::Bool(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_bool(&self) -> &bool {
        match self {
            Self::Bool(inner) => inner,
            _ => panic!("UniScalarValue::expect_bool called on the wrong variant"),
        }
    }
    pub fn from_u8(inner: u8) -> Self {
        Self::U8(inner)
    }
    pub fn as_u8(&self) -> Option<&u8> {
        match self {
            Self::U8(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_u8(&self) -> &u8 {
        match self {
            Self::U8(inner) => inner,
            _ => panic!("UniScalarValue::expect_u8 called on the wrong variant"),
        }
    }
    pub fn from_i8(inner: i8) -> Self {
        Self::I8(inner)
    }
    pub fn as_i8(&self) -> Option<&i8> {
        match self {
            Self::I8(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_i8(&self) -> &i8 {
        match self {
            Self::I8(inner) => inner,
            _ => panic!("UniScalarValue::expect_i8 called on the wrong variant"),
        }
    }
    pub fn from_u16(inner: u16) -> Self {
        Self::U16(inner)
    }
    pub fn as_u16(&self) -> Option<&u16> {
        match self {
            Self::U16(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_u16(&self) -> &u16 {
        match self {
            Self::U16(inner) => inner,
            _ => panic!("UniScalarValue::expect_u16 called on the wrong variant"),
        }
    }
    pub fn from_i16(inner: i16) -> Self {
        Self::I16(inner)
    }
    pub fn as_i16(&self) -> Option<&i16> {
        match self {
            Self::I16(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_i16(&self) -> &i16 {
        match self {
            Self::I16(inner) => inner,
            _ => panic!("UniScalarValue::expect_i16 called on the wrong variant"),
        }
    }
    pub fn from_u32(inner: u32) -> Self {
        Self::U32(inner)
    }
    pub fn as_u32(&self) -> Option<&u32> {
        match self {
            Self::U32(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_u32(&self) -> &u32 {
        match self {
            Self::U32(inner) => inner,
            _ => panic!("UniScalarValue::expect_u32 called on the wrong variant"),
        }
    }
    pub fn from_i32(inner: i32) -> Self {
        Self::I32(inner)
    }
    pub fn as_i32(&self) -> Option<&i32> {
        match self {
            Self::I32(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_i32(&self) -> &i32 {
        match self {
            Self::I32(inner) => inner,
            _ => panic!("UniScalarValue::expect_i32 called on the wrong variant"),
        }
    }
    pub fn from_u64(inner: u64) -> Self {
        Self::U64(inner)
    }
    pub fn as_u64(&self) -> Option<&u64> {
        match self {
            Self::U64(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_u64(&self) -> &u64 {
        match self {
            Self::U64(inner) => inner,
            _ => panic!("UniScalarValue::expect_u64 called on the wrong variant"),
        }
    }
    pub fn from_u128(inner: Vec<u8>) -> Self {
        Self::U128(inner)
    }
    pub fn as_u128(&self) -> Option<&Vec<u8>> {
        match self {
            Self::U128(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_u128(&self) -> &Vec<u8> {
        match self {
            Self::U128(inner) => inner,
            _ => panic!("UniScalarValue::expect_u128 called on the wrong variant"),
        }
    }
    pub fn from_i64(inner: i64) -> Self {
        Self::I64(inner)
    }
    pub fn as_i64(&self) -> Option<&i64> {
        match self {
            Self::I64(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_i64(&self) -> &i64 {
        match self {
            Self::I64(inner) => inner,
            _ => panic!("UniScalarValue::expect_i64 called on the wrong variant"),
        }
    }
    pub fn from_i128(inner: Vec<u8>) -> Self {
        Self::I128(inner)
    }
    pub fn as_i128(&self) -> Option<&Vec<u8>> {
        match self {
            Self::I128(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_i128(&self) -> &Vec<u8> {
        match self {
            Self::I128(inner) => inner,
            _ => panic!("UniScalarValue::expect_i128 called on the wrong variant"),
        }
    }
    pub fn from_f32(inner: f32) -> Self {
        Self::F32(inner)
    }
    pub fn as_f32(&self) -> Option<&f32> {
        match self {
            Self::F32(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_f32(&self) -> &f32 {
        match self {
            Self::F32(inner) => inner,
            _ => panic!("UniScalarValue::expect_f32 called on the wrong variant"),
        }
    }
    pub fn from_f64(inner: f64) -> Self {
        Self::F64(inner)
    }
    pub fn as_f64(&self) -> Option<&f64> {
        match self {
            Self::F64(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_f64(&self) -> &f64 {
        match self {
            Self::F64(inner) => inner,
            _ => panic!("UniScalarValue::expect_f64 called on the wrong variant"),
        }
    }
    pub fn from_char(inner: char) -> Self {
        Self::Char(inner)
    }
    pub fn as_char(&self) -> Option<&char> {
        match self {
            Self::Char(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_char(&self) -> &char {
        match self {
            Self::Char(inner) => inner,
            _ => panic!("UniScalarValue::expect_char called on the wrong variant"),
        }
    }
    pub fn from_string(inner: String) -> Self {
        Self::String(inner)
    }
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_string(&self) -> &String {
        match self {
            Self::String(inner) => inner,
            _ => panic!("UniScalarValue::expect_string called on the wrong variant"),
        }
    }
    pub fn from_blob(inner: Vec<u8>) -> Self {
        Self::Blob(inner)
    }
    pub fn as_blob(&self) -> Option<&Vec<u8>> {
        match self {
            Self::Blob(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_blob(&self) -> &Vec<u8> {
        match self {
            Self::Blob(inner) => inner,
            _ => panic!("UniScalarValue::expect_blob called on the wrong variant"),
        }
    }
    pub fn from_numeric(inner: String) -> Self {
        Self::Numeric(inner)
    }
    pub fn as_numeric(&self) -> Option<&String> {
        match self {
            Self::Numeric(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_numeric(&self) -> &String {
        match self {
            Self::Numeric(inner) => inner,
            _ => panic!("UniScalarValue::expect_numeric called on the wrong variant"),
        }
    }
    pub fn from_date(inner: String) -> Self {
        Self::Date(inner)
    }
    pub fn as_date(&self) -> Option<&String> {
        match self {
            Self::Date(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_date(&self) -> &String {
        match self {
            Self::Date(inner) => inner,
            _ => panic!("UniScalarValue::expect_date called on the wrong variant"),
        }
    }
    pub fn from_time(inner: String) -> Self {
        Self::Time(inner)
    }
    pub fn as_time(&self) -> Option<&String> {
        match self {
            Self::Time(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_time(&self) -> &String {
        match self {
            Self::Time(inner) => inner,
            _ => panic!("UniScalarValue::expect_time called on the wrong variant"),
        }
    }
    pub fn from_timestamp(inner: String) -> Self {
        Self::Timestamp(inner)
    }
    pub fn as_timestamp(&self) -> Option<&String> {
        match self {
            Self::Timestamp(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_timestamp(&self) -> &String {
        match self {
            Self::Timestamp(inner) => inner,
            _ => panic!("UniScalarValue::expect_timestamp called on the wrong variant"),
        }
    }
    pub fn from_timestamp_tz(inner: String) -> Self {
        Self::TimestampTz(inner)
    }
    pub fn as_timestamp_tz(&self) -> Option<&String> {
        match self {
            Self::TimestampTz(inner) => Some(inner),
            _ => None,
        }
    }
    pub fn expect_timestamp_tz(&self) -> &String {
        match self {
            Self::TimestampTz(inner) => inner,
            _ => {
                panic!("UniScalarValue::expect_timestamp_tz called on the wrong variant")
            }
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniScalarValue {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        match self {
            UniScalarValue::Bool(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(0u32),
                (inner).to_value(),
            ]),
            UniScalarValue::U8(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(1u32),
                (inner).to_value(),
            ]),
            UniScalarValue::I8(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(2u32),
                (inner).to_value(),
            ]),
            UniScalarValue::U16(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(3u32),
                (inner).to_value(),
            ]),
            UniScalarValue::I16(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(4u32),
                (inner).to_value(),
            ]),
            UniScalarValue::U32(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(5u32),
                (inner).to_value(),
            ]),
            UniScalarValue::I32(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(6u32),
                (inner).to_value(),
            ]),
            UniScalarValue::U64(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(7u32),
                (inner).to_value(),
            ]),
            UniScalarValue::U128(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(8u32),
                (inner).to_value(),
            ]),
            UniScalarValue::I64(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(9u32),
                (inner).to_value(),
            ]),
            UniScalarValue::I128(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(10u32),
                (inner).to_value(),
            ]),
            UniScalarValue::F32(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(11u32),
                (inner).to_value(),
            ]),
            UniScalarValue::F64(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(12u32),
                (inner).to_value(),
            ]),
            UniScalarValue::Char(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(13u32),
                (inner).to_value(),
            ]),
            UniScalarValue::String(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(14u32),
                (inner).to_value(),
            ]),
            UniScalarValue::Blob(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(15u32),
                (inner).to_value(),
            ]),
            UniScalarValue::Numeric(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(16u32),
                (inner).to_value(),
            ]),
            UniScalarValue::Date(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(17u32),
                (inner).to_value(),
            ]),
            UniScalarValue::Time(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(18u32),
                (inner).to_value(),
            ]),
            UniScalarValue::Timestamp(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(19u32),
                (inner).to_value(),
            ]),
            UniScalarValue::TimestampTz(inner) => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(20u32),
                (inner).to_value(),
            ]),
            UniScalarValue::Null => crate::universal::mp_wire::Value::Array(vec![
                crate::universal::mp_wire::Value::from(21u32),
                crate::universal::mp_wire::Value::from(0u8),
            ]),
        }
    }
}
impl crate::universal::mp_wire::FromValue for UniScalarValue {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let items = value.as_array()?;
        if items.len() != 2 {
            return Err(crate::universal::mp_wire::WireError::new(format!(
                "a {} value must be a 2-element [tag, payload] array, found {} elements",
                "UniScalarValue",
                items.len()
            )));
        }
        let tag = u32::from_value(&items[0])?;
        match tag {
            0 => Ok(Self::Bool(bool::from_value(&items[1])?)),
            1 => Ok(Self::U8(u8::from_value(&items[1])?)),
            2 => Ok(Self::I8(i8::from_value(&items[1])?)),
            3 => Ok(Self::U16(u16::from_value(&items[1])?)),
            4 => Ok(Self::I16(i16::from_value(&items[1])?)),
            5 => Ok(Self::U32(u32::from_value(&items[1])?)),
            6 => Ok(Self::I32(i32::from_value(&items[1])?)),
            7 => Ok(Self::U64(u64::from_value(&items[1])?)),
            8 => Ok(Self::U128((&items[1]).as_bin()?)),
            9 => Ok(Self::I64(i64::from_value(&items[1])?)),
            10 => Ok(Self::I128((&items[1]).as_bin()?)),
            11 => Ok(Self::F32(f32::from_value(&items[1])?)),
            12 => Ok(Self::F64(f64::from_value(&items[1])?)),
            13 => Ok(Self::Char(char::from_value(&items[1])?)),
            14 => Ok(Self::String(String::from_value(&items[1])?)),
            15 => Ok(Self::Blob((&items[1]).as_bin()?)),
            16 => Ok(Self::Numeric(String::from_value(&items[1])?)),
            17 => Ok(Self::Date(String::from_value(&items[1])?)),
            18 => Ok(Self::Time(String::from_value(&items[1])?)),
            19 => Ok(Self::Timestamp(String::from_value(&items[1])?)),
            20 => Ok(Self::TimestampTz(String::from_value(&items[1])?)),
            21 => Ok(Self::Null),
            _ => Err(crate::universal::mp_wire::WireError::new(format!(
                "unknown UniScalarValue tag {tag}"
            ))),
        }
    }
}
