// Generated by mudu_gen. Do not edit manually.
#![allow(
    dead_code,
    unused_imports,
    clippy::borrowed_box,
    clippy::derivable_impls,
    clippy::map_identity,
    clippy::needless_borrow,
    clippy::panic,
    clippy::ptr_arg,
    clippy::redundant_closure,
    clippy::single_match,
    clippy::type_complexity
)]
use crate::universal::mp_wire::{
    FromValue, ToValue, Value, WireError, from_array, from_option, from_tuple2, from_tuple3,
    to_array, to_option, to_tuple2, to_tuple3,
};
use crate::universal::uni_data_value::UniDataValue;
#[derive(Debug, Clone)]
pub struct UniSqlParam {
    pub params: Vec<UniDataValue>,
    pub param_names: Option<Vec<String>>,
}
impl Default for UniSqlParam {
    fn default() -> Self {
        Self {
            params: Default::default(),
            param_names: Default::default(),
        }
    }
}
impl crate::universal::mp_wire::ToValue for UniSqlParam {
    fn to_value(&self) -> crate::universal::mp_wire::Value {
        #[allow(unused_mut)]
        let mut fields = vec![(
            crate::universal::mp_wire::Value::from(1u32),
            to_array(&self.params, |item| (item).to_value()),
        )];
        if self.param_names.is_some() {
            fields.push((
                crate::universal::mp_wire::Value::from(2u32),
                to_option(&self.param_names, |item| {
                    to_array(item, |item| (item).to_value())
                }),
            ));
        }
        crate::universal::mp_wire::Value::Map(fields)
    }
}
impl crate::universal::mp_wire::FromValue for UniSqlParam {
    fn from_value(
        value: &crate::universal::mp_wire::Value,
    ) -> Result<Self, crate::universal::mp_wire::WireError> {
        let map_pairs = value.as_map()?;
        let mut params = None;
        let mut param_names = None;
        for (key, val) in map_pairs {
            let Ok(number) = key.as_u64() else {
                continue;
            };
            match number {
                1 => {
                    params = Some(from_array(val, |item| UniDataValue::from_value(item))?);
                }
                2 => {
                    param_names = Some(from_option(val, |item| {
                        from_array(item, |item| String::from_value(item))
                    })?);
                }
                _ => {}
            }
        }
        Ok(Self {
            params: params.unwrap_or_default(),
            param_names: param_names.unwrap_or_default(),
        })
    }
}
